### ISSUE TITLE
Android - text input field in a DM chat has too much padding

### ISSUE THREAD

**Issue by michaelhaxhiu** [Expensify/Expensify.cash#1002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!

Upwork job post - https://www.upwork.com/jobs/~01ed3f44a74b174dd1
___

**Platform - version:**  
Platform - Android (Xiaomi Redmi Note 8 / Android 9.0)
Version - v1.0.1.269

**Action Performed (reproducible steps):**
1. Open the Expensify.cash app
2. Log in
3. Tap the hamburger menu button( ☰ ) in the top-left
4. Start a new DM (or select an existing DM)
5. Observe the text input box, and see too much padding at the top of the box.

**Expected Result:**
Chat input box should have the same padding (white space) on the top and bottom

**Actual Result:**
The text box has too much padding / white space in the top

**Notes/Photos/Videos:** 
<img width=300 src=https://user-images.githubusercontent.com/13206896/102492837-9d8cb780-4048-11eb-9a6b-30c1d5f176e9.png>

**Logs - JS/Android/iOS (if applicable)**:
N/A

**Comment by muhammadusama95** [comment]
Go to ReportActionCompose.js File. Go to Parent View then there are multiple containers i.e. attachments, send button, and input text field. There was a problem with the input text field view styles. There was Unnecessary padding of the input text field which was causing the extra space at the top and was not setting the input text view to the center of the parent view So we removed that and input text is at the center of the parent view and the top spacing has been removed using top, bottom padding value to 0 and I have tested this.

**Comment by michaelhaxhiu** [comment]
Assigned you, feel free to proceed!

**Comment by michaelhaxhiu** [comment]
Going to assign Brian Muks, as he's prepared the PR for the fix and seems close!

**Comment by brianmuks** [comment]
> Going to assign Brian Muks, as he's prepared the PR for the fix and seems close!

Thanks

**Comment by michaelhaxhiu** [comment]
✅
