### ISSUE TITLE
Graphical alignment issues in chat upon first sign-in

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1031]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  

**Action Performed (reproducible steps):**
1. Start the app on in an Incognito browser
2. Hard refresh the page
3. type in your username and password, and tap 'Log in'
4. Once you're logged in, tap the hamburger menu, type in `concierge@` in the text box, and tap on the `Concierge` user
5. Notice the off-center paperclip icon and misaligned presence indicator (green dot)

**Expected Result:**
1. The paperclip icon should remain centered on initial load and subsequent access.
2. The green dot should be correctly aligned with the profile image
3. This should be solved holistically, not as a one-off solution for each of the problems. The graphical elements are supposed to be absolute positioned, but on initial page load, this is being overruled by a position:relative. The order the styles show up in the debugger appear to change after refreshing. To see the problem occur after initial load, you must log out and refresh, then log back in. In other words, a fix will only be considered acceptable if it fixes the underlying cause of the issue, rather than masking the symptom(s). 'Band-aid' fixes are unacceptable.

**Actual Result:**
The paper clip is not centered
The green dot appears below the profile icon

**Notes/Photos/Videos:** 

![off center (2)](https://user-images.githubusercontent.com/24399930/102103181-aa1bd080-3dfa-11eb-9d67-6c9fe5ee746b.png)

![image](https://user-images.githubusercontent.com/24399930/102814425-a1963d80-4398-11eb-82b4-5cbeba8493ec.png)

View the Upwork job [here](https://www.upwork.com/jobs/~018bda224287da8095).

**Comment by ilijaprzeski** [comment]
So, react-native-web plugin in babel.config.js file was causing this issue. So to fix this issue, we should remove react-native-web plugin in babel.config.js
