### ISSUE TITLE
Allow download of images shared in chat

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1040]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
All platforms / 280

**Action Performed (reproducible steps):**
1. Log into Expensify Cash
2. Click the paperclip icon
3. Select an image and confirm the upload
4. Once the image uploads to the chat, click the image
5. Notice that there is no way to download the image in the Attachment modal

**Expected Result:**
The modal should provide an icon that can be clicked to download the image.

**Actual Result:**
There is no way to download the image

**Notes/Photos/Videos:**
 
 Here is what it currently looks like:
![image](https://user-images.githubusercontent.com/24399930/102933845-1177f700-4471-11eb-84f5-b252724c5cba.png)

Instead, we'd like to include a download button:
<img width="584" alt="101112969-47713c00-3593-11eb-89ed-02b61f92bcbc-1" src="https://user-images.githubusercontent.com/24399930/102933921-2f455c00-4471-11eb-83f1-f073029f3c3d.png">

The icon asset can be found here:
![101107234-ba27ea80-3586-11eb-940c-024ae39438ca](https://user-images.githubusercontent.com/24399930/102933945-366c6a00-4471-11eb-84d8-be466e71e7d7.png)

After downloading, please confirm the image is stored on the device.

view the job on Upwork [here](https://www.upwork.com/jobs/~01340639ab0b967185).

**Comment by daniyal-intellicel** [comment]
Hi, 
My proposal for solution:
1. Adding download image button (as provided in this issue's description)
2. Binding this button to a download action
3. For native mobile apps download action will use `rn-fetch-blob` library to download files to Download folder of device
4. For web/desktop download action will use js `fetch` to download file and then send it to web window to be saved

**Comment by marcaaron** [comment]
@daniyal-intellicel Thanks! This plan sounds good, but I have a few questions... 

1. Are you planning to generalize the "download" behavior? e.g. Is it something that could be used to "download" anything in the future? 
2. When you say a "download action", what do you mean by this? Is it a utility method? Component? Something else?

**Comment by daniyal-intellicel** [comment]
@marcaaron Thanks!

1. Yes "download" action will be generalised to download almost any file. It will take attachment/file url and perform platform specific download.
2.  Download action will be a utility method defined under src/libs folder.

**Comment by bullseye405** [comment]
We could use [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) or 
[react-native-fs](https://github.com/itinance/react-native-fs)

Using this, we can create a small component, put that component next to the close button and use the download icon ( which is in png, should we not use a svg? ) to download the file

**Comment by arielgreen** [comment]
Looks good @bullseye405, please proceed with your PR. 

@shawnborton is png correct or should the icon be svg format?

**Comment by shawnborton** [comment]
We should use an .svg for the icon. You should be able to take a look at how we're handling .svg icons elsewhere in the app.

**Comment by arielgreen** [comment]
@bullseye405, please provide an update.

**Comment by smokfyz** [comment]
I have solved this issue with rn-fetch-blob.
const { config, fs } = RNFetchBlob
let PictureDir = fs.dirs.PictureDir
let options = {
  fileCache: true,
  addAndroidDownloads : {
    useDownloadManager : true, 
    notification : false,
    path:  PictureDir + "/me_"+Math.floor(date.getTime() + date.getSeconds() / 2),
    description : 'Downloading image.'
  }
}
config(options).fetch('GET', "http://www.example.com/example.png").then((res) => {
    //
})

**Comment by SameeraMadushan** [comment]
Hi,

I submitted a proposal on Upwork and I would like to handle this task.
I will explain my approach to solve this.

### Problem
The modal should provide an icon that can be clicked to download the image.

### Suggested solution
This function will be implemented as a reusable function inside `src/libs`.
Any type of file download will be possible

#### iOS and Android

- I will use `rn-fetch-blob` for both iOS and Android
- I checked and this package is already installed and WRITE_EXTERNAL_STORAGE permission also already enabled.

#### Web, Desktop and mobile web

- I will use fetch and create blob link to download the file

Thanks,
Sameera

**Comment by arielgreen** [comment]
Thanks for the proposals! @SameeraMadushan, we'd like to move forward. Sending over an offer via Upwork now. Once you have accepted that, please proceed with your PR.

**Comment by SameeraMadushan** [comment]
@arielgreen 
Can you provide me the `.svg` image for the download icon? I found the attachment but it's in `.png` format.

**Comment by marcaaron** [comment]
cc @shawnborton if you are around to help us out with this :) 🙏

**Comment by shawnborton** [comment]
Here ya go: [download.svg.zip](https://github.com/Expensify/Expensify.cash/files/6052078/download.svg.zip)

**Comment by SameeraMadushan** [comment]
Hi @marcaaron 
In Expensify web, Im getting cross-origin issue when opening a `.pdf` file.
Because the asset url is from expensify domain and my dev env is localhost.

Also I'm getting the same error when I try to download the file (images and pdf).
For the development purpose I used [cors-anywhere](https://cors-anywhere.herokuapp.com/) to by pass the cors.
Do you have any idea about this?

**Comment by parasharrajat** [comment]
@SameeraMadushan Look at #1509. It will help.

**Comment by SameeraMadushan** [comment]
@parasharrajat thanks. I'll check.😋
