### ISSUE TITLE
Test issue for assignment 

### ISSUE THREAD

**Issue by stephanieelliott** [Expensify/Expensify.cash#1047]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  

**Action Performed (reproducible steps):**

**Expected Result:**

**Actual Result:**

**Notes/Photos/Videos:** 
 
**Logs - JS/Android/iOS (if applicable)**:

**Comment by billbillbill100** [comment]
Hello I would like to pick up this issue.
