### ISSUE TITLE
Web - Confusing experience as a newly signed up user

### ISSUE THREAD

**Issue by dylmye** [Expensify/Expensify.cash#1081]
I signed up to the platform from your email as a user without an existing Expensify account. After completing the sign-up flow, I was redirected to https://expensify.cash/#/r/undefined where the page was pretty much blank - see attached photo. It looks even more confusing on mobile where it's single-column. The search box wouldn't bring back any results.

I understand this may be low priority in the beta, I just thought it would be worth flagging.
___

**Platform - version:** Windows 10 / Firefox, 1.0.1-292

**Action Performed (reproducible steps):**
1. On the public homepage, sign up for Expensify.cash with a GitHub username
2. Load public homepage logged in (https://expensify.cash/)

**Expected Result:**
* Empty state message on the message pane (eg "Select a message")
* Empty state message in the messages list (eg "To get started, search for someone to message")
* Documentation/linking to set up expensify account first - or validation that the account is an expensify account when signing up

**Actual Result:**
* Screen is blank

**Notes/Photos/Videos:** 
![Screenshot of issue on desktop](https://user-images.githubusercontent.com/7024578/103033936-a5be8880-455b-11eb-9d8e-6dddd2b2c75b.png)
<img src="https://user-images.githubusercontent.com/7024578/103034101-05b52f00-455c-11eb-8f78-401a4573cfba.png" alt="Screenshot of issue on mobile" style="width: 200px" />

**Logs - JS/Android/iOS (if applicable)**: _n/a_

**Comment by puneetlath** [comment]
Thanks for creating this issue @dylmye! I agree this is a very confusing entry experience into the app. We'll chat internally a bit about what we think the best landing experience should be and then post back in this issue.

**Comment by kadiealexander** [comment]
Hey there @dylmye! We've made a lot of updates to the UI for expensify.cash since this issue was raised. Would you be able to review your request and see if it still applies? Thanks!!

**Comment by dylmye** [comment]
> Would you be able to review your request and see if it still applies? Thanks!!

Now it opens up with the list of conversations which is definitely clearer. Thanks for keeping this ticket updated!
