### ISSUE TITLE
Cheer up new chats with improved empty-state microcopy

### ISSUE THREAD

**Issue by quinthar** [Expensify/Expensify.cash#1095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  All

**Action Performed (reproducible steps):**
Start a new chat as follows:;
1. Click/tap on the chat switcher
2. Choose someone you've never chatted with before
3. Note the content "Be the first person to comment!"

**Expected Result:**
I'd love to see it randomly pick from a whole bunch of clever introductions -- Tinder does this nicely, let's copy that.  Some examples of content:
* Be the first person to comment!
* Ten points to whoever speaks first!
* Say it, you know you want to...
* Less thinking, more typing
* C'mon, what are you waiting for?
* Protip: Start out by saying Hello

**Actual Result:**
In practice it only says "Be the first person to comment!", every time.

**Notes/Photos/Videos:** 
None.
 
**Logs - JS/Android/iOS (if applicable)**:
n/a

**Comment by jamesdeanexpensify** [comment]
Other potentials:
- If not now, when? Start a chat!
- Come on in, water's warm!
- Hello, hola, bonjour, ciao, etc.
- What's up?
- It's polite to say hello.

**Comment by NickTooker** [comment]
Additional options:

- Clear for takeoff!
- Come in! The door's open!
- Permission to chat? Permission granted!
- Howdy?

**Comment by rosegrech** [comment]
I believe this new GH here overlaps with this [GH](https://github.com/Expensify/Expensify/issues/142661) that Gabi started a while ago where we worked on some intro copy and images. It has not yet been implemented.
I do like some of the copy proposed copy in this one particularly these but not sure if we now want to have an image with each intro?

> Clear for takeoff!
> Hello, hola, bonjour, ciao, etc.
> If not now, when? Start a chat!
> Say it, you know you want to...

**Comment by laurenreidexpensify** [comment]
It's super easy to add to the library if we want to add more or change these down the line, so let's build the functionality using David's suggestions, to get started and then edit these as v2?

**Comment by GabiHExpensify** [comment]
hey @quinthar, we have [another GH](https://github.com/Expensify/Expensify/issues/142661) for this already -- it only has a few copy variants, but also includes animations, to help fill up the empty white space. I think we should move forward with that one because the animations are a nice touch IMO, but we could add some more copy variants if you don't think what we have is enough.

**Comment by GabiHExpensify** [comment]
I'm gonna close this GH and combine some of these suggestions into the other one that we were already working on. Head over there to follow along! https://github.com/Expensify/Expensify/issues/142661
