### ISSUE TITLE
User sign up flow broken on Android

### ISSUE THREAD

**Issue by anthony-hull** [Expensify/Expensify.cash#1131]
**Platform - version:**  
Android
Version: 1.0.1-307

**Action Performed (reproducible steps):**
Clear app data
Enter unique email address (sign up as a new user)
Enter github username

**Expected Result:**
taken to the next screen showing:
Expensify.cash
Please validate your account by clicking on the link we just sent you.

**Actual Result:**
Component exception screen
When dismissed the only way to get out of this state is to clear the app data.

**Notes/Photos/Videos:** 
 ![photo_2020-12-30_14-05-57](https://user-images.githubusercontent.com/47184118/103356208-35a68a00-4aa8-11eb-9e91-654e7dbd9b55.jpg)

~~I have not been able to test on iOS yet. I will post later when I have had the chance to fix my environment.~~
Confirmed broken on iOS with the same error.

It appears to work fine on Web app and MacOS Desktop app.
**Logs - JS/Android/iOS (if applicable)**:

**Comment by anthony-hull** [comment]
The validation emails are sent as normal after the github username is entered

**Comment by tgolen** [comment]
A came across this in my testing for https://github.com/Expensify/Expensify.cash/pull/1122 and fixed it in that PR.
