### ISSUE TITLE
No error handling for expired password reset tokens

### ISSUE THREAD

**Issue by anthony-hull** [Expensify/Expensify.cash#1133]
**Platform - version:**  
1.0.1-307

**Action Performed (reproducible steps):**
Browse to an old password reset link
enter anything in as a password
submit the change
**Expected Result:**
Some kind of error message and the loading state to end:

**Actual Result:**
Submit button is stuck on loading state using response data:
"message":"Validate code is likely expired","title":"Validate code failed"

**Notes/Photos/Videos:** 
 
**Logs - JS/Android/iOS (if applicable)**:

JSON response from server:
{"code":666,"jsonCode":404,"type":"Expensify\\Libs\\Error\\ExpError","UUID":"4a16d616-589d-47a2-9e3a-50729c33520a","message":"Validate code is likely expired","title":"Validate code failed","data":[],"htmlMessage":"","requestID":"0755f92ad400002c7644847000000001"}

**Comment by tgolen** [comment]
Thanks for reporting this! I ran across this too and put the fix for it along with https://github.com/Expensify/Expensify.cash/pull/1122
