### ISSUE TITLE
Non-human language name for Concierge user when showing typing status of Concierge in a chat

### ISSUE THREAD

**Issue by anthony-hull** [Expensify/Expensify.cash#1134]
**Platform - version:**  
1.0.1-307

**Action Performed (reproducible steps):**
Send a message to the Concierge user to ask them to type a message to you slowly so you have time to see the message show
**Expected Result:**
A message status below the text box saying "Concierge is typing"
**Actual Result:**
Status says:
userLogin is typing

**Notes/Photos/Videos:**
<img width="1321" alt="Screenshot 2020-12-30 at 16 23 30" src="https://user-images.githubusercontent.com/47184118/103367014-e9fddb80-4abb-11eb-99d7-6d28aa6661e5.png">

 
 
**Logs - JS/Android/iOS (if applicable)**:

**Comment by laurenreidexpensify** [comment]
Hey @anthony-hull Thanks for writing this up.

Can you confirm - 
- Thats error is still occurring 
- whether you have a proposed solution for fixing it?

Thanks!

**Comment by anthony-hull** [comment]
Hey Lauren, it looks like this bug is fixed in the lastest version: 1.0.1-406 when I just checked now. I will close the issue down.

**Comment by laurenreidexpensify** [comment]
Cool thanks @anthony-hull - sorry we missed this one in the launch shuffle! Appreciate you reporting it
