### ISSUE TITLE
Web - charset not declared

### ISSUE THREAD

**Issue by dylmye** [Expensify/Expensify.cash#1148]
**Platform - version:**  
Firefox latest - Windows 10
Chrome latest - Windows 10

**Action Performed (reproducible steps):**
1. Navigate to any page on the expensify.cash domain.

**Expected Result:**
No error message present in console

**Actual Result:**
Following error message is present in console:
> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

![image](https://user-images.githubusercontent.com/7024578/103422241-56e6a380-4b98-11eb-8edf-b422e397c0a0.png)

**Solution:**
Declaration of the meta 'charset' tag. Typically UTF-8 is used. From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset):
> This attribute declares the document's character encoding. If the attribute is present, its value must be an ASCII case-insensitive match for the string "utf-8", because UTF-8 is the only valid encoding for HTML5 documents. meta elements which declare a character encoding must be located entirely within the first 1024 bytes of the document.

**Comment by roryabraham** [comment]
This seems like a good idea. @dylmye Feel free to create a PR for this. All you'll need to do is add `<meta charset="UTF-8"/>` just under the opening `<head>` tag in [`/web/index.html`](https://github.com/Expensify/Expensify.cash/blob/master/web/index.html)

**Comment by timszot** [comment]
cc: @laurenreidexpensify @stephanieelliott
