### ISSUE TITLE
Fix switching to a chat with a saved draft

### ISSUE THREAD

**Issue by iwiznia** [Expensify/Expensify.cash#1183]
# Reproduction steps

- Open a chat
- Write a very long text that makes the field grow, but do not send it
- Open another chat
- Click on the original one that is shown in the sidebar with a pencil icon (indicating you have a draft message)
- The cursor is at the beginning of the written text
- The text area is smaller than it should be

# Solution

Make it so that when you switch back to the draft, the cursor is at the end of the message and the text area is the correct size

# Screenshots

<img width="897" alt="Screen Shot 2021-01-06 at 7 41 37 AM" src="https://user-images.githubusercontent.com/1058475/103788689-fb7f4000-4ff3-11eb-90e7-b3b3f19d73ef.png">
<img width="884" alt="Screen Shot 2021-01-06 at 7 41 43 AM" src="https://user-images.githubusercontent.com/1058475/103788695-fcb06d00-4ff3-11eb-9044-fb5a84aa9ace.png">

Platform - version: all - latest

https://www.upwork.com/jobs/~01f468f9e296585e08

**Comment by UpworkBartkoski** [comment]
I am working on this.
