### ISSUE TITLE
Misaligned loading icon on web

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
web, current

**Action Performed (reproducible steps):**

1. Go to https://expensify.cash/#/signin
2. Type an email and click continue

**Expected Result:**
Loading sign is centered

**Actual Result:**
Loading sign is misaligned. This occurs intermittently.

**Notes/Photos/Videos:** 

![2020-12-29_11-11-46 (1)](https://user-images.githubusercontent.com/37308300/103824746-825b0980-5042-11eb-9167-55d3c241db3e.gif)

![image](https://user-images.githubusercontent.com/37308300/103824769-8be47180-5042-11eb-9480-3e37d704247a.png)

https://github.com/Expensify/Expensify/issues/149155
https://www.upwork.com/jobs/~01460954c9e7b0d41d

**Comment by codelover1110** [comment]
Hi, Arielgreen.
How are you doing?
I do hope to contribute to you project.
Is there any chance I can work with your best project?
Looking forward to hearing from you.
Thank you.

**Comment by codelover1110** [comment]
I saw your task on the Upwork.
But unfortunately, you've already hired another guy.
How can I get a good chance to work with you?

**Comment by arielgreen** [comment]
No longer reproducible.

**Comment by codelover1110** [comment]
ok
