### ISSUE TITLE
Reduce Number of Reconnection Callbacks on Chat app 

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/Expensify.cash#1204]
### **Problem**
The reconnection callbacks fire frequently as a means of catching up the user when:

- They move from offline to online
- They move from active to inactive
- Laptop is closed and reopened
- This is a problem because the act of firing all the reconnection callbacks is a very expensive task. There isn't really any great reason why it should be so expensive and the reasons why should be investigated and fixed. However, this issue is only about reducing how often they run.

To do this we need to stop using the `AppState listener `and instead use Pusher's `pusher:subscription_succeeded` event as mentioned [here](https://support.pusher.com/hc/en-us/articles/360025880633-How-Can-I-Get-Missed-Messages-After-Reconnecting-To-Channels-).

The AppState listener here was added so that we would be able to catch up on missed data when putting the iOS or Android app into the background. Pusher loses connectivity in this case and when it comes back online we aren't sure if we've missed anything so we naively assume that we have and fire the reconnection callbacks.

See relevant code section [here](https://github.com/Expensify/Expensify.cash/blob/0603df60dd13385aacf7ff001815f7224b7875bb/src/libs/NetworkConnection.js#L102-L105)

### Why is this important?
We should only ask users to "catch up" on data they've missed when they need to.

### Solution
Reduce number of calls to reconnection callbacks by ditching AppState listener in favor of the Pusher solution linked in the article

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01a0d4874dc1c6aa07

**Comment by parasharrajat** [comment]
I am starting on this one.

**Comment by parasharrajat** [comment]
So I found. then when we move away from the tab in the browser then AppState changes. which is pretty bad as we were already connected to the internet.
So pusher event will just play nicely. But there are cases where reconnectionCallbacks are running independently of AppState. I will dig deep and try to reduce that behaviour as much possible after adopting the Pusher event solution. BTW thanks for sharing the solution as well.

**Comment by laurenreidexpensify** [comment]
@parasharrajat how's things going on this one?

**Comment by parasharrajat** [comment]
I will prepare PR Today. Before that, I would like to confirm if my solution is fine or I am missing something. There are three cases
1. They move from offline to online
2. They move from active to inactive
3. Laptop is closed and reopened.

So I was thinking to swap the AppState `change` event with the `pusher:subscription_succeeded` event. For this, I will bind the  `pusher:subscription_succeeded` with each channel and when this will be fired the callback will be called. Is this what you are looking for?

**Comment by laurenreidexpensify** [comment]
cc @marcaaron

**Comment by marcaaron** [comment]
@parasharrajat yep that's all correct so far.

>But I see that callbacks are independent of Channels so there is not the way to link a callback to a channel. Now what we can do is check for the pusher:subscription_succeeded on any channel and assume that pusher has reconnected and fire the callbacks.

Right I think what we are going to need to do here is:

- Create another callback for the `subscription_succeeded` event when calling `Pusher.subscribe()`. Fix the logic in the Pusher wrapper so that the `subscription_succeeded` callback can also fire more than once (I believe it's prevented at the moment).

https://github.com/Expensify/Expensify.cash/blob/7823b07422f3bbc935f9e9f57f8e60e099c12a11/src/libs/Pusher/pusher.js#L200-L202

We will need to prevent the duplicate event binding another way - one idea is to use a Boolean flag in the closure formed then only call `bindEventToChannel()` if we have not yet called it?

https://github.com/Expensify/Expensify.cash/blob/7823b07422f3bbc935f9e9f57f8e60e099c12a11/src/libs/Pusher/pusher.js#L198

**Comment by parasharrajat** [comment]
@marcaaron. Ok so we enable `subscription_succeeded` to be fired more than once by removing this 
```
channel.unbind('pusher:subscription_succeeded')
```
 and prevent the bindEventToChannel() in a different way.
 But callbacks passed to reconnect are mostly API calls and they are not dependent on `Pusher.subscribe()`. How will they be retriggered? 
 at this location
https://github.com/Expensify/Expensify.cash/blob/0603df60dd13385aacf7ff001815f7224b7875bb/src/libs/NetworkConnection.js#L72-L77
We again need a way to call all those callbacks. What are you trying to suggest by 

> Create another callback for the subscription_succeeded event when calling `Pusher.subscribe()`

Excuse me but I am still trying to understand your approach. 🙂

**Comment by marcaaron** [comment]
>We again need a way to call all those callbacks. What are you trying to suggest

Right, so before we had this function running 

https://github.com/Expensify/Expensify.cash/blob/96ede9ccc1d4af4694867e818eac993ec945e0a3/src/libs/NetworkConnection.js#L53

We now need to call the same function when a `subscription_suceeded` event occurs.

We can perhaps do it by passing a callback to `Pusher.subscribe()` e.g.

```js
Pusher.subscribe('eventName', eventCallback, isChunked, subscriptionSucceededCallback);
```

>Whatever callbacks are passed here are running on other events on channels which will fire automatically after reconnection

Can you try asking this another way? I'm not sure I understood. Thanks!

**Comment by parasharrajat** [comment]
> We now need to call the same function when a subscription_suceeded event occurs.

 I understand this part but `subscription_suceeded ` will be fired on each channel instead we just need to fire https://github.com/Expensify/Expensify.cash/blob/96ede9ccc1d4af4694867e818eac993ec945e0a3/src/libs/NetworkConnection.js#L53
 once each time `subscription_succeeded` event is fired so I don't this we should call this here in the `subscription_succeeded` callback. instead we can use the https://pusher.com/docs/channels/using_channels/events#binding-on-the-client
 this to bind to client for the  `subscription_succeeded` in the `NetworkConnection.js` file.
 
 Am I missing something?

**Comment by marcaaron** [comment]
Yes, I think you are maybe missing that my suggestion is to pass the function _when we subscribe_ and that sometimes the subscription succeeded callback will just be a no operation (and by default it should noop).

```js
Pusher.subscribe('event1', event1Callback, false, () => {});
Pusher.subscribe('event2', event2Callback, false, reconnect); // Only reconnect for this channel
```

Every channel will have its own subscription succeeded event that's true. But we only want the reconnection callbacks to trigger for a specific subscription. Which is the main subscription to the `private-user-accountID-*` channel.

**Comment by parasharrajat** [comment]
Oh. I see. So you mean we only call the reconnection on one channel for comments on the report and we don't need to call reconnectionCallbacks for other channels. Nice. 💯

So Now reconnectionCallacks will fire when

1. When we have connection success on the channel for comments on the report, after
2. User comes back online (which will be covered in 1).
3. Computer is back from sleep.

**Comment by marcaaron** [comment]
Yep, you got it.

**Comment by quinthar** [comment]
omg omg omg, so excited for this one

**Comment by quinthar** [comment]
It looks like it's working!!!  Thank you thank you!!

**Comment by parasharrajat** [comment]
@quinthar And the credit go to @marcaaron. 
🏆 🏆 🏆
