### ISSUE TITLE
[Consumer UI Refresh] Refactor Avatar component and relocate it from Sidebar bottom 

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1218]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**This is refactoring / feature improvement task and not a bug fix. All directions should be followed as written.**

- The avatar + indicator [here](https://github.com/Expensify/ReactNativeChat/blob/9f48370459159c7599be6f23661de737319739a0/src/pages/home/sidebar/SidebarBottom.js#L56-L63) should be refactored into a component called `AvatarWithIndicator`.
- It should take a prop of `isActive` and the styles should be moved from [here](https://github.com/Expensify/ReactNativeChat/blob/9f48370459159c7599be6f23661de737319739a0/src/pages/home/sidebar/SidebarBottom.js#L42-L45) into the new component.
- Only pass the `network && network.isOffline` value via the `isActive` prop
- Once we have done this the `AvatarWithIndicator` should be moved out of the `SidebarBottom` and relocated to the area here:
![Screen Shot 2021-01-11 at 9 59 53 AM](https://user-images.githubusercontent.com/32969087/104232096-e63f5280-53f3-11eb-9bc8-cc89ba53f69c.png)

- We must create a new `View` (flex-direction row, justify-content space-between) with the word `Chats` to the left and the `AvatarWithIndicator` to the right
- Here is a mockup of what it should look like:
![Screen Shot 2021-01-11 at 9 57 31 AM](https://user-images.githubusercontent.com/32969087/104231893-aa0bf200-53f3-11eb-9333-5f2ce0ddc594.png)

**Comment by parasharrajat** [comment]
I will glad to take upon this also submitted proposal. One question? What will happen to the old Search bar and Icon?

**Comment by marcaaron** [comment]
>What will happen to the old Search bar and Icon?

Awesome! Thanks for the question. The Search bar and icon will remain for now, but will be relocated in another issue to be posted soon. So the header and avatar will just sit below the search bar for now.

**Comment by parasharrajat** [comment]
Ok.

**Comment by parasharrajat** [comment]
![image](https://user-images.githubusercontent.com/24370807/104499761-946d1700-5603-11eb-8527-032d8647675f.png)
Hey @marcaaron, After removing the avatar from the bottom, should the remaining part be left as it is?

**Comment by marcaaron** [comment]
@parasharrajat yes, the app links and sign out button can remain.

**Comment by parasharrajat** [comment]
@marcaaron I have removed the User name from the Bottom as well. is it fine? also, I have moved the links horizontally center.

**Comment by marcaaron** [comment]
The user name can remain it will be removed soon, but not in this issue.

**Comment by parasharrajat** [comment]
Sure, I will add it back.

**Comment by parasharrajat** [comment]
@marcaaron  So I have found that there are a lot of UI bugs in Firefox and works well on chrome. I don't know why nobody has revealed it so far but I found these so far.
1. Chat scrolling behaviour has lag.
2. Search bar on the top go out of the sidebar.
4. Chat input box is absurd height.
These all issues were picked in the recent Upwork tasks but they were only fixed on chrome I presume.

see this SC. I took it from https://expensify.cash/#/r/68438375.
![image](https://user-images.githubusercontent.com/24370807/104522181-52080200-5624-11eb-995d-543ac5223a0e.png)

**Comment by marcaaron** [comment]
@parasharrajat Interesting. I don't think these have been reported yet, thanks! We don't need to worry about them in this issue, but we should create some new issues for them.

**Comment by marcaaron** [comment]
If you would like to create new issues for each problem we will take time to review them! If they are worth fixing then we can hire you again to fix them (if you are interested of course).

**Comment by parasharrajat** [comment]
Yes. I am very much interested. Thanks.

**Comment by marcaaron** [comment]
@parasharrajat feel free to create any issues for bugs you may find or suggestions you have for us. Testing cross-browser is a great idea as we've seen some unexpected styling in Firefox and Safari before.
