### ISSUE TITLE
[Consumer UI Refresh] Replace Icon w/ Left arrow icon make "sidebar" take up the full width of the screen

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
For this issue we must change the icon of the "hamburger" menu and do some light refactoring and styling.

- Remove all language in the code that refers to `hamburger` wherever `hamburger` is used we should replace it to `navigationMenu`
- Remove the hamburger menu icon itself from the [HeaderView](https://github.com/Expensify/ReactNativeChat/blob/9f48370459159c7599be6f23661de737319739a0/src/pages/home/HeaderView.js#L43-L52) and replace it with this chevron-left back style icon. Switch it to a `Pressable` instead of a `TouchableOpacity`.
- Make the "toggled open" state of the menu take up the entire width of the screen when viewing below the breakpoint.
- Remove the [`Pressable`](https://github.com/Expensify/Expensify.cash/blob/3f74c1f11e01a17039c539d4dcb0f81827d97e4e/src/pages/home/HomePage.js#L223-L230) that is listening for touches outside of the nav since the nav is now either pinned or full screen there is no need to listen for touches on an area that doesn’t exist. 
- Here is the asset we should use for the new icon: 
[arrow-left.svg.zip](https://github.com/Expensify/Expensify.cash/files/5799362/arrow-left.svg.zip)

**Note:** No proposal is required for this issue as we are asking contributors for exactly what we want.

# Screenshots

![Screen Shot 2021-01-11 at 9 36 33 AM](https://user-images.githubusercontent.com/32969087/104229799-cd816d80-53f0-11eb-9905-19772ac078ad.png)
![Screen Shot 2021-01-11 at 9 37 15 AM](https://user-images.githubusercontent.com/32969087/104230053-22bd7f00-53f1-11eb-9ce1-2d2e08eefe82.png)

https://www.upwork.com/job/React-Native-Update-Refactoring-Task-Expensify-1223_~01f16b24a0fd3311c1/

**Comment by kiritmodi2702** [comment]
- Remove the hamburger menu icon itself from the HeaderView and replace it with this chevron-left back style icon. Switch it to a Pressable instead of a TouchableOpacity. - **Done.**

<img width="448" alt="Screenshot 2021-01-13 at 11 40 15 PM" src="https://user-images.githubusercontent.com/10494663/104492609-ee68df00-55f9-11eb-9124-f7cd01ac3140.png">

**Comment by shawnborton** [comment]
The fill color of the icon should be `themeColors.icon`

**Comment by kiritmodi2702** [comment]
> The fill color of the icon should be `themeColors.icon`
Done

**Comment by kiritmodi2702** [comment]
- Remove the Pressable that is listening for touches outside of the nav since the nav is now either pinned or full screen there is no need to listen for touches on an area that doesn’t exist.  - **Done**



> The fill color of the icon should be `themeColors.icon`
> Done

![Uploading Screenshot 2021-01-14 at 12.20.01 AM.png…]()

**Comment by kiritmodi2702** [comment]
- Remove the Pressable that is listening for touches outside of the nav since the nav is now either pinned or full screen there is no need to listen for touches on an area that doesn’t exist.  - **Done**


![Simulator Screen Shot - iPhone 11 - 2021-01-14 at 00 20 57](https://user-images.githubusercontent.com/10494663/104495980-66390880-55fe-11eb-9bba-f0b96b6d08d7.png)

**Comment by kiritmodi2702** [comment]
hamburger word is totally replaced with navigationMenu.

- Remove all language in the code that refers to hamburger wherever hamburger is used we should replace it to navigationMenu

![Uploading Screenshot 2021-01-14 at 12.54.47 AM.png…]()

**Comment by kiritmodi2702** [comment]
Hi @trjExpensify Can you please let me know, What's should branch name to upload my work to create pull request ?

**Comment by marcaaron** [comment]
@kiritmodi2702 Feel free to name the branch whatever you want.
