### ISSUE TITLE
[Consumer UI Refresh] Create the Settings Page/Screen

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

This task is to implement a new UI feature and we are providing very clear instructions for how to do it. Instructions should be followed exactly and **no proposal is necessary**. 

- Create a new page called `SettingsPage.js` in the `/pages` directory
- Add a new route for `/settings` [here](https://github.com/Expensify/Expensify.cash/blob/3f74c1f11e01a17039c539d4dcb0f81827d97e4e/src/ROUTES.js#L5-L12) 
- Add this route to the `HomePage` [here](https://github.com/Expensify/Expensify.cash/blob/3f74c1f11e01a17039c539d4dcb0f81827d97e4e/src/pages/home/HomePage.js#L209) so the sidebar elements will load when we redirect or navigate to `/settings`. **Note:** the Settings page should sit above the `Main` view [here](https://github.com/Expensify/Expensify.cash/blob/9f48370459159c7599be6f23661de737319739a0/src/pages/home/HomePage.js#L273).
- Make [the `Avatar` in the `SidebarBottom`](https://github.com/Expensify/ReactNativeChat/blob/9f48370459159c7599be6f23661de737319739a0/src/pages/home/sidebar/SidebarBottom.js#L56-L62) touchable (use a `Pressable`) and give it an `onPress` method.
- When pressed should call `redirect(ROUTE.SETTINGS)`
- The app version code should be displayed at the bottom of the page, this can be imported from package.json: `import {version} from '../../../../package.json';`

The new page/screen should look like this:

![Screen Shot 2021-01-11 at 10 18 27 AM](https://user-images.githubusercontent.com/32969087/104235845-a54a3c80-53f9-11eb-8628-a06bc03eda40.png)

Much of the logic for building this page can be found in the `SidebarBottom` component [here](https://github.com/Expensify/ReactNativeChat/blob/9f48370459159c7599be6f23661de737319739a0/src/pages/home/sidebar/SidebarBottom.js#L55-L74).

- Note that we do **not** need to display the "app links" (`Web, iOS, Android`)
- Note that the "Sign Out" link is now a button
- Make sure that we are displaying both the "display name" and user email
- It should have a `HeaderWithCloseButton` with a title of "Settings"
- The `onCloseButtonPress` callback should redirect back to the [`currentlyViewedReportID`](https://github.com/Expensify/ReactNativeChat/blob/9f48370459159c7599be6f23661de737319739a0/src/ONYXKEYS.js#L18-L20) e.g. `redirect(ROUTES.getReportRoute(currentlyViewedReportID));`

**Upwork:** https://www.upwork.com/jobs/~01f50f69729f6c8ae8

**Comment by rafidaky** [comment]
Hello I would like to pick up this issue.

**Comment by Julesssss** [comment]
Hi @rafidaky, just wanted to let you know I'm adding a small missing task to the main issue description:

> - Display the current app version at the bottom of the page, this can be found with the following: `import {version} from '../../../../package.json';`

**Comment by marcaaron** [comment]
@rafidaky please let us know the progress here.
