### ISSUE TITLE
[Consumer UI Refresh] Hide the Search Input and Display when Touching Magnifying Glass

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1230]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Deliverables:**
- Remove the `ChatSwitcherView` [here](https://github.com/Expensify/ReactNativeChat/blob/3f74c1f11e01a17039c539d4dcb0f81827d97e4e/src/pages/home/sidebar/SidebarLinks.js#L96-L99) and replace it with a touchable magnifying glass icon as the `ChatSwitcherView` must now be conditionally rendered.
- In the `onPress` callback for the icon conditionally render the `ChatSwitcher` view
- Clean up the code so that the [`isLogoVisible` and `isClearButtonVisible`](https://github.com/Expensify/ReactNativeChat/blob/3f74c1f11e01a17039c539d4dcb0f81827d97e4e/src/pages/home/sidebar/ChatSwitcherSearchForm.js#L23-L28) props are removed from the `ChatSwitcherSearchForm` component as the logo will never be visible and the clear button will always be visible from now on.
- Remove the logo entirely from [here](https://github.com/Expensify/ReactNativeChat/blob/3f74c1f11e01a17039c539d4dcb0f81827d97e4e/src/pages/home/sidebar/ChatSwitcherSearchForm.js#L60-L68)
- Make the clear button always visible by removing this condition [here](https://github.com/Expensify/ReactNativeChat/blob/3f74c1f11e01a17039c539d4dcb0f81827d97e4e/src/pages/home/sidebar/ChatSwitcherSearchForm.js#L150-L151)

**Magnifying Glass Asset:** 
[magnifyingglass.svg.zip](https://github.com/Expensify/Expensify.cash/files/5805815/magnifyingglass.svg.zip)

**Screenshots:**

Here is the current view:

<img width="301" alt="Screen Shot 2021-01-12 at 3 37 03 PM" src="https://user-images.githubusercontent.com/32969087/104395454-db1c1d80-54ec-11eb-82eb-de4e1e1cff60.png">

Here is how it should look after (**Note:** Our design team may have final notes for you):

![Search bar 1](https://user-images.githubusercontent.com/32969087/104395505-f1c27480-54ec-11eb-9923-7010fcec08e0.png)
<img width="299" alt="Screen Shot 2021-01-12 at 3 41 13 PM" src="https://user-images.githubusercontent.com/32969087/104395522-f8e98280-54ec-11eb-9ef5-f7671f3bf369.png">

**Note:** If this issue is not completed before the [Avatar and header are moved above the chat list](https://github.com/Expensify/Expensify.cash/issues/1218) then the magnifying glass should appear to the left of the avatar. The final view will look like this:

![Screen Shot 2021-01-12 at 3 44 18 PM](https://user-images.githubusercontent.com/32969087/104395585-1a4a6e80-54ed-11eb-980e-890ddfc8a64c.png)
____

Please leave any questions on this issue after accepting our offer.

**Upwork Listing:** https://www.upwork.com/jobs/~01d448e47c9642e502

**Comment by UpworkBartkoski** [comment]
Questions:
1. Another solution to resolve this issue, make a Touchable magnifying glass icon inside `ChatSwitcherView` instead of  `SidebarLinks`?
2. When clicking the clear button, should it show a magnifying glass icon again?
3. magnifyingglass.svg.zip doesn't look work.

**Comment by UpworkBartkoski** [comment]
I am working on this.

**Comment by chiragsalian** [comment]
We can wait on marc if you want another opinion but here are my thoughts to answer your questions,
1. No so your solution won't work as well as marcs solution because marc wants us to conditionally render `ChatSwitcherView`. By rendering `ChatSwitcherView` only when the magnifying glass is clicked it helps keep the app lighter.
2. Yes
3. Seems to work fine for me. Did you download and then unzip it to get the svg file?

**Comment by chiragsalian** [comment]
Sent the svg file over slack as well to you ([here](https://expensify.slack.com/archives/C01GTK53T8Q/p1610654871035200?thread_ts=1610652801.034500&cid=C01GTK53T8Q)).

**Comment by marcaaron** [comment]
Yep, agree with everything @chiragsalian is saying here! And another point which is that we will eventually be removing the old `ChatSwitcherView` completely. The magnifying glass icon should remain. So we really do not want to put the magnifying glass inside the view that we will remove eventually.

**Comment by chiragsalian** [comment]
@Expensify/design can we get new mockups for how the UI will look with search box for the new UI?
![image](https://user-images.githubusercontent.com/14356145/104643607-80580280-5661-11eb-936f-a6e191efe315.png)

**Comment by UpworkBartkoski** [comment]
OK

**Comment by shawnborton** [comment]
I think you can just follow the original comment - tapping the search icon will navigate to the page with the search input + results that looks like this:
![image](https://user-images.githubusercontent.com/2319350/104643854-e0e73f80-5661-11eb-83bd-17f0d0d5d21d.png)

**Comment by UpworkBartkoski** [comment]
Magnifying glass svg works on web but not on Android

**Comment by chiragsalian** [comment]
whats the issue on android?

**Comment by UpworkBartkoski** [comment]
not showing.

**Comment by UpworkBartkoski** [comment]
![Screen Shot 2021-01-14 at 2 33 33 PM](https://user-images.githubusercontent.com/74012504/104646063-9243a080-5675-11eb-82a5-efa59ea3897c.png)
![Uploading Screen Shot 2021-01-14 at 2.34.29 PM.png…]()

**Comment by marcaaron** [comment]
Code example?

**Comment by marcaaron** [comment]
It needs to be imported as a component IIRC e.g.

https://github.com/Expensify/Expensify.cash/blob/076e10f4e0b6d9fec5ba5a2d19090dc6304a1691/src/components/Expensicons/PinIcon.js#L1-L28

**Comment by UpworkBartkoski** [comment]
Yes, I already did it.
Will check again.

**Comment by UpworkBartkoski** [comment]
Done
