### ISSUE TITLE
[Consumer UI Refresh] Add CreateMenu. Bottom Drawer Modal Pattern + Hook up FAB

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

For this issue we will create a new type of [Modal](https://github.com/Expensify/Expensify.cash/blob/master/src/components/Modal.js#L22-L25) called `bottomDocked` and then display a menu `CreateMenu` component with two options "New Group" and "New Chat". For now, touching both of these options will open the `ChatSwitcher` which we can do by calling [`ChatSwitcher.show()`](https://github.com/Expensify/Expensify.cash/blob/ca2fa88a5789b82463d35eddc3d57f70a7286868/src/libs/actions/ChatSwitcher.js#L14-L16) and closing the modal after a selection is made.

We are using the [`react-native-modal` library](https://github.com/react-native-modal/react-native-modal) which has good documentation.

1. Create a new component called `CreateMenu` which will render a `bottomDrawer` type `Modal`. It should look like this:
![Screen Shot 2021-01-13 at 3 19 15 PM](https://user-images.githubusercontent.com/32969087/104531692-d0c45700-55b2-11eb-815b-4a33225fa60a.png)
2. `CreateMenu` should have the following props:
	1. `isVisible` - `Boolean` Used to display or hide the menu
	2. `menuItemData` - array of objects with the following additional props:
		1. `icon` - icon component to show in the option
		2. `text` - text to display to the right of the icon
		3. `onPress` - function fired when menu option selected
3. The `CreateMenu` should render the `bottomDrawer` `Modal` and then render the rows for each option passed in the `menuItemData` array.
4. Remove the ability to hide the `FAB.js` `isHidden`
5. When the FAB is active we will set the `isVisible` property of the menu to `true` and when it is not active we will hide the modal.
6. When the menu is closed (either via the `x` or by making a selection) the FAB should be set back to it's original state.
7. All menu selections should call `ChatSwitcher.show()`.

So, after one of the selections in the menu is made we should see this view open:
<img width="301" alt="Screen Shot 2021-01-13 at 3 22 29 PM" src="https://user-images.githubusercontent.com/32969087/104531914-2f89d080-55b3-11eb-939c-d8748a1f3259.png">

**The chat bubble and person icon assets to use are here:**
[MenuAssets (1).zip](https://github.com/Expensify/Expensify.cash/files/5815871/MenuAssets.1.zip)

**Comment by parasharrajat** [comment]
Hey guys, How can I apply? I don't see any upwork link. Anyway, I would like to work on this.

**Comment by lucas-neuhaus-dev** [comment]
I have a question, the images do now explicit it very well:

What happens to the FAB when the modal is open? Looking at the image I believe it would just get hidden under the modal, and we actually would not have an `X` to close it.

Maybe make it go up with the modal (I believe we would need to do something tricky so it does not get obfuscated by the modal).
Maybe leave it hidden and simply close the modal with a click anywhere outside of it.

**Comment by marcaaron** [comment]
@parasharrajat Thanks, we have assigned to Lucas already, but will have some more project work soon for you!

>What happens to the FAB when the modal is open?

Correct. It should just be hidden by the modal in this case. There is a future plan for the alternate state of the FAB. But no need to worry about this for now.

>Maybe make it go up with the modal (I believe we would need to do something tricky so it does not get obfuscated by the modal).

Interesting idea, but we have something else in mind :)

>Maybe leave it hidden and simply close the modal with a click anywhere outside of it.

Exactly! Clicking outside the modal should close it. Selecting one of the options will also close it.

**Comment by lucas-neuhaus-dev** [comment]
Alright, after a lot of looking and testing things around, I have a couple of more questions and an early proposal.

## Proposal
1. Add the svg assets to `assets/images` and create each icon component following the pattern in `src/components/Expenseicons`;
2. Add a new MODAL_TYPE in `src/CONST.js` called `BOTTOM_DOCKED` and use it to create a new modal style in `src/styles/getModalStyles.js`;
3. Create the `CreateMenu` component. It renders the custom `Modal` component that already exists on the project, that uses the new modal style created, and renders the menu mapping throw the `menuItemData` array prop;
4. Place the new component on the `HomePage`, it takes the `isVisible` prop that corresponds to the `isFloatingAcionButtonActive` state, and the `onClose` prop that takes the `toggleFab()` function. We might want to change this names maybe, but that what it corresponds to right now. It also takes the `menuItemData`. I am not sure where to define it yet (accept suggestions);
5. Remove the `isVisible` prop from the floating action button.


## Questions
1. On large screens, I believe the View inside the modal should extend just the sidebar width, right? (gif at the end). I didn't have time to look much, but if this is it do I copy the hard-coded value 300 I found in the `animationTranslateX` on the HomePage, or is there a better place to get this value? I can also take a better look at the sidebar components to find the value;
2. From the last commit I fetched upstream this afternoon, the mobile sidebar width was still not corresponding to the whole screen width, but I know I read in one of the issues it was going to be implemented (I'm pretty sure). If my assumption in 1. is correct, can I make the modal component width 100% in small screens, and 300 on others already?
3. In the next gif, when I press the modal test button, I did call the `ChatSwitcher.show()`, and something weird happened (as can be seen in the gif). I will take a more in-depth look to debug it, but maybe someone can already tell me what is happening. No problem if it not known, I'll figure it out.

![demonstration](https://i.ibb.co/Z1mWj0w/modal.gif)

**Comment by marcaaron** [comment]
Proposal sounds perfect! 

And yes, I agree with you about the name change. Perhaps instead of having a state value with `isFloatingActionButtonActive` we can change this to `isCreateMenuVisible` and then pass this to both the modal and the fab?

As for the questions....

>On large screens, I believe the View inside the modal should extend just the sidebar width, right? (gif at the end). I didn't have time to look much, but if this is it do I copy the hard-coded value 300 I found in the animationTranslateX on the HomePage, or is there a better place to get this value? I can also take a better look at the sidebar components to find the value;

For now, it's ok to do exactly as you have there. Our plan for this is to have another style of modal that is more like a popover for the wide screen views. In that case, the menu will be closed by pressing on the FAB and the menu will sit above like so:

![Screen Shot 2021-01-14 at 12 32 52 PM](https://user-images.githubusercontent.com/32969087/104657242-b480f280-5664-11eb-9358-53d8214fc809.png)

>From the last commit I fetched upstream this afternoon, the mobile sidebar width was still not corresponding to the whole screen width, but I know I read in one of the issues it was going to be implemented (I'm pretty sure). If my assumption in 1. is correct, can I make the modal component width 100% in small screens, and 300 on others already?

Yep you are correct and that sounds like a good plan. We can do 300 for the wide view and 100% for the small view.

>In the next gif, when I press the modal test button, I did call the ChatSwitcher.show(), and something weird happened (as can be seen in the gif). I will take a more in-depth look to debug it, but maybe someone can already tell me what is happening. No problem if it is not known, I'll figure it out.

Ah hmm I see. It seems like the "ChatSwitcher" is not showing. I can help debug when you create a PR if you haven't solved it yet.
