### ISSUE TITLE
[Consumer UI Refresh] Create the Popover style Modal and switch to it for wide screens

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1267]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Now that the `CreateMenu` exists we need to display an alternate modal style depending on if we have a wide screen width. Here's what it should look like. 

![Screen Shot 2021-01-19 at 7 34 07 AM](https://user-images.githubusercontent.com/32969087/105072040-73545e00-5a29-11eb-9aa8-865b586475ee.png)

**Deliverables:**
1. Create a new style of modal called a `popover`
2. It should not have a semi-transparent back drop like other modals
3. It should still close when tap outside and also close when tapping the `x`
4. It should be aligned with the FAB
5. It should only be visible when viewing past the responsive breakpoint

**Comment by lucas-neuhaus-dev** [comment]
@marcaaron 
Just to be sure, the response when clicking the FAB on small screens (`windowDimensions.width < variables.mobileResponsiveWidthBreakpoint`) should not change?

**Comment by marcaaron** [comment]
Correct. In that case, we will use the `bottom_docked` style menu like we are now.

**Comment by lucas-neuhaus-dev** [comment]
### Proposal

1. Add a new MODAL_TYPE in `src/CONST.js` called `POPOVER` and use it to create a new modal style in `src/styles/getModalStyles.js`;
2. Add a new prop on the `Modal` component called `isPopover`. It defaults to false and can be set in `getModalStyles`. Use this prop to conditionally render the backdrop;
3. I am still testing out the animations, but I want to end up with an animation similar to [the material UI](https://material-ui.com/components/menus/#menulist-composition) popover menu;
4. Conditionally renders this modal style when the screen is **not small**.

### Aditional proposal

The proposal above would be in line with the deliverable, but a modal might not be the best solution for this. A normal View with a click away listener might provide a better UX.

For example, if the menu opens a modal, the user no longer has a pointer cursor for the fab, links or just pointers at all. And has to click twice to perform another action (close modal -> perform action).

The material UI link I sent before ([this link](https://material-ui.com/components/menus/#menulist-composition)) has a nice example of this. The `Toggle Menu Grow` button on that page (MenuList composition section) opens what acts like a div with the a click away listener, and the `Open Menu` button (Customized menus section) acts like a modal. I personally greatly prefer the first.

**Comment by marcaaron** [comment]
>Add a new prop on the Modal component called isPopover. It defaults to false and can be set in getModalStyles. Use this prop to conditionally render the backdrop;

I think we can maybe get even more generic here and have this be `showBackdrop` in case other things would hide it?

>I am still testing out the animations, but I want to end up with an animation similar to the material UI popover menu;

Sounds good, I think we can even just have it fade into a fixed position for now. But maybe @shawnborton has thoughts on this and we should get some ideas from him.

>A normal View with a click away listener might provide a better UX. For example, if the menu opens a modal, the user no longer has a pointer cursor for the fab, links or just pointers at all. And has to click twice to perform another action (close modal -> perform action). And when there is no backdrop it doesn't feel natural (for me) to have a different behavior.

That's a good point and I agree with you. I guess my counter question would be... 

Is there any way to:
1. Not use a backdrop for the modal (`hasBackdrop: false` maybe can be used)
2. Add a click away handler so we can close the modal yet not prevent additional actions

I'm not sure if that would be possible, but it might be worth trying.

**Comment by lucas-neuhaus-dev** [comment]
> I think we can maybe get even more generic here and have this be showBackdrop in case other things would hide it?

Make sense!

> Sounds good, I think we can even just have it fade into a fixed position for now

You mean from the bottom (or left) of the screen? (not from the top of the button). It does make it easier.

> Not use a backdrop for the modal (hasBackdrop: false maybe can be used)

This was my first idea when reading the `react-native-modal` API. But for some reason, I can't seem to get this prop to work on web and desktop for anything (works on android). I will to do some more debugging, see if I can find the reason.

**Comment by marcaaron** [comment]
>You mean from the bottom (or left) of the screen? (not from the top of the button). It does make it easier.

Yeah I was thinking it would not necessarily have to transform from a certain origin just simply fade into a fixed position.

**Comment by lucas-neuhaus-dev** [comment]
I really can't seem to get this modal to behave as I want on web and desktop.
Just to summarize, the behavior I want is for the modal to not have a backdrop, so we don't have a `div` covering the whole screen and don't lose our cursor functionality (for other actions) when the CreateMenu is opened.

I tried:
- Setting `hasBackdrop` to false (works on mobile);
- Using the `customBackdrop` props, passing down an empty `<View />` (works on mobile);
- Setting `coverScreen={false}` with `backdropOpacity={0}` (also doesn't work as intended on mobile)

I also tried to find existing issues of this on the [react-native-modal github page](https://github.com/react-native-modal/react-native-modal), but could not find anything.

If someone could please test at least the two first things I tried, to make sure it is not just me, it would be greatly appreciated.
The file is located at `scr/components/Modal.js`.

If someone else tests it and it really doesn't work, I see two options:

1. Use the modal setting `backdropOpacity={0}`, and not really care about the whole cursor problem;
2. Create a new component for this, don't use the modal.

**Comment by shawnborton** [comment]
Maybe the cursor thing isn’t a big deal, in that clicking outside of the
menu should close the menu and not interact with background UI. Thoughts on
that?

**Comment by lucas-neuhaus-dev** [comment]
Yeah, it is a very minor thing. But I was hoping to find an easy solution.

I am going to commit a PR soon just using `backdropOpacity={0}`. If after testing out we realize we can change it so something else, we can keep the discussion there.

**Comment by marcaaron** [comment]
I've tried for a bit to get the `hasBackdrop={false}` prop to work and can confirm that it is not working on web. 

I can't see any reason why this shouldn't work and see that you've opened an issue [here](https://github.com/react-native-modal/react-native-modal/issues/517). So, probably the best thing to do for now is proceed with the modal opacity 0 and hopefully we can resolve this in the future to improve the UX.

Thanks!
