### ISSUE TITLE
[Improvement] Improve E.cash search for group chats

### ISSUE THREAD

**Issue by NicMendonca** [Expensify/Expensify.cash#1283]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  All

# Problem
Search is frequently how I find a given chat. There are two main problems I currently have with it: 
1. It doesn't work well for group chats. For example I can't type in `Lauren Andrew` in order to find my group chat with Lauren and Andrew. 
2. It looks for the whole string that I type in to be a match, rather than looking at whether there is a matching user for each word. For example, when I search `Alex Revelli` nothing comes up because she she is listed as `Alexandra Revelli`. I would think that she would still show up because the second word in my search, `Revelli` is a match to her user. 
 
# Why is this important?
Easy search makes Expensify.cash an easier, lighter experience. 

# Solution
Update search to work as follows: 

- split search string on spaces
- return all exact and partial matches to each string
- order results by most recent message (meaning the most recent message posted in the chat)

Upwork Job link: https://www.upwork.com/jobs/~01ccd27d2ef43f2d7f

**Comment by tugbadogan** [comment]
Hi @NicMendonca ,
I would like to work on this issue. Here is my proposal:

I found that search results are generated in `ChatSwitcherView.updateSearch()` function. I’m planning to modify the following for loop.
https://github.com/Expensify/Expensify.cash/blob/c0069cf6e2df94ba7c3a2c242cf9e6a9c82ddd30/src/pages/home/sidebar/ChatSwitcherView.js#L424-L451

I’m going to split search string on spaces and create an array of words.
`isMatch` condition should be changed such that our regex matches should work for all words from search string.
https://github.com/Expensify/Expensify.cash/blob/c0069cf6e2df94ba7c3a2c242cf9e6a9c82ddd30/src/pages/home/sidebar/ChatSwitcherView.js#L429

I have a question for ordering results. I see there is an existing ranking that ranks exact matches higher. Do you want me to preserve this ranking or should we order all matches by most recent message time? To implement this, I’m going to sort all search options  by most recent message time that is not available in this function. I need to pass that value somehow.

**Comment by NicMendonca** [comment]
@tugbadogan Thanks! Please apply for the job directly [through Upwork](https://www.upwork.com/jobs/~01ccd27d2ef43f2d7f). 

Also a note, we're waiting for other UI changes before we can hire for this job.

**Comment by tugbadogan** [comment]
Hi @NicMendonca,

I've already apply through Upwork. My Upwork name is Fadime Tugba Oge.

> Also a note, we're waiting for other UI changes before we can hire for this job.

No problem, thanks for letting me know. I'm happy to work on this issue later.

**Comment by NicMendonca** [comment]
@tugbadogan as mentioned last week we did make some UI changes so you might want to give your initial proposal a second look. 

Thanks!

**Comment by tugbadogan** [comment]
Hi @NicMendonca, I created a pull request on top of the most recent UI changes. I fixed this issue and removed redundant regex patterns from the code.
