### ISSUE TITLE
Design clean up items for FAB and create menu

### ISSUE THREAD

**Issue by shawnborton** [Expensify/Expensify.cash#1296]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

There are a few design items we'd like to clean up with the FAB and Create Menu. 

**FAB - All Platforms**
The FAB itself appears to be too small. Can we make the FAB itself use an area of 52x52? 
![image](https://user-images.githubusercontent.com/2319350/105275610-09aa9000-5ba0-11eb-970a-896c18c81d4d.png)

The icon inside of the FAB can be 20x20. 

For iOS, also be sure that the <SafeAreaPadding> is below the FAB so that it is not too close to the home indicator. 
![image](https://user-images.githubusercontent.com/2319350/105275597-031c1880-5ba0-11eb-9ec4-c969a703ca33.png)

**Create Menu - iOS Only**
The bottom of the Create Menu should have the <SafeAreaPadding> inserted into it so that it respects the home indicator. 
![image](https://user-images.githubusercontent.com/2319350/105275532-db2cb500-5b9f-11eb-9723-b60d9f80b443.png)

cc @marcaaron @lucas-neuhaus-dev

**Comment by lucas-neuhaus-dev** [comment]
Hi. Sorry I have not been testing my code on iPhones and missing points like this. I have an old iPhone but no Mac, and couldn't really find a way to test out a React Native project that does not use Expo.

I am heavily considering renting a cloud service like [macincloud](https://www.macincloud.com/) to make sure I always test at least on an iPhone emulator.

I am asking about it in a couple of dev communities. If it happens to be the best solution I plan on doing it today.

**Comment by lucas-neuhaus-dev** [comment]
@shawnborton 

> Can we make the FAB itself use an area of 52x52?

On the `src/styles/variables.js` file, there is a constant called `componentSizeLarge` with a value of `50`. What do you think is better?
- Use this constant;
- Change `componentSizeLarge` to `52` and use it _(the other component that is using its value is the `ExpensifyCashLogoIcon`)_;
- Create a new constant;
- Hard code the value.

I like the idea of changing the constant value to 52. I also tend to use multiples of 4 for sizes.

**Comment by shawnborton** [comment]
Let’s change the constant to 52. Thanks!
