### ISSUE TITLE
Add meta tags to Expensify.cash html for link previews

### ISSUE THREAD

**Issue by marklouisdeshaun** [Expensify/Expensify.cash#1302]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
View the job on Upwork [here](https://www.upwork.com/jobs/~01a827f3a0a815553e)

**Platform - version:**  
iOS
Android

**Action Performed (reproducible steps):**
1. Copy link to https://expensify.cash
2. Send the link via:
a. iPhone iMessage 
b. iPhone apps: WhatsApp, Facebook, Slack, Twitter
c. Android Text Message
d. Android apps: WhatsApp, Facebook, Slack, Twitter
3. Take note of the link preview that is generated (or not generated)

**Desired Result:**
Add meta tags to Expensify.cash HTML to generate a different selected preview and description (image file and description copy will be provided).

File: 
[expensifycash_metapreviewimage.png.zip](https://github.com/Expensify/Expensify.cash/files/5852544/expensifycash_metapreviewimage.png.zip)

**Actual Result:**
Sharing a link to expensify.cash either doesn't generate a preview (e.g., WhatsApp) or generates a very basic preview (e.g., iMessage)

**Notes/Photos/Videos:** 
Current link preview on iOS/iMessage
![image](https://user-images.githubusercontent.com/53453740/105414717-72742580-5bfd-11eb-8818-511b62cdb55d.png)

Current link preview on iOS/WhatsApp
![image](https://user-images.githubusercontent.com/53453740/105415183-0f36c300-5bfe-11eb-9110-a98b28374406.png)

Desired link preview (image):
![image](https://user-images.githubusercontent.com/53453740/105423178-a86bd680-5c0a-11eb-8c27-8ab4f5fa0ec1.png)

Desired link preview (copy):
> Chat and payments are now the same thing. Launching Summer 2021, join the waitlist to be first in line!

**Comment by parasharrajat** [comment]
@marklouisdeshaun Thanks. I will work on this.
So I have few questions:
1. Do you want it to look like  Expensify.com
![image](https://user-images.githubusercontent.com/24370807/105554140-c0d41200-5d2c-11eb-983c-5d6f191144e1.png)

But with 
> Chat and payments are now the same thing. Launching Summer 2021, join the waitlist to be first in line!
and the new Image.

**Comment by marklouisdeshaun** [comment]
@parasharrajat I'm just asking for confirmation from the team now and will let you know as soon as I can!

**Comment by parasharrajat** [comment]
@marklouisdeshaun Some matching example will be really helpful to Identify the exact requirement.

**Comment by marklouisdeshaun** [comment]
@parasharrajat - the team confirmed it should look like the Expensify.org preview option (the bottom one in the screenshot), and yes with the new copy and the Expensify.cash logo. 

Just let me know if that's not clear enough or if you have other questions.

**Comment by parasharrajat** [comment]
Ok. Thanks. It's clear now.

**Comment by marklouisdeshaun** [comment]
Hi @parasharrajat! We require a description of the proposed solution before reviewing the PR. Can you provide a brief description of the solution you plan to implement? Thanks!

**Comment by parasharrajat** [comment]
@marklouisdeshaun Sory about that. But I thought it mentioned to add meta links.

Proposed Solution:
1. I have added meta links into the `web/index.html` file which will help providers to fetch the correct link preview while using out links.
I have added only the required tags so far
 ```
 <meta property="og:site_name" content="Expensify.cash">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://expensify.cash">
    <meta property="og:title" content="Chat and payments are now the same thing. Launching Summer 2021, join the waitlist to be first in line!">
    <meta property="og:image" content="https://expensify.cash/icon-square@4x.png">
    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://expensify.cash">
    <meta property="twitter:title" content="Chat and payments are now the same thing. Launching Summer 2021, join the waitlist to be first in line!">
    <meta property="twitter:image" content="https://expensify.cash/icon-square@4x.png">
```

Here `og:title` and `og:image` is the needed one for most of the providers but to achieve the same result on Twitter I have added Twitter tags as well.

**Comment by shawnborton** [comment]
The solution sounds good to me.

**Comment by shawnborton** [comment]
Apologies, I left a comment in your PR but actually for the proposed solution, it looks like we can remove some of the Twitter-specific tags you are using (notably the `twitter:title` tag) as Twitter works well with the standard Open Graph (og) protocol. [Take a look here (bottom of page)](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started), this would be an ideal set of tags:

```
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@nytimesbits" />
<meta name="twitter:creator" content="@nickbilton" />
<meta property="og:url" content="http://bits.blogs.nytimes.com/2011/12/08/a-twitter-for-my-sister/" />
<meta property="og:title" content="A Twitter for My Sister" />
<meta property="og:description" content="In the early days, Twitter grew so quickly that it was almost impossible to add new features because engineers spent their time trying to keep the rocket ship from stalling." />
<meta property="og:image" content="http://graphics8.nytimes.com/images/2011/12/08/technology/bits-newtwitter/bits-newtwitter-tmagArticle.jpg" />
```

**Comment by parasharrajat** [comment]
Sure.
