### ISSUE TITLE
[Consumer UI Refresh] Spruce up the New Group page

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1336]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

We implemented a new page at `#/new/group` that is not yet accessible by clicking around in the UI. In this view, multiple users can be selected and a chat can be started with them. 

**Deliverables:**
- We must update the UI for showing the "selected" state by using the icon asset provided
- Make various design adjustments based on feedback of our design team 
- The page must also be moved into a modal that is type `right_docked` (similar to the `Settings` view)

![new group](https://user-images.githubusercontent.com/32969087/106173284-d768d780-6137-11eb-9952-e0cf6c3dfca3.png)

**Comment by marcaaron** [comment]
cc @shawnborton to provide us with the checkmark asset required to complete this issue

**Comment by shawnborton** [comment]
Here is the asset: [checkmark.svg.zip](https://github.com/Expensify/Expensify.cash/files/5889715/checkmark.svg.zip)

It should be shown at a size of 20x20.

**Comment by lucas-neuhaus-dev** [comment]
### Proposal

- Rename the `SettingsModal` component to `RightDockedModal`;
- Add 2 new required props to it: `title` and `Page`, which take a `string` and a `function`, respectively;
- Change the existing `SettingsModal` on the `HomePage` to this new modal, taking the additional `title: "Settings` and `Page={SettingsPage}` props;
- Add a new `<RightDockedModal />` right under it, with matching props for it;
- Create new generic styles for the modal, that could easily be used on additional pages like `Split Bill` (I'm looking at the Figma designs).

**Comment by lucas-neuhaus-dev** [comment]
Also, I would like to suggest something @shawnborton 

On the `src/pages/home/sidebar/ChatLinkRow.js` file, transform the top component into a `Pressable` _(and the existing `TouchableOpacity` into a `View`)_, so we can get some nice hover effect for the contacts. 
I am still seeing at what looks good, but I want to end up with the style seen on the image below (maintaining the rest of the layout as it is).

_Obs: The cursor is pointer, just my screenshot doesn't get that_
![contacts](https://i.ibb.co/hDbbRQz/example.png)

**Comment by shawnborton** [comment]
I think that sounds like a great idea. I believe you can at least use the arrow key to go through the list at the moment (which will toggle the BG style) but I love the idea of having a full row hover style.

**Comment by lucas-neuhaus-dev** [comment]
Oh, good thing you mentioned that, I actually was not aware of the arrow key selection, and did not see this effect.

All right I will make sure both work.

**Comment by marcaaron** [comment]
Thanks @lucas-neuhaus-dev. Plan sounds 👍  to me.
