### ISSUE TITLE
[Consumer UI Refresh] Implement the New Chat view

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

We must take the existing "New Group" page and create a "New Chat" page which is a simplified version of the "New Group" page. There is a method that should already calculate the correct options to display called `OptionsListUtils.getNewChatOptions()`. 

Here are the following differences:

- No headers will be shown for the sections
- No recent reports will be included
- Selecting multiple options is not supported and tapping on a user option will simply navigate to the chat
- Users can still be invited via this flow

**Deliverables:**
- Create the "New Chat" page following the example of the "New Group" page and refactoring where necessary to optimize shared logic
- Hook up the "New Group" and "New Chat" pages to the `CreateMenu` so that when the FAB options are clicked these pages will appear

![New Chat desktop](https://user-images.githubusercontent.com/32969087/106173356-ee0f2e80-6137-11eb-93b4-dc7c3b2f8846.png)
![New Chat](https://user-images.githubusercontent.com/32969087/106173415-fc5d4a80-6137-11eb-9c01-a7557e02ecbe.png)

**Comment by lucas-neuhaus-dev** [comment]
### Proposal

1. Create a new route -> `NEW_CHAT: '/new/chat/`;
2. Create a new `NewChatPage` file, that has much of the same as `NewGroupPage`, but gets the options using `getNewChatOptions` removes unnecessary code, and creates a new chat using `fetchOrCreateChatReport` when an option is pressed;
3. Hook this up in the `HomePage`.

The PR should be up pretty soon.
