### ISSUE TITLE
[Consumer UI Refresh] Implement the Search view

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

We need to replace the `ChatSwitcherView` entirely with a "Search page" which is an even simpler version of the "New Chat" page. There is a method that should already calculate the correct options to display called `OptionsListUtils.getSearchOptions()`. The difference here between the "New Chat" page will be that:

- No headers will be shown
- No personalDetails will be shown
- No headers will be shown for the sections
- Users can **not** be invited via this flow
- Chats with multiple participants should be shown

**Deliverables:**
- Implement the Search page and replace the `ChatSwitcherView` in the `Sidebar`.
- The `ChatSwitcherView` and anything related to it (that is no longer used) must be deleted from the codebase.

![Search Desktop](https://user-images.githubusercontent.com/32969087/106173482-0f701a80-6138-11eb-8d0d-1b22a028a1da.png)
![Search](https://user-images.githubusercontent.com/32969087/106173494-11d27480-6138-11eb-8d6c-4c66d162f8dd.png)

**Comment by lucas-neuhaus-dev** [comment]
@marcaaron 
I have a couple of questions:

> We need to replace the ChatSwitcherView entirely with a "Search page"

1. Is the search a page accessed by a URL (using `redirect`)? Just like `NewGroupPage`, `NewChatPage`.... Or is it to maintain as it is right now, rendering if `isChatSwitcherActive`? If it is the second, I will create a component in `components/`, not a page.
2. This is just a double check, but from the images in the description, we can see this contact:

![image](https://i.ibb.co/2djt9yf/example-problem.png)

with the email, which makes it look like there is not a active chat with him yet (not in `recentReports`), unless of course the last message was the email  (:grin:). I'm assuming we really just want to show `recentReports`.

**Comment by marcaaron** [comment]
>Is the search a page accessed by a URL (using redirect)?

I think we can leave things as they are now. There's no need to create a `/search` route yet as we can always do this in the future.

>which makes it look like there is not a active chat with him yet (not in recentReports), unless of course the last message was the email (😁). I'm assuming we really just want to show recentReports.

Was just chatting with @trjExpensify about this and the behavior in the mock up is what we want. So if a chat has no messages it should just show the email in that second line. IIRC we are currently excluding reports that have no last message in the `Sidebar` view. So we may need to make that logic optional so that the `Search` view can show chats that have no messages.

**Comment by lucas-neuhaus-dev** [comment]
@marcaaron 
> IIRC we are currently excluding reports that have no last message in the Sidebar view

It seems to work like this. So the only way to have access to contacts without messages is with the `personalDetails` return from the `getOptions` function.
Should I add this then?

From my tests for this to work the `getOptions` function would need some additional logic, to be able to show either recent messages or email, depending on the case.

**Comment by marcaaron** [comment]
Sorry, I'm unsure of what changes you are suggesting. Can you break down what the additional logic would be?

**Comment by lucas-neuhaus-dev** [comment]
I thought it would be more stuff, but it's extremely simple. I just needed to change:
```javascript
alternateText: showChatPreviewLine ? lastMessageText : personalDetail.login
```
to 
```javascript
alternateText: (showChatPreviewLine && lastMessageText) ? lastMessageText : personalDetail.login
```
on the `createOption` function.

Alright I think I got all information I needed, going to finish testing on the platforms and create the PR. We can discuss better with the code in hands.

### Proposal

1. Create a `SearchView` component which looks a lot like `NewChatPage`. It uses the `OptionsListUtils.getSearchOptions` function to fetch both `personalDetails` and `recentReports`.
2. Replace it with the `ChatSwitcherView`, and delete everything related to it from the code.
3. On the list, show either the last message if it is a `recentReport`, or the email if it `personalDetail`.
4. For showing the text unread style and hide the pin and draft icons on the list, I will break down the current `OptionRow`'s `hideAdditionalOptionStates` prop in two: `hideAdditionalOptionStates` and `forceTextUnreadStyle`. 

The `forceTextUnreadStyle` is used on `NewChatPage` and `NewGroupPage`.

**Comment by marcaaron** [comment]
>On the list, show either the last message if it is a recentReport, or the email if it personalDetail.

To clarify, the search page should only show recent reports so we will just need some way to indicate that reports with no messages should not be filtered from the Search page but should be filtered from the Sidebar.

Rest of the plan sounds good to me :)

**Comment by lucas-neuhaus-dev** [comment]
Ohhhhh ok!
That took me a while to figure out. Needed to stop and understand the `getOptions` function better.

Added a new entry in the object prop of the `getOptions` function, called `showEmptyRecentReports`, defaulted it to false.
Set to true in the `getSearchOptions` call.

PR coming soon.
