### ISSUE TITLE
Add pin icon to left hand navigation menu for chat rows that are pinned

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

view the job on Upwork [here](https://www.upwork.com/jobs/~014f4f916839e82c3f).

**Platform - version:**  
all

**Action Performed (reproducible steps):**

1. Log into Expensify Cash
2. Pin a chat using the pin icon at the top right of the chat
![image](https://user-images.githubusercontent.com/24399930/105907415-f1e56880-5ff2-11eb-8823-15dd2c22ecd5.png)

**Expected Result:**

When a chat is pinned, it should display a small pin icon to the right hand side of the chat row in the left-hand nav.

![image](https://user-images.githubusercontent.com/24399930/105906274-7a630980-5ff1-11eb-86b1-6ad80f6e0c65.png)

The icon to be used can be found here as an .svg image: 
[pin-circle.svg.zip](https://github.com/Expensify/Expensify.cash/files/5876111/pin-circle.svg.zip)

The icon should use the color `themeColors.icon` and should be displayed at a size of 20x20. 

**Actual Result:**

There is currently no pin icon in the left-hand nav

**Notes/Photos/Videos:** 

Mockup:
![105833560-a5396780-5fc9-11eb-9c7c-3ba14c9aaa86](https://user-images.githubusercontent.com/24399930/105905850-f577f000-5ff0-11eb-921a-e9b4ffc37107.png)

**Comment by tugbadogan** [comment]
Hi, 

I'd like to work on this task and submitted my proposal via upwork.

**Comment by tugbadogan** [comment]
I'm planning to modify `ChatLinkRow` module and use `isPinned` boolean flag from `option` param (`isPinned` boolean flag is already available in this object) to add pin-circle icon here:
https://github.com/Expensify/Expensify.cash/blob/be4a3c57c29f1807b4ec3c34e8932c5cfc4fa6f0/src/pages/home/sidebar/ChatLinkRow.js#L121-L125

Also, I have to add `pin-circle.svg` to `assets/images` folder and import it to `Expensicons` module.

**Comment by jboniface** [comment]
@tugbadogan what's your name in Upwork, so we can proceed?

**Comment by tugbadogan** [comment]
@jboniface it's **Fadime Tugba Oge**

**Comment by jboniface** [comment]
@tugbadogan ah, I missed that one when I looked earlier; cool, I sent the offer!
