### ISSUE TITLE
Add Chat Preview Line to Side Bar Options

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Currently we show the user email below a chat row listed in the Sidebar like this:
<img width="372" alt="Screen Shot 2021-01-29 at 12 42 05 PM" src="https://user-images.githubusercontent.com/32969087/106334827-92c06780-622f-11eb-89b7-2a2e4e33403b.png">

For this issue we will instead include the `lastMessageText` on a report (chat) and it will be truncated like so...

![Screen Shot 2021-01-29 at 12 44 42 PM](https://user-images.githubusercontent.com/32969087/106334932-d024f500-622f-11eb-9864-4cad8c4051c0.png)

Additionally, the `lastMessage` does not yet show who left the message for reports with multiple participants.

**Deliverables:**
1. Where we are saving the `lastMessageText` we should also save the `lastActorEmail` (which should be accessible via `actorEmail` property on `reportAction` and `report`) e.g. see these two places:
https://github.com/Expensify/Expensify.cash/blob/376c07b551f067e21736f7a73581c6b6fe7ea1ad/src/libs/actions/Report.js#L252-L263
https://github.com/Expensify/Expensify.cash/blob/376c07b551f067e21736f7a73581c6b6fe7ea1ad/src/libs/actions/Report.js#L252-L263
2. Next we must replace the alternate text with the `lastMessageText` and append the `displayName` of the `lastActorEmail` when the report has multiple participants here: https://github.com/Expensify/Expensify.cash/blob/376c07b551f067e21736f7a73581c6b6fe7ea1ad/src/libs/OptionsListUtils.js#L85-L87
3. Finally we must make sure that the alternate text always shows for all options by updating the logic here:
https://github.com/Expensify/Expensify.cash/blob/376c07b551f067e21736f7a73581c6b6fe7ea1ad/src/pages/home/sidebar/OptionRow.js#L97
4. And also make sure that the `alternateText` is truncated with ellipsis

[Upwork](https://www.upwork.com/jobs/~0165b6fec21a79805c)

**Comment by parasharrajat** [comment]
I have a question though. What do we need to show in the `alternateText` if a user has shared a media in the report?
What If the last message was an image.

**Comment by marcaaron** [comment]
Great question. I'm not sure there is consensus on that yet. At the moment, the text (not html) version of those messages will just say `[Attachment]` so I'm assuming something like that is fine for now. There are two sources for getting the message at the moment and we are stripping out html tags here: 

https://github.com/Expensify/Expensify.cash/blob/376c07b551f067e21736f7a73581c6b6fe7ea1ad/src/libs/actions/Report.js#L135-L137

Before doing that we could detect the presence of an image by looking for an `img` tag and then replace it with `[Attachment]`.

This is less obvious, but the text taken from here will already have this `[Attachment]` text:
https://github.com/Expensify/Expensify.cash/blob/376c07b551f067e21736f7a73581c6b6fe7ea1ad/src/libs/actions/Report.js#L252

**Comment by parasharrajat** [comment]
## Proposal

It's simple, 
1. I will add the last message from the report to the sidebar report listing as explained above. 
2. For messages that contain media, I will add [Attachment] if it's not already in the message text. 
3. For group Chats, I will add the user name who last messages.
4. I will show the user's First name only.

**Comment by parasharrajat** [comment]
What should I show here when we click search 
![image](https://user-images.githubusercontent.com/24370807/106371571-feb7e280-638b-11eb-961f-86f5c721a049.png)

**Comment by shawnborton** [comment]
The preview line should behave the same in Search as well - basically these chat rows look the same in Search as they do on the Chats home screen, though you can keep the "Add" button there in Search.

**Comment by parasharrajat** [comment]
Question: 
1. What should I show if there is no last message? I think this condition will not arise as the code does not show an empty report.

**Comment by marcaaron** [comment]
@parasharrajat I don't think it's possible so would probably not use the `report.login` as the fallback and instead show nothing. Otherwise, it may look like the last message was a user entering an email address.

**Comment by parasharrajat** [comment]
Question:
When we search for a user using email what should be shown?

![image](https://user-images.githubusercontent.com/24370807/106507287-d4cc0080-64f0-11eb-8cb2-e7efdcf223ad.png)

**Comment by marcaaron** [comment]
Show the chat preview line. It doesn't matter if there is a display name or an email for the main text.

**Comment by marcaaron** [comment]
@shawnborton Sorry I did not catch this exchange soon enough but the comment [here](https://github.com/Expensify/Expensify.cash/issues/1366#issuecomment-770369332) is not correct. While we eventually do want that behavior it should not be added in this PR because the "Search" view is still relying on the old `ChatSwitcherView` logic which will be replaced soon.

**Comment by shawnborton** [comment]
Ah, got it. I thought the `ChatLinkRow` was a shared component by both Search and the Home screen, so I assumed that updating this component would update it everywhere.

**Comment by marcaaron** [comment]
It is, but the data fed into it will be changing.

**Comment by marcaaron** [comment]
@parasharrajat Thanks for your work on this.

**Comment by laurenreidexpensify** [comment]
Confirmed no regression - had Paid @parasharrajat
