### ISSUE TITLE
[Consumer UI Refresh] Chat preview line shouldn't show in the chat row when creating a New Group

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/Expensify.cash#1417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Desktop & iOS -  v1.0.1-419

**Action Performed (reproducible steps):**
1. Open Global Create 
2. Select New Group 
3. Notice the last message of the chat being displayed in the chat rows, or the chat rows are blank if you haven't chatted with that other user before

**Expected Result:**
When creating a New Group, the user's primary login should always be displayed as the second line of the chat row like so: 

![image](https://user-images.githubusercontent.com/16232057/107078618-75b70600-67e6-11eb-8774-511bba6b20a7.png)

**Actual Result:**

![image](https://user-images.githubusercontent.com/16232057/107075885-a137f180-67e2-11eb-959d-f352d9998178.png)

**Notes**
CC: @lucas-neuhaus-dev @marcaaron @shawnborton 

**Logs - JS/Android/iOS (if applicable)**:
N/A

**Comment by marcaaron** [comment]
@parasharrajat Sorry this was also left out of the requirements for the issue you have worked on. Slipped my mind that we wanted to preserve the existing behavior and just modify it in `OptionsListUtils` e.g.

https://github.com/Expensify/Expensify.cash/blob/037293697faf8f823ecb854e287c8153872cff03/src/libs/OptionsListUtils.js#L364-L370

Should maybe have something like `showChatPreviewLine` that would be `true` for 

https://github.com/Expensify/Expensify.cash/blob/037293697faf8f823ecb854e287c8153872cff03/src/libs/OptionsListUtils.js#L363

and 

https://github.com/Expensify/Expensify.cash/blob/037293697faf8f823ecb854e287c8153872cff03/src/libs/OptionsListUtils.js#L297

And fallback to showing the email in the other cases.

**Comment by parasharrajat** [comment]
Let me see this. Thanks

**Comment by marcaaron** [comment]
Thanks @parasharrajat 🎉
