### ISSUE TITLE
[Consumer UI Refresh] Create Group confirmation button visible without attendees selected

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/Expensify.cash#1418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Desktop & iOS - v1.0.1-419

**Action Performed (reproducible steps):**
1. Open Global Create
2. Select New Group
3. Notice the `Create Group` confirmation button is visible when attendees aren't selected

**Expected Result:**

![image](https://user-images.githubusercontent.com/16232057/107080552-5d94b600-67e9-11eb-8341-e12244dbf925.png)

**Actual Result:**

![image](https://user-images.githubusercontent.com/16232057/107080689-8b79fa80-67e9-11eb-9b3d-809ddd979674.png)

**Notes**
 CC: @lucas-neuhaus-dev @marcaaron @shawnborton

**Comment by lucas-neuhaus-dev** [comment]
I see.
I will have this changed soon, no problem!

**Comment by trjExpensify** [comment]
Thank you, Lucas!

**Comment by lucas-neuhaus-dev** [comment]
@trjExpensify 
Apologize for saying it would be soon, haha :man_facepalming:
Had to leave for a while.

**Comment by trjExpensify** [comment]
No need to apologise, thanks for getting a PR up for this!
