### ISSUE TITLE
Email addresses appearing instead of names when creating group

### ISSUE THREAD

**Issue by Dal-Papa** [Expensify/Expensify.cash#1446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Chrome Windows/Mac
1.0.1-221 although this has been reproduced recently

**Action Performed (reproducible steps):**

1. Go to expensify.cash and login as conor@expensify.com
2. On the search box, look for users and tap on the add button.
3. Add at least 4 users (you can access to) and click on "Go"
4. Verify the group is created, and that the email addresses are displaying. Wait 15-20 seconds and the account names should load
5. Sign in to conor+chatWithAName3@conorpendergrast.com, and you'll see the group is there but the email addresses display. Wait 15-20 seconds, and the account names should show

Created a group DM with these four users, whom I haven't chatted to before:

1. conor+chatWithName@conorpendergrast.com
2. conor+chatWithOutAName@conorpendergrast.com
3. conor+chatWithAName2@conorpendergrast.com
4. conor+chatWithAName3@conorpendergrast.com

**Expected Result:**
The names of all participants should be shown in the header of the conversation immediately. Like in [this screenshot](https://user-images.githubusercontent.com/1805746/107455565-58b86500-6b4f-11eb-8f99-b8d5798a4e79.png). 

**Actual Result:**
When first opening the conversation, whether from the creator or the receiver point of view, the email addresses appear in the header for 15-20s and then are replaced by the names. See [this screenshot](https://user-images.githubusercontent.com/1805746/107455775-a339e180-6b4f-11eb-85ad-fb4e669d9fef.png) when the conversation was created, and [this screenshot](https://user-images.githubusercontent.com/1805746/107455814-b64cb180-6b4f-11eb-9fc9-20abcd703108.png) when the conversation was first opened from one of the other participants. 

**Notes/Photos/Videos:** 
![100911440-9a6cc580-34a5-11eb-803f-c521972cc481](https://user-images.githubusercontent.com/1805746/107456137-f57b0280-6b4f-11eb-9f8f-525e8055b8a1.gif)

https://www.upwork.com/jobs/~0110c4704835e8d4aa

**Comment by tugbadogan** [comment]
Hi @Dal-Papa ,
I would like to work on this issue. Here is my proposal:

I found that we are making an API request to fetch personal details like `avatar` and `full name`.
https://github.com/Expensify/Expensify.cash/blob/79e7f28ed5d954204f6ba8da8c61c03ce93e1828/src/libs/actions/PersonalDetails.js#L151-L176

It looks like we are updating `avatars` for each report but we're not updating `reportName`. We can use `formattedPersonalDetails` array (returned from `formatPersonalDetails()` function) that contains `displayName` variable to generate `reportName` with full names.
https://github.com/Expensify/Expensify.cash/blob/79e7f28ed5d954204f6ba8da8c61c03ce93e1828/src/libs/actions/PersonalDetails.js#L154

**Comment by tugbadogan** [comment]
I also applied through Upwork. My Upwork name is Fadime Tugba Oge.

**Comment by Dal-Papa** [comment]
@tugbadogan : Let's do this ! We are waiting for confirmation on UpWork. 
In the meantime, we also realized that the images of the avatars were also delayed when creating a new group so hopefully fixing this issue should fix that too. 
_Sorry for the delay, we were consolidating a few issues together_

**Comment by tugbadogan** [comment]
Hi @Dal-Papa,

I've created PR for name displaying issue in existing chats.

I couldn't reproduce avatar issue while creating a new group. I couldn't create more test accounts because I'm getting "Github username doesn't exist" error. How can I create more test users to reproduce this issue?
