### ISSUE TITLE
Move Search to the RightDockedModal

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

view the job on upwork [here](https://www.upwork.com/jobs/~019f6dc14b35d73bb0).

**Platform - version:**  
current

Currently, clicking the search icon changes the functionality of the Left Hand Nav in order to show search results. We've recently introduced a right-docked modal which would be a better fit for search functionality. We're leaving the search icon in the same place as it is today (on the left), but we're going to engage the right-docked modal to show the search bar and search results when the icon is clicked. This implementation is similar to `NewChatPage` and `NewGroupPage` navigation wise.

**Action Performed (reproducible steps):**
1. Click the search icon
2. Search for a user using the search bar

**Expected Result:**
1. The search bar and results should utilize `RightDockedModal`
Note: ensure we grey out the main page content, as we do for the other pages in the `RightDockedModal`

**Actual Result:**
1. The search bar and results utilize the Left Hand Nav

**Notes/Photos/Videos:** 
![107490413-2546fc00-6b8a-11eb-9020-0dc65d5e49b8](https://user-images.githubusercontent.com/24399930/107530291-ba95c080-6b89-11eb-8b18-4c9c15770116.png)

**Comment by lucas-neuhaus-dev** [comment]
I would love to work on this issue.
I have worked on the `SearchView`, `RightDockedModal`, and `NewGroup(/Chat)Page`, so I know exactly the steps needed to reproduce the desired behavior.

Sent the proposal Upwork (Lucas Neuhaus).

### Proposal

1. Change the `SearchView` component to `SearchPage` (basically just changing the name and the folder location);
2. Delete everything related to it on `SidebarLinks`;
3. Create a new route in `src/ROUTES`: `SEARCH: '/search'`;
3. Call it on the `HomePage`, using the same pattern as the other `RightDockedModal` pages;
4. Verify everything works on all platforms.

### Questions

1. Should the arrow keys actions be disabled as they are on the other `RightDockedModal` pages?

**Comment by lucas-neuhaus-dev** [comment]
We would probably be able to delete the `isChatSwitcherActive` `ONYXKEYS` entry as well since it wouldn't control anything anymore.

**Comment by marcaaron** [comment]
Yep, sounds good @lucas-neuhaus-dev. I think we'd really be looking to remove all traces of anything referencing a ChatSwitcher as part of this step.

**Comment by marcaaron** [comment]
>Should the arrow keys actions be disabled as they are on the other RightDockedModal pages?

I'm not too sure about this question. cc @shawnborton to see what he thinks.

**Comment by shawnborton** [comment]
I think we want to have the arrow functionality work for Search like it currently does.
