### ISSUE TITLE
Set up Electron with hot reload

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

view the job on upwork [here](https://www.upwork.com/jobs/~01f880574c4fd035fb).

# Problem
When developing the Expensify.cash for desktop, you need to rebuild the application in order for your changes to take effect.

# Why is this important?
One of the great advantages of React Native is the ability to see your changes in real-time using a hot-reload feature. Developing on desktop takes longer than on other platforms, because changes in the code aren't reflected in the desktop app in real-time, like they are on web, android, and iOS.

# Solution
[Setup electron-reloader](https://www.geeksforgeeks.org/hot-reload-in-electronjs/) so that changes can take effect in real-time on desktop.

**Comment by parasharrajat** [comment]
## Proposal

We can start by adding this code
```
try {
    require('electron-reloader')(module, {
        watchRenderer: true,
    });
// eslint-disable-next-line no-empty
} catch { }
```
Into the `desktop/main.js` file. I think it covers fairly every module and Renderer process as well.
So the whole business logic resides in the Renderer process which will be covered so this will work fine. 

Applied on Upwork as Rajat Parashar as well.

**Comment by roryabraham** [comment]
@parasharrajat Proposal looks good. I've never used `electron-reloader`, but from what I've read this looks correct. Just one caveat: we'll just want to make sure that we only require `electron-reloader` as a dev dependency (and only use it in the dev environment). That will mean we'll need to set `NODE_ENV=development` to the environment whenever running `npm run desktop`, which should just be an easy adjustment to the npm script.

**Comment by parasharrajat** [comment]
yeah Sure, I will add it and we will only require the Package in the dev environment.
Something like this
```
const isDev = process.env.NODE_ENV  === 'development';
If(isDev){
....hot reload here
}
```
