### ISSUE TITLE
Message previews show encoded versions of characters

### ISSUE THREAD

**Issue by stephanieelliott** [Expensify/Expensify.cash#1481]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
All platforms, v. 1.0.1-442

**Action Performed (reproducible steps):**
1. Open two instances of expensify.cash: `Account A` (on any platform) and `Account B` (on either a web browser or the mobile app and not the desktop app)
1. In `Account A`, open/start a message to `Account B`
3. In the message text field to Account B, type the character `>`
4. As `Account B`, view the message in preview. Notice it shows an encoded version of the character, showing as `&lt`

**Expected Result:**
character should appear in the message preview as it was typed: `>`

**Actual Result:**
the message preview shows as `&lt;`

**Notes/Photos/Videos:** 

![image](https://user-images.githubusercontent.com/31225194/108096357-e2d06400-704e-11eb-98ad-f82afdc4c07b.png)

**Comment by stephanieelliott** [comment]
Please apply to this Upwork Job if you would like to work on this issue:
https://www.upwork.com/jobs/~01cbd1c35c26999772

**Comment by parasharrajat** [comment]
I would like to fix this.
## Proposal
use `_.unescape` from underscore here
https://github.com/Expensify/Expensify.cash/blob/7c138786bf23625b3ba995c5dcf8406c71d57229/src/libs/actions/Report.js#L137-L158.

It will render the correct text in the preview. Applied on Upwork as well via Rajat Parashar.

**Comment by aliabbasmalik8** [comment]
```
Here is the solutions
1) please use this package
https://www.npmjs.com/package/lodash.unescape
and use this way
    let lastMessageText = unescape(lodashGet(lastReportAction, ['message', 'html'], '').replace(/(<([^>]+)>)/gi, ''));
    lastMessageText = unescape(lastMessageText)
 
2) decode entities in custome way, here is list https://www.w3schools.com/HTML/html_entities.asp    
you can decode like this way
    let lastMessageText = lodashGet(lastReportAction, ['message', 'html'], '').replace(/(<([^>]+)>)/gi, '');
    lastMessageText = lastMessageText.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
    
    `https://stackoverflow.com/questions/5302037/javascript-string-replace-lt-into`
```
