### ISSUE TITLE
Improve clarity of unread indicator in favicon

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  Web 1.0.1.297

**Action Performed (reproducible steps):** Have an unread chat

**Expected Result:** The unread indicator on the favicon should be noticeable

**Actual Result:** It is very very easy to miss the unread indicator because it blurs into the logo

**Notes/Photos/Videos:** 
 
Here's how the favicon currently appears:
![image](https://user-images.githubusercontent.com/37308300/108138942-f7335180-708c-11eb-9395-bfe63b11d4a0.png)

Zoomed in:
![image](https://user-images.githubusercontent.com/37308300/108138953-fbf80580-708c-11eb-9455-0a8f6b9bb713.png)

We need to update it to this:
![image](https://user-images.githubusercontent.com/37308300/108139080-4e392680-708d-11eb-87f3-59b82cd4bb14.png)

**Logs - JS/Android/iOS (if applicable)**:

Here are the new assets that can be used to update the icon: 
[ECASH_unread.zip](https://github.com/Expensify/Expensify.cash/files/5992424/ECASH_unread.zip)

https://github.com/Expensify/Expensify/issues/149295
https://www.upwork.com/jobs/~01ebf6f50340c191af

**Comment by tugbadogan** [comment]
Hi @arielgreen,

I would like to work on this issue. Here is my proposal:

I found that `CONFIG.FAVICON.UNREAD` is used when there is an unread message.

https://github.com/Expensify/Expensify.cash/blob/eaba9026a62fcfe355591af578f41e533496af0e/src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js#L11-L15

https://github.com/Expensify/Expensify.cash/blob/257518b71ebd9687e733bcc777e0f07a10fd61c3/src/CONFIG.js#L48-L51

We just need to change this file with new icon.
https://github.com/Expensify/Expensify.cash/blob/master/web/favicon-unread.png

**Comment by parasharrajat** [comment]
## Proposal
The main logic to update the favicon reside here 
https://github.com/Expensify/Expensify.cash/blob/88a0c5e8f137b08c273aa7926e5326a621dd8eca/src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js#L11-L15
Which takes the favicon url from the CONFIG Keys.
https://github.com/Expensify/Expensify.cash/blob/88a0c5e8f137b08c273aa7926e5326a621dd8eca/src/CONFIG.js#L48-L51.

For now, we have to replace the old asset web/favicon-unread.png with the new asset image.

There are few points which I like to point out here.
1. We should also add a apple-touch-icon for safari browsers lIke this.
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">

```

**Comment by arielgreen** [comment]
Thanks for the proposals! @tugbadogan please proceed with your PR.
