### ISSUE TITLE
[User Settings] Implement new Profile view

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/Expensify.cash#1492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!

___

We're adding a new profile view that will display a right-docked modal with a user's avatar, primary login, as well as their first name, last name, pronouns, and timezone (as applicable, depending on what data the user has filled out. This page will mimic the current [SettingsPage.js](https://github.com/Expensify/Expensify.cash/blob/master/src/pages/SettingsPage.js) view with a few key differences
- No `Settings` title 
- No `Sign Out` button 
- New (non-editable) fields with titles that are displayed/hidden depending on what the user has filled out in the `personalDetails` onyx key) 
     - Email
     - Phone Number
     - Preferred Pronouns 
     - Local Time

**Deliverables:**
- Update HeaderView.js to display a clickable icon associated with the given chat (`report.icons`) 
   - <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108244905-8e87bb80-7104-11eb-9b0c-13f439b48ac7.png">
   - You can reuse the [MultipleAvatars.js](https://github.com/Expensify/Expensify.cash/blob/master/src/components/MultipleAvatars.js#L19) component for this 
   - If the chat has multiple participants (`report.participants > 1`) clicking on the icon should do nothing 
   - Otherwise, the chat is a direct message (having only one participant) and clicking on the icon should open the `Profile` page for that `report.participant`
       - This works similarly to how the Settings page opens up when a user clicks on their own avatar in the sidebar
- Add two new routes to [Routes.js](https://github.com/Expensify/Expensify.cash/blob/master/src/ROUTES.js)
    - `Profile: '/profile/:login`
    - ``getProfileRoute: login => `/profile/${login}` ``
- Create the right-docked modal "Profile" page following the example of the "Settings" page and refactoring as necessary 
    -  The profile page should take in the `login` associated with the `report.participant` as a prop
    - That login will be used to get the associated `personalDetail` object for that user from the `personalDetails` onyx key 
        - That object will contain the information to be displayed for this user on their Profile page.  

### Mobile 
| No Details Filled Out  | All Details Filled Out|
| ------------- | ------------- |
| <img width="300" alt="" src="https://user-images.githubusercontent.com/16747822/108243977-88450f80-7103-11eb-8f23-51231e00ea68.png"> | <img width="300" alt="" src="https://user-images.githubusercontent.com/16747822/108243894-71062200-7103-11eb-91b3-62e7ce6bae34.png"> |

### Web/Desktop
| No Details Filled Out  | All Details Filled Out|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/16747822/108244212-cfcb9b80-7103-11eb-9396-c83a19278ace.png) | ![image](https://user-images.githubusercontent.com/16747822/108244274-e3770200-7103-11eb-9e9a-f4895c1e43c8.png) |

### Upwork Link: https://www.upwork.com/jobs/~01f46c14a330e02af6

**Comment by AlishahSolanki** [comment]
@NikkiWines I am interested to work on that, can you connect on Upwork with me I have already sent a proposal.

**Comment by dc-brian** [comment]
@NikkiWines 
can you let me know one credentials?
https://prnt.sc/100dwaw
I tried to signup from the link of email
but it is showing this error
https://prnt.sc/100dx5l

**Comment by Maftalion** [comment]
Hello,
I'd like to take this if it's still available.

**Proposal**
- I would update `HeaderView` to show avatars using ` MultipleAvatars`. If there's more than one participant I would redirect to the new right-docked modal and pass the login: `redirect(ROUTES.getProfileRoute(login));`
- I would create the new route under ROUTES.js and add the new right-docked modal in HomePage.js.
- I would set up a new profile page by duplicating most of the existing settings page with the changes listed above.
- This new page would obtain the `personalDetails` from onyx using the login passed into the route.

**Questions**
- Would you like the `onPress` to be passed into `MultipleAvatars` as a prop or should it just wrap `MultipleAvatars` in `HeaderView`?
- For the person details to be display:
-- Do we have a way to determine whether `login` is an email or phone number to display the correct label?
-- I don't see Preferred Pronouns, is this planned to be added later and if so what is the name of the property that would exist on the `personalDetails`

**Comment by NikkiWines** [comment]
Hi Matt, 

Thanks for submitting your proposal. One minor note is that we only want to open the right-docked modal for chats with one participant. If there is more than one participant, we don't want to do anything when the avatar is clicked. I've updated the issue to make this a little clearer as well. 

To answer your questions: 
> Would you like the onPress to be passed into MultipleAvatars as a prop or should it just wrap MultipleAvatars in HeaderView?

I would do something similar to what we did for the clickable avatar in `SidebarLinks.js` and just wrap `MultipleAvatars` in a `TouchableOpacity` within `HeaderView.js`

> I don't see Preferred Pronouns, is this planned to be added later and if so what is the name of the property that would exist on the personalDetails

As of right now, we don't have a way for users to manually set their preferred pronouns but the property name would just be `pronouns` like so: 

![image](https://user-images.githubusercontent.com/16747822/109199271-18aed000-7754-11eb-8e88-e9bbdfdd8159.png)

**Comment by Maftalion** [comment]
Thanks @NikkiWines, I have two follow up questions:
1. The mockups above seem to use `AvatarWithIndicator`, should I be using that or just `Avatar` instead?
2. `That login will be used to get the associated personalDetail object for that user from the personalDetails onyx key`
I'm a little stuck on this but also not too familiar with Onyx, I'm doing `key: ONYXKEYS.PERSONAL_DETAILS` but I only get objects associated with my own login and concierge. how would I use the login being passed in to get the user's personalDetails?

**Comment by NikkiWines** [comment]
Hi @Maftalion, to answer your questions 

> 1. The mockups above seem to use AvatarWithIndicator, should I be using that or just Avatar instead?

Good catch! I don't believe we have a way to identify if other users are online/offline yet, so let's just use Avatar for now.

> I'm doing key: ONYXKEYS.PERSONAL_DETAILS but I only get objects associated with my own login and concierge. 

The `PERSONAL_DETAILS` onyx key contains the details of anyone who is on your policies, owns your policies, or belongs to the domain you're on in Expensify.com. They show up if they've modified their personal details in some way. If you wanted to add another user to your `PERSONAL_DETAILS` list I would do the following: 

1. Create + validate a new user in Expensify.com with an email you have access to
2. Add them to the policy associated with your main account in E.com 
3. Set a first and/or last name for that user
4. Refresh your page in E.cash and you should see the updated `PERSONAL_DETAILS` list with the newly added user. 
5. If they're still not showing up, try starting a chat with that newly added user.

> how would I use the login being passed in to get the user's personalDetails?

My thought here is that the `profile` component will receive the `participant` (aka. login) from the `report_#` key as a prop and would be subscribed to the `PERSONAL_DETAILS` onyx key. We can then we can filter the `PERSONAL_DETAILS` list to obtain the details for that specific user. However, there's a possibility that we won't be able to find the user in the personal details, so let's be sure to pass the `icon` (avatar URL) from the `report_#` key as well so that we can always display at least a phone/email and an avatar for the report participant. 

Hopefully, this clarifies things, let me know if I'm still being unclear here. 

One last note - it looks like at the moment we don't keep the `Local Time`/Timezone information for users in the `PERSONAL_DETAILS` key so you can omit that for now. I'll be working on getting that added this week.

**Comment by Maftalion** [comment]
@NikkiWines Hey, thanks for answering my questions but this creates a few more questions on my end:

1. I'm trying to create another user but it fails for me when adding my github user, can we only have one account per gh username?
2. Initially I set up the route to be `'/profile/:login` and planned to use the login from there to filter down the `PERSONAL_DETAILS`. It sounds like instead I can just get the data from the report by doing:
```
    withOnyx({
        currentlyViewedReportID: {
            key: ONYXKEYS.CURRENTLY_VIEWED_REPORTID,
        },
    }),
    withOnyx({
        report: {
            key: ({currentlyViewedReportID}) => `${ONYXKEYS.COLLECTION.REPORT}${currentlyViewedReportID}`,
        },
    }),
```
to get both the participant name and the icon and would that mean I can just update the route to be `/profile`

**Comment by NikkiWines** [comment]
Hey Matt, 

> I'm trying to create another user but it fails for me when adding my github user, can we only have one account per gh username?

You should only need to create the user on Expensify.com not on Expensify.cash 

>  would that mean I can just update the route to be /profile

Just to be extra clear are you asking 
a. If we can forgo using `PERSONAL_DETAILS` because we can get the participant name and icon from `COLLECTION.REPORT}${currentlyViewedReportID}`
b. If we can forgo appending `:login` to the route because we can just pass the participant name and icon as props and display the user's information without the need for a more specific route
c. both a and b
d. none of the above, and I've misunderstood your question.

**Comment by Maftalion** [comment]
Thanks! I was totally using Expensify.cash, but it worked when using Expensify.com.

Mostly B I think haha. 

Basically I think since we can get the report from the code i posted above, it's no longer necessary to pass login through the route itself (it also made me have to make some changes to the right docked modal bc it didn't support dynamic paths).

We would still need `PERSONAL_DETAILS` to get all the other data outside of login/avatar.

**Comment by Maftalion** [comment]
the other two options would be:

1. don't grab the report from onyx and instead pass both login & avatar when routing. maybe something like `/profile/:login?avatar=...` but i havent seen any params being passed elsewhere in the app so would have to test this.
2. continue to use `/profile/:login` but ignore login from the route and just grab it from the report instead

**Comment by NikkiWines** [comment]
> Basically I think since we can get the report from the code i posted above, it's no longer necessary to pass login through the route itself

Ah, I see what you're saying. Since we have to click on the avatar of a currently viewed chat to open the `profile` modal we can use `currentlyViewedReportID` instead of explicitly passing the login. Nice, that sounds great to me, and it keeps things a little simpler which is always good.

> We would still need PERSONAL_DETAILS to get all the other data outside of login/avatar.

Yes exactly. I was hoping you weren't asking option A. 

wrt your other three options, I think your original suggestion has the cleanest implementation - let's go with that.

**Comment by NikkiWines** [comment]
Closing as this issue has been completed successfully in https://github.com/Expensify/Expensify.cash/pull/1593
