### ISSUE TITLE
[User Settings] Implement Settings Menu Selectors

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/Expensify.cash#1493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

We need to update the existing Settings page to include four new menu items that will link to new sub-pages. When one of the menu items is selected, a new view should appear with the title of the menu item selected.

In addition to the title, each menu item will have an icon on the left-hand side, as well as a right-facing arrow on the right-hand side (`arrow-right.svg`) The icons needed for these menu items are: 
     - Profile: `profile.svg`
     - Preferences: `gear.svg`
     - Change Password: `lock.svg`
     - Payments: `wallet.svg`
  
Icons can be found in the following zip file: [UI_Icons.zip](https://github.com/Expensify/Expensify.cash/files/5998018/UI_Icons.zip)

### Deliverables: 
- Add four clickable menu items `Profile`, `Preferences`, `Change Password`, and `Payments` to [SettingsPage.js](https://github.com/Expensify/Expensify.cash/blob/blob/src/pages/SettingsPage.js)
- When a menu item is clicked, the right-docked modal should hide the existing settings view, and display the new view with the title of the page
    -  Use `params.match.route` to determine which view to display.  
- When a sub-page is closed, the view should display the Settings page once again
- Add two new routes to [ROUTES.js](https://github.com/Expensify/Expensify.cash/blob/master/src/ROUTES.js)
     - `SUBSETTINGS: '/sttings/:route'`
     - ``getSettingsRoute: route => `/settings/${route}` ``

 
| Mobile  | Web|
| ------------- | ------------- |
| <img width="300" alt="" src="https://user-images.githubusercontent.com/16747822/108277495-5301e700-712e-11eb-997f-5299ca0b3293.png"> | <img width="700" alt="" src="https://user-images.githubusercontent.com/16747822/108277266-facae500-712d-11eb-8b4b-34427d241952.png"> |

### Sample Flow for clicking on the `Preferences` Menu Item
![Screen Shot 2021-02-17 at 2 40 40 PM](https://user-images.githubusercontent.com/16747822/108277604-88a6d000-712e-11eb-9542-5489cb4300aa.png)

**Comment by shawnborton** [comment]
Just leaving a note that the rows here should use the same style as the global create menu (green "+" button):
![image](https://user-images.githubusercontent.com/2319350/108246628-f0badd80-7151-11eb-89b2-5b79f7f717d9.png)


Meaning, they should have the same padding, icon size, and font size. We might want to DRY up how that component is used if it's going to be a shared style.

**Comment by shawnborton** [comment]
Working on the icons now and will post them shortly.

**Comment by shawnborton** [comment]
What are your thoughts on using a wallet icon instead of cash for "Payments"?
![image](https://user-images.githubusercontent.com/2319350/108254607-8444dc00-715b-11eb-90c6-62d05a6bea72.png)

**Comment by NikkiWines** [comment]
Looks great to me!!

**Comment by shawnborton** [comment]
Here are the icons:

[UI_Icons.zip](https://github.com/Expensify/Expensify.cash/files/5998018/UI_Icons.zip)

**Comment by NikkiWines** [comment]
Great, thank you @shawnborton!! Taking this off hold!

**Comment by Maftalion** [comment]
Hello,
I'd like to take this if it's still available.

**Proposal**

- I would first create a new Cell component that takes `icon` `title` and `showRightArrow` props to be reusable across the app.
- Then I would add Profile, Preferences, Change Password, and Payments Cells to the SettingsPage.

This is where it gets a bit tricky....from what I've tested there's currently no way to go from RightDockedModal -> RightDockedModal. What happens is the route gets updated before the previous route's modal animation completes and never opens the new modal.

The three options I can think of to handle this are:
1. create a hacky approach to use `onClose` in the RightDockedModal to re-trigger the redirect. for example if you route to `/settings/payments` the right docked modal will add the redirect to `/settings/payments` as well so settings calls redirect -> settings modal closes -> onClose calls redirect to `/settings/payments` which opens the modal again
2. switch to use a built-in drawer library that has a more elaborate implementation to make this possible. or rewriting to use react-navigation which is cross platform and supports drawers pretty well.
3. If you don't need the close modal -> open modal animation you can conditionally render the settings page based on the state/param. for example /settings would render the normal settings page but clicking one of the buttons renders a different component within that same RightDockedModal. video below shows this process:

https://user-images.githubusercontent.com/12075600/109603805-4048c400-7ad7-11eb-8b1f-e622f756b763.mov

**Comment by NikkiWines** [comment]
Hey Matt, 

This is indeed still available. A couple of notes on your proposal 

> or rewriting to use react-navigation which is cross-platform and supports drawers pretty well.

This is a good thought and one we had ourselves as well.  We are considering implementing react-navigation but didn't want to hold this project on the outcome of that discussion. 

> If you don't need the close modal -> open modal animation you can conditionally render the settings page based on the state/param. for example /settings would render the normal settings page but clicking one of the buttons renders a different component within that same RightDockedModal. video below shows this process:

This is the implementation we had in mind for this issue. As you said, the idea is the new 'pages' are views inside the right-docked Settings modal that get conditionally rendered. You could achieve this by using `match.params.route`.

**Comment by Maftalion** [comment]
@NikkiWines hey, looks like this is on the settings page. I'm assuming this would live under `Preferences`, want me to move it into that subroute?
<img width="494" alt="Screen Shot 2021-03-03 at 2 04 07 PM" src="https://user-images.githubusercontent.com/12075600/109878722-7dbd6680-7c29-11eb-9dcb-2dee3cd8b8f2.png">

Also, lemme know if you want the right arrow visible on this menu as well or if I should leave it as is:
<img width="494" alt="Screen Shot 2021-03-03 at 2 01 09 PM" src="https://user-images.githubusercontent.com/12075600/109878801-9b8acb80-7c29-11eb-948f-2467924e30b5.png">

**Comment by NikkiWines** [comment]
Hey @Maftalion 

> I'm assuming this would live under Preferences, want me to move it into that subroute?

Yes feel free to move that there. 

> Also, lemme know if you want the right arrow visible on this menu as well or if I should leave it as is:

Let's leave it as is for now!!
