### ISSUE TITLE
[User Settings] Add new Payments view

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/Expensify.cash#1496]
Having added four new menu items to the Settings page, we now need to begin linking those menu items to actual pages.  This issue pertains to the `Payments` page. 

The Payments view will be displayed when the "Payments" menu item is clicked. It will display a header with a left-facing arrow on the left-hand side, a title, and an `X` button to close the view on the right-hand side. The view will contain a prompt, a text box with a title and placeholder, and a button with the text `Add a Paypal Account`

### Deliverables 

- Clicking on the `Payments` menu item on the Settings page will route the user to `settings/payments` via the payments route in ROUTES.js and display the new view
- The text field should contain the value of the `nvp_payPalMeAddress` onyx key, if it exists. 
    - If the key doesn't exist or is empty, the field should contain a placeholder value `Your Paypal username`  
- Pressing `Add Paypal Account` will call `NameValuePair.Set` with the following parameters:
    - name = `"expensify_PayPalMeAddress"`
    - value = string value of whatever the user entered in the text field. 
- Pressing `X` will close the right-hand modal and route the user back to the last viewed report
- Pressing `<` should display the main settings view.

| Mobile  | Web/Desktop |
| ------------- | ------------- |
| <img width="300" alt="" src="https://user-images.githubusercontent.com/16747822/108260497-3f975180-7117-11eb-9d8e-a70ac4fc8163.png"> | <img width="700" alt="" src="https://user-images.githubusercontent.com/16747822/108260108-c3047300-7116-11eb-82ba-3cb9bed0b010.png"> |

### Upwork Link: https://www.upwork.com/jobs/~0103782fbda3be06eb

**Comment by Shailesh351** [comment]
https://user-images.githubusercontent.com/18264684/110787820-d6c57400-8293-11eb-9a7b-6e5b8d883a47.mov

@NikkiWines After clicking on `Add Paypal Account` it should show something that shows it was added successfully. What do you think?

**Comment by NikkiWines** [comment]
@Shailesh351 nice! this is looking great. 

>  After clicking on Add Paypal Account it should show something that shows it was added successfully. What do you think?

We were originally considering a snackbar/growl for success/failure but considered it out of scope for this issue - there doesn't need to be any sort of indicator for success at this time.

However, @shawnborton this is looking a little weird without any feedback whatsoever. Curious to your thoughts about a low cost option for letting the user know we'd saved their changes.

**Comment by shawnborton** [comment]
I agree with you Nikki. So I think we should just formally propose a P/S for adding a lost-cost growl solution, and implement that separate from this PR. We can work with you to come up with some styling ideas, but let's decouple that project from this particular step for now.

**Comment by NikkiWines** [comment]
Closing as https://github.com/Expensify/Expensify.cash/pull/1739 has been merged.
