### ISSUE TITLE
Padding and alignment on compose field for iOS looks misaligned

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#1500]
**Platform - version:**  
iOS 14
iPhone X

**Action Performed (reproducible steps):**
Open expensify.cash and login. Observe the **Compose** box. The text inside of the compose box is misaligned. It is not vertically centered. 

**Expected Result:**
I would expect the text to be vertically aligned within the compose area. See below, it is sitting too low in the box. 

**Actual Result:**
![image](https://user-images.githubusercontent.com/2319350/106277916-1da65f80-623a-11eb-9a31-1c8937bd8601.png)

**Notes/Photos/Videos:** 
 
**Logs - JS/Android/iOS (if applicable)**:

**Comment by kadiealexander** [comment]
Upwork listing: https://www.upwork.com/jobs/~01c80596a92bad7845

**Comment by aliabbasmalik8** [comment]
Just remove `alignSelf: 'center',`  from this style object `textInputCompose` that located in styles/styles.js
<img width="1174" alt="Screen Shot 2021-02-18 at 11 54 00 PM" src="https://user-images.githubusercontent.com/31027036/108437173-b4b47500-7244-11eb-9c2e-f0bc757ab83b.png">

**Comment by shawnborton** [comment]
@aliabbasmalik8 can you confirm that your proposed change will not break other platforms as well?

**Comment by aliabbasmalik8** [comment]
yes, because this style object `textInputCompose` used only one place in the App

**Comment by aliabbasmalik8** [comment]
Here is an updated solution that tested on web app as well as mobile devices
We need to import 
`import { Platform } from 'react-native';` at the top of `src/styles/styles`
and add this code in `textInputCompose` style Object
`...Platform.select({
            web: {
                alignSelf: 'center',
            }
        }),
        `
![image](https://user-images.githubusercontent.com/31027036/108486232-c6723880-7295-11eb-9cf1-142b927ea4ef.png)

**Comment by shawnborton** [comment]
@marcaaron curious for your thoughts on the above... I know we try to avoid platform-specific instances like the above proposal, but I'm not sure how else to solve for this one.

**Comment by marcaaron** [comment]
Yes, well there is nothing wrong with having a platform specific implementation. It just needs to follow the guidance [here](https://github.com/Expensify/Expensify.cash/blob/master/README.md#platform-specific-file-extensions) as we have decided to avoid using `Platform` in the code. Instead we'd add something like this:

```
.
└── textInputAlignSelf/
    ├── index.js
    └── index.native.js
```

**Comment by aliabbasmalik8** [comment]
Got it. so updated solution according to guidance is here
Added textInputAlignSelf utilities like this

![image](https://user-images.githubusercontent.com/31027036/108541212-14a92b00-72da-11eb-82d6-3bd15d975ab2.png)

and import at top 
`import textInputAlignSelf from './utilities/textInputAlignSelf';`
and updated `textInputCompose` style object like this

![image](https://user-images.githubusercontent.com/31027036/108541244-2094ed00-72da-11eb-999a-fcacf0d39f98.png)

**Comment by marcaaron** [comment]
yep, you got it

**Comment by aliabbasmalik8** [comment]
@kadiealexander can I do this Ticket?

**Comment by kadiealexander** [comment]
@aliabbasmalik8 Hey! Thanks for sharing this fix. My colleague wanted to confirm if this will also fix the issue for Android, as we discovered the issue exists here too. Thanks in advance!

**Comment by aliabbasmalik8** [comment]
@kadiealexander  I tested it on all platforms and it's working well and also attached a screenshot for the android platform.
Please let me know the device name if you still face this issue
Thanks
 
![image](https://user-images.githubusercontent.com/31027036/110104168-b6cb1780-7d9e-11eb-842a-69ae4c89a7c7.png)
