### ISSUE TITLE
Update desktop app title bar style

### ISSUE THREAD

**Issue by puneetlath** [Expensify/Expensify.cash#1503]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
Upwork posting: https://www.upwork.com/jobs/~0156d292c1f9d2ed43

**Platform - version:**  
Mac Desktop app 

**Current:**
Right now this is what the title bar looks like on the mac electron app. 
![image](https://user-images.githubusercontent.com/1371996/108402991-d7627180-71e3-11eb-8efa-09ea9d55fdea.png)

**New:**
This is what we want it to look like: 

![image](https://user-images.githubusercontent.com/1371996/108403186-12fd3b80-71e4-11eb-9d7b-e9fe571a487f.png)

**Notes/Photos/Videos:** 
Notice that the button color is only shown when hovered. 

Not Hovered | Hovered
----- | -----
![image](https://user-images.githubusercontent.com/2319350/107886254-f5d41e80-6efe-11eb-912a-2840972d78fe.png) | ![image](https://user-images.githubusercontent.com/2319350/107886243-e8b72f80-6efe-11eb-9b50-a8de2b0111ce.png)

**Comment by eneskarpuz1** [comment]
My proposal;
1.Remove existing titleBar with setting "frame:false" on BrowserWindow from desktop/main.js.
```javascript  
/*desktop/main.js:*/
const browserWindow = new BrowserWindow({
                backgroundColor: '#FAFAFA',
                width: 1200,
                height: 900,
                frame:false,
                webPreferences: {
                    nodeIntegration: true,
                },
```
2.Creating new titleBar with dynamic html which contains styling,hover and drag listener to web/index.html, which is renderer of electron.
 ```javascript
/*Sample : */
 let titleBar = document.getElementById("title-bar");
      titleBar.style.webkitAppRegion = "drag";
      titleBar.style.webkitUserSelect= "none";
```
3.This titlebar only will be rendered on desktop using browser conditions.
```javascript
/*Sample:*/
var opera = (!!window.opr && !!opr.addons) || !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0;
```
4.Button functions(window.maximize() etc.) will be applied using `'remote';
```javascript     
/*Sample:*/    
          const { remote } = require('electron');
          const { BrowserWindow } = remote;
      /* ... */
            document.getElementById("min-button").addEventListener("click", function (e) {
                    var window = BrowserWindow.getFocusedWindow();
                    window.minimize();
               }); 
  /* ... */
```

**Comment by eneskarpuz1** [comment]
Hi @puneetlath, 
I would like to work on this issue and I submitted a proposal on Upwork regarding this issue.

Here is my proposal;
1- I will remove existing titleBar with setting "frame:false" on BrowserWindow from desktop/main.js.
```javascript  
/*desktop/main.js:*/
const browserWindow = new BrowserWindow({
                backgroundColor: '#FAFAFA',
                width: 1200,
                height: 900,
                frame:false,
                webPreferences: {
                    nodeIntegration: true,
                },
```
2- Creating new titleBar with dynamic html which contains styling,hover and drag listener to web/index.html, which is renderer of electron.
 ```javascript
/*Sample : */
 let titleBar = document.getElementById("title-bar");
      titleBar.style.webkitAppRegion = "drag";
      titleBar.style.webkitUserSelect= "none";
```
3- This titlebar only will be rendered on desktop using browser conditions.
```javascript
/*Sample:*/
var opera = (!!window.opr && !!opr.addons) || !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0;
```
4- Button functions(window.maximize() etc.) will be applied using `'remote';

**Comment by puneetlath** [comment]
As we discussed in slack, I think the ideal would be to make this a `component` which only gets rendered on Desktop by putting it in a `index.desktop.js` file. Rather than by editing the HTML and using browser conditions.

**Comment by ilijaprzeski** [comment]
Ok, got it.

**Comment by ilijaprzeski** [comment]
This is not default theme in macos desktop app.
![Screen Shot 2021-02-23 at 9 20 58 PM](https://user-images.githubusercontent.com/71725797/108902946-0716dc80-761d-11eb-9504-5d59d9fbb2eb.png)
This is for title bar of not focused desktop app

**Comment by puneetlath** [comment]
After a discussion in Slack we decided that doing the custom buttons wasn't worth the trouble. Thanks again @ilijaprzeski!

**Comment by ilijaprzeski** [comment]
Thank you so much for understanding me.
