### ISSUE TITLE
[IOU] Make CreateMenu dynamic, add launch Modal options

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

view the job on Upwork [here](https://www.upwork.com/jobs/~014db3f8a95478ac7f).

**Platform - version:**  
current

**Deliverables:**

This issue builds on top of the existing [CreateMenu](https://github.com/Expensify/Expensify.cash/blob/master/src/components/CreateMenu.js) Bottom Drawer (original issue which introduced this modal can be [found here](https://github.com/Expensify/Expensify.cash/issues/1240)) 
<img width="294" alt="New Menu" src="https://user-images.githubusercontent.com/10736861/108239029-64a0ba00-7141-11eb-8664-0279ac8c222b.png"> ![Chat (2)](https://user-images.githubusercontent.com/10736861/108239159-85690f80-7141-11eb-986d-e915d4444495.png)

![Chat (3)](https://user-images.githubusercontent.com/10736861/108400064-b6fddb80-7212-11eb-8800-86b2d7ead449.png)

1. Add a `menuOption` enum to the [CreateMenu](https://github.com/Expensify/Expensify.cash/blob/master/src/components/CreateMenu.js) class
	- With the following types: `NewChat: 'NewChat'`, `NewGroup: 'NewGroup'`, `RequestMoney: 'RequestMoney'`, `SplitBill: 'SplitBill'`, `AttachmentPicker: 'AttachmentPicker'`
2. Add a new CreateMenu prop `menuOptions` which takes an array of the above `menuOption`s. The `menuItemData` array should be modified and should now be created dynamically in the constructor, based upon the `menuOptions` prop
3. The existing usage of the CreateMenu Modal should then be refactored to use the new prop method ([for example here](https://github.com/Expensify/Expensify.cash/blob/ec9f9cb84f7a88b79ac2bd46861b908448630bdc/src/pages/home/sidebar/SidebarView.js#L54)), and new array items should be generated for the new `menuOption`s (RequestMoney, SplitBill, AttachmentPicker). For now RequestMoney & SplitBill can redirect to an existing route.
4. A new prop should be created on The ReportView Component: `hasMultipleParticipants` which will be true if participants is greater than 2
5. In a 1:1  or group chat, the [attachment picker ](https://github.com/Expensify/Expensify.cash/blob/e63583c07393f55af1e629d53364e30c0daaf27c/src/pages/home/report/ReportActionCompose.js#L150-L171)should be replaced with the `CreateMenu` Component. 
    - The ReportView `hasMultipleParticipants` prop should then be used to determine the correct menu options to pass in (`SplitBill|AddAttachment` if true, else `RequestMoney|AddAttachment`). 
    - When the AttachmentPicker option is selected, a callback to the parent component should be invoked via another new prop: `onAttachmentPickerSelected` or something similar. Finally, this callback should trigger the AttachmentPicker to be rendered from the [ReportActionCompose](https://github.com/Expensify/Expensify.cash/blob/77f84d86e38d3554c3ce5476d60f5e229e67441d/src/pages/home/report/ReportActionCompose.js#L160-L222) Component, like it was prior to the CreateMenu addition.
6. The new image assets (for the new menu items) should be added as Expensicons [here](https://github.com/Expensify/Expensify.cash/blob/master/src/components/Icon/Expensicons.js) -- these should be available as the attachment: [MenuIcons.zip](https://github.com/Expensify/Expensify.cash/files/6005940/MenuIcons.zip)

**Comment by Maftalion** [comment]
Hello,
I'd like to take on this task.

**Proposal**
1. refactor the `CreateMenu` class to accept the `menuOptions` listed above as a prop.
2. move the `menuItemData` out of the render and build the array instead in the constructor based on the `menuOptions` props.
3. update existing uses of the `CreateMenu` component to pass the menu items.
4. update `CreateMenu` to have a new `hasMultipleParticipants` prop when more than one participant and if true the menu items would be `SplitBill|AddAttachment` or `RequestMoney|AddAttachment` if not true.
5. add  `onAttachmentPickerSelected` which will render `AttachmentPicker` if that option is selected

**Comment by Jag96** [comment]
@Maftalion your proposal looks good 👍

**Comment by Jag96** [comment]
Looks like this was fixed by https://github.com/Expensify/Expensify.cash/pull/1548, closing
