### ISSUE TITLE
Typo in passing props to PDF in PDFView component

### ISSUE THREAD

**Issue by anthony-hull** [Expensify/Expensify.cash#1514]
https://github.com/Expensify/Expensify.cash/blob/309a1308693c1e73f2632c9654a0f73c90aa5267/src/components/PDFView/index.native.js#L39

**Comment by parasharrajat** [comment]
Nice I will fix it in my PR for #1383

**Comment by AndrewGable** [comment]
Nice find @anthony-hull!
