### ISSUE TITLE
[Desktop] index.desktop.js is not working

### ISSUE THREAD

**Issue by ilijaprzeski** [Expensify/Expensify.cash#1537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  Desktop - [PR1533](https://github.com/Expensify/Expensify.cash/pull/1533)

**Action Performed (reproducible steps):**

Run the desktop app on macOS.
```
npm run desktop
```
If run the desktop app, you will see the following screen.
![](https://user-images.githubusercontent.com/71725797/108740126-a1035a00-7535-11eb-9078-a5bbc3d15b20.png)

If desktop environments works well and index.desktop.js files are applied to desktop app, you will get following screen.
Expected Result | Current Result
------ | ------
![Expected Result](https://user-images.githubusercontent.com/71725797/108740882-6a7a0f00-7536-11eb-9d38-1dc4c1e30f0e.png) | ![Current Result](https://user-images.githubusercontent.com/71725797/108740698-3d2d6100-7536-11eb-8057-9a2c87f258e2.png)

**Comment by shawnborton** [comment]
I'm not entirely sure I am following the problem. Can you elaborate on what exactly is broken, and if possible, how we might fix it?

**Comment by marcaaron** [comment]
cc @AndrewGable @roryabraham if they have any ideas on how to fix this...

I tested out @ilijaprzeski's PR [here](https://github.com/Expensify/Expensify.cash/pull/1533/files) and discovered a workaround:

- If we do not include an `index.js` file and instead include a `index.website.js` and `index.native.js` and `index.desktop.js` the correct file is used. So maybe we can go with that for now to unblock the linked PR.

**Comment by ilijaprzeski** [comment]
Hi, @marcaaron 
You mean, i should create index.website.js and index.native.js instead of index.js?

**Comment by ilijaprzeski** [comment]
Ok, everything works correctly.

**Comment by roryabraham** [comment]
@ilijaprzeski Thanks for reporting this issue. I found a simple solution to this problem which I'll x-post here: https://github.com/Expensify/Expensify.cash/pull/1533#issuecomment-783604268

**Comment by ilijaprzeski** [comment]
Thanks, @roryabraham

**Comment by ilijaprzeski** [comment]
Solved. Thanks again, @roryabraham
