### ISSUE TITLE
Cannot pin a chat if it contains no messages

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Desktop & Web - 1.0.1-461

**Action Performed (reproducible steps):**
Press the + button to start a new chat with an individual who you have never messaged before. 
Before sending any message, pin the chat.

**Expected Result:**
The chat should be pinned in the chat list on the left.

**Actual Result:**
The pin reflects in the chat list momentarily, but as soon as you click on another chat, it disappears.

https://github.com/Expensify/Expensify/issues/153409
https://www.upwork.com/jobs/~01dc4c143fd4be1b85

**Comment by parasharrajat** [comment]
I would like to solve this problem.

### Proposal
1. pass a configuration option such as`keepEmptyPinnedReports:boolean` to the `createOptions` method here.
https://github.com/Expensify/Expensify.cash/blob/a897058dc9059763f4ce7b6fcf7b9d647ea6e0b6/src/libs/OptionsListUtils.js#L150-160
2. Add the same config option following up to the method chain till the `getSidebarOptions` and setting its value `true` here.
3. In `CreateOption` 
https://github.com/Expensify/Expensify.cash/blob/a897058dc9059763f4ce7b6fcf7b9d647ea6e0b6/src/libs/OptionsListUtils.js#L181-L185
Allow the reports if the `keepEmptyPinnedReports` is true.

**Comment by anthony-hull** [comment]
##Proposal

1. I would first update the tests here to cover this bug:
https://github.com/Expensify/Expensify.cash/blob/a897058dc9059763f4ce7b6fcf7b9d647ea6e0b6/tests/unit/OptionsListUtilsTest.js#L307-L323
2. In line 182 I would add `!reportOption.isPinned` to the if statement.
https://github.com/Expensify/Expensify.cash/blob/a897058dc9059763f4ce7b6fcf7b9d647ea6e0b6/src/libs/OptionsListUtils.js#L181-L184

I don't think there is a feature that requires to turn this behaviour off so I wouldn't plan on adding a parameter to the getOptions unless you have a justification for it.

I recently worked on this getSidebarOptions() function for a feature so am familiar with writing tests for; and working in this area of the code.

I would also look at adding more test cases to cover off other options to improve maintainability and prevent future bugs.

**Comment by marcaaron** [comment]
Both of these proposals have the right idea. I agree with @anthony-hull's assessment

>I don't think there is a feature that requires to turn this behaviour off so I wouldn't plan on adding a parameter to the getOptions() and getSidebarOptions() unless you have a justification for it.

Seems like we'd want this to be the _default_ behavior so I think we would not need a `keepEmptyPinnedReports` option.

**Comment by arielgreen** [comment]
Thanks for the proposals, guys. Rajat, I see you're working on a few issues already, so @anthony-hull please proceed. Sending over an offer now.
