### ISSUE TITLE
[GH Actions] Update semantic versioning for Expensify.cash

### ISSUE THREAD

**Issue by roryabraham** [Expensify/Expensify.cash#1572]
Upwork posting: https://www.upwork.com/jobs/~011cb60c9e032b2c3b

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

# Problem
We use the following semver (semantic versioning) schema for Expensify.cash: `MAJOR.MINOR.PATCH-BUILD`. Right now, the [bumpVersion](https://github.com/Expensify/Expensify.cash/blob/master/.github/actions/bumpVersion/action.yml) action only ever increments the `BUILD` version, but we need to be able to increment other segments of the semver version, too.

# Why is this important?
This is a requirement in order to deploy Expensify.cash mobile to production.

# Solution
We need the following updates made to the existing `bumpVersion` action:

1) It should take a `SEMVER_LEVEL` input which must be one of: [`MAJOR`, `MINOR`, `PATCH`, `BUILD`]
2) Based on the `SEMVER_LEVEL` parameter, it must update the correct portion of the semver version. So if the current version were `1.0.1-444` and I execute the `bumpVersion` action w/ a `SEMVER_LEVEL` of `BUILD`, the new version should be `1.0.1-445`.
3) Whenever you update a higher `SEMVER_LEVEL`, the lower levels should be reset to 0. For example, if the the current version were `1.0.2-444` and I execute the `bumpVersion` action w/ a `SEMVER_LEVEL` of `MINOR`, then the new version should be `1.1.0`. 
4) A `BUILD` level of 0 should not be included in the semantic version. So if the the current version were `1.0.1-444` and I execute the `bumpVersion` action w/ a `SEMVER_LEVEL` of `PATCH`, then the new version should be `1.0.2`, _not_ `1.0.2-0`.
5) We also need this action to output the new version string to the workflow that executes it.
6) The maximum number for each `SEMVER_LEVEL` should be `999`, and if the maximum is reached then it should automatically bump the next level up. For example, if the current version is `1.0.999` and I execute this action w/ a `SEMVER_LEVEL` of `PATCH`, then this action should update the version to `1.1.0`, not `1.0.1000`.
7) The existing functionality, which retries the `npm version` command in the event of a race condition/version conflict must be maintained.
8) Automated tests should be written to cover all the functionality of this action.

## To be considered complete

- Verify that all 8 of the above are satisfied
- Document testing done for this action in a separate repo before we will merge a PR and QA it in Expensify.cash
- Provide a set of automated tests
- You must test that all build levels are updated as expected.
- Verify that the action still properly handles the npm version race condition that can occur if two or more PRs are merged in quick succession. You can test this by:
    1) Manually create a git tag in your repo for the highest existing version +1
    2) Execute this action, and if it bumps the version to the level of the tag you created in the previous step +1, then it was a success.
- Verify that the version generated by this action is successfully output to the workflow that executed it by echoing the version in the workflow.

**Comment by sagacity-developer** [comment]
The versioning should be maintained some where in dynamo db table or in Json file, whenever new MAJOR, MINOR, PATCH, BUILD will come the key value mapping should done and updated accordingly. with the increment. Index reset  should be applied once it will reach to 999.

**Comment by nik0811** [comment]
The versioning should be maintained some where in dynamo db table or in Json file, whenever new MAJOR, MINOR, PATCH, BUILD will come the key value mapping should done and updated accordingly. with the increment. Index reset should be applied once it will reach to 999.

**Comment by roryabraham** [comment]
> The versioning should be maintained some where in dynamo db table or in Json file

@nik0811 Thanks for your input, but first let me explain how we currently manage versions in Expensify.cash. The please re-read the issue description and provide a more detailed proposal.

The version number is stored in [package.json](https://github.com/Expensify/Expensify.cash/blob/master/package.json#L3). We use a [Github Action](https://github.com/Expensify/Expensify.cash/blob/master/.github/actions/bumpVersion/action.yml) to update the app version automatically when a pull request is merged, but before we deploy new code. So the data is stored in Github – we don't want to set up or use some external database just for the app version.

We have some [custom logic](https://github.com/Expensify/Expensify.cash/blob/master/.github/actions/bumpVersion/bumpVersion.js) to handle a race condition that can occur when two or more PRs are merged in quick succession.

However, that code currently only updates the `BUILD` version, and we need it updated such that it takes in a `SEMVER_LEVEL` and updates the `MAJOR`, `MINOR`, `PATCH`, or `BUILD` version accordingly.

**Comment by nik0811** [comment]
Thanks for the update @roryabraham, I will look into it. Forking the repository for now.

**Comment by FredericoGauz** [comment]
Hi @roryabraham , 

I will extract the logic of the "bumping" out of the main function just to make things cleaner and easier to test.

I will simply increase the required level and then check if new number reaches 1000 if so increase the next one accordingly until the MAJOR since it should never get that high! =)

After this done it will be a matter of updating the `newBuildNumber` and running the appropriate function:

```
exec(`npm version ${newBuildNumber} -m "Update version to ${newBuildNumber}"`,
                            // eslint-disable-next-line no-shadow
                            (err, stdout, stderr) => {
                                console.log(stdout);
                                if (err) {
                                    console.log(stderr);
                                }
                            });
```

Since nothing on the current flow will really change, it should work as expected. I will write unity tests for the added functions and make the test in: 

> Verify that the action still properly handles the npm version race condition that can occur if two or more PRs are merged in quick succession. You can test this by:
Manually create a git tag in your repo for the highest existing version +1
Execute this action, and if it bumps the version to the level of the tag you created in the previous step +1, then it was a success.

To check if the racing condition logic is still working as expected.

Let me know your thought, I will also apply for this issue in upwork.

Thanks,

**Comment by roryabraham** [comment]
@FredericoGauz Your proposal looks good! You'll need to also ensure that you update the [action metadata file](https://github.com/Expensify/Expensify.cash/blob/master/.github/actions/bumpVersion/action.yml) to take in a `SEMVER_LEVEL` as input and output the new version (after it has been successfully created). You can interface with the Github Action data (inputs and outputs) using the `@actions/core` package that's already included. You may also find it helpful to check out the [README](https://github.com/Expensify/Expensify.cash/blob/master/.github/workflows/README.md) for our Github workflows and actions.

Note: don't forget to recompile your actions using `npm run gh-actions-build` 😁

**Comment by FredericoGauz** [comment]
@roryabraham  That's great, I will start working on it right now! 

OK, I will do that and build the index.js with `ncc `as well =)

**Comment by FredericoGauz** [comment]
Hi @roryabraham I hope you are having a good day. I made a pull request with the changes required. It took a little longer because it is my first work with you and as it seem to be an important issue for your team I made lots for test in my forked (and before on my cloned) repository to make sure it would work as expected.

It took a little bit of time to get used to some details of the project. I hope this is what you are looking for.

I can also see that you made some changes to the files I was supposed to update. Please let me know how you want to proceed.

Thanks,
Frederico

**Comment by parasharrajat** [comment]
This issue is already resolved and thus should be closed.

**Comment by roryabraham** [comment]
Thanks @parasharrajat
