### ISSUE TITLE
[GH Actions] Create the markPullRequestsAsDeployed action

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

# Problem
There is no obvious audit trail on Expensify.cash pull requests that show us whether they've been deployed.

# Why is this important?
Right now, this isn't a super critical issue because PRs are always deployed when they're merged. But soon, that won't be the case. Furthermore, right now we're only deploying once, directly to production, but soon we'll be deploying pull requests first to staging, then to production.

# Solution
Create a Github Action called `markPullRequestsAsDeployed` that takes the following inputs:

1) `PR_LIST`: `Array<Number>` – The list of PR #’s to comment in
2) `IS_PRODUCTION_DEPLOY`: `Boolean`

And it will use [`octokit.issues.createComment`](https://octokit.github.io/rest.js/v18#issues-create-comment) to comment on every PR in the list stating that it was deployed to staging or production.

## To be considered complete

- You must provide documentation that this has been tested in a separate repo (or a fork of Expensify.cash) as is working as expected.
- Just because the PR is merged doesn't mean that your work is done. We need to make sure that it's working as expected with a live test in Expensify.cash.

[Internal issue](https://github.com/Expensify/Expensify/issues/155147)
[Upwork posting](https://www.upwork.com/jobs/~0178ef13cafb2ddedd)

**Comment by SombreroElGringo** [comment]
Hello,

My solution to this problem is:

- Create a action `markPullRequestsAsDeployed` whose takes the following inputs PR_LIST and IS_PRODUCTION_DEPLOY

- Then loop on the PR_LIST and use the function createComment to write if the PR has been deployed on staging or prod

**Comment by arielgreen** [comment]
@SombreroElGringo, have you applied to the Upwork job as well?

**Comment by SombreroElGringo** [comment]
@arielgreen for this one I need 2 more `connect` before be able to apply on Upwork. Once I got the ˋ4 connects` I will apply on Upwork for this one too.

**Comment by mikeattara** [comment]
**My proposed solution**l:
Check if each pull request is merged to the master or staging branch based on the IS_PRODUCTION_DEPLOY value and write the comment on the issue stating where it has been deployed.

**Comment by roryabraham** [comment]
@mikeattara Your proposal looks good. I'd like to see automated unit tests of the comments, too.

**Comment by mikeattara** [comment]
__Progress Update__ 
 - setup project following the contributor guidelines
 -  install octokit
 - create action metadata file

**Comment by mikeattara** [comment]
__Question__
Do I check if the pull request is merged to master when the IS_PRODUCTION_DEPLOY is true and staging if it is false?

**Comment by roryabraham** [comment]
> Do I check if the pull request is merged to _master_ when the `IS_PRODUCTION_DEPLOY` is true and _staging_ if it is false

No, you shouldn't need to check anything. This action should really be pretty simple ... given these two inputs:

1) `PR_LIST`
2) `IS_PRODUCTION_DEPLOY`

Then it should _always_ comment on every PR in the list.
If `IS_PRODUCTION_DEPLOY`, the comment should be "Deployed to production on `DATE` at `TIME`"
Else, the comment should be "Deployed to staging on `DATE` at `TIME`"

Does that make sense?

**Comment by roryabraham** [comment]
From your proposal:

> Check if each PR is merged to the master or staging branch based on the IS_PRODUCTION_DEPLOY value

That wasn't 100% correct. The action should just trust its `IS_PRODUCTION_DEPLOY` input as the thing that determines if the PR was deployed to staging vs production. No need to deal with `git` or branches at all.

**Comment by mikeattara** [comment]
__Status Update__:
- Making a new pull request

**Comment by mikeattara** [comment]
@arielgreen the PR has been merged
