### ISSUE TITLE
[Chat] / Chrome fails to "Ask" for notification privileges

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/Expensify.cash#1609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  v1.0.1-488 web on Chrome 

**Action Performed (reproducible steps):**

- Navigate to https://expensify.cash/#/signin on web on Chrome browser  
- Click into the padlock in the URL bar and set notifications to `default` (see image below) 
- Reload page
- Sign in
- Sign out via /settings
- Observe that activeClients2 has no value in localStorage whatsoever (see image below)
- Sign in again
- Observe that activeClients2 still has no value
- Leave a comment on a report that is not currently in view from another session as a shared user (this should trigger the prompt to appear)
- Observe that no prompt appears because the notification is skipped and this log displays:
- [LOCAL_NOTIFICATION] Skipping notification because this client is not the leader

**Expected Result:**
The Ask for notifications prompt should display reliably. 

**Actual Result:**
No prompt appears because the notification is skipped because `Skipping notification because this client is not the leader`

**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/62073721/109794506-d41cac00-7c0d-11eb-931f-f72bf7eb157b.png)

![image](https://user-images.githubusercontent.com/62073721/109794589-e72f7c00-7c0d-11eb-8759-09c60b32dd80.png) 

In addition to posting a proposal here, please make sure to submit via this Upwork job too https://www.upwork.com/jobs/~01b3cfaf1cd42f3481

**Comment by SameeraMadushan** [comment]
Hi,

Here is the solution.

In SignInRedirect.js we have to keep current activeClients value remain when user logs out from the system.

In SignIn Redirect.js we can get active clients with this,
```

let activeClients2;

Onyx.connect({
    key: ONYXKEYS.ACTIVE_CLIENTS,
    callback: (val) => {
        activeClients2 = !val ? [] : val;
    },
});

```

then In redirectToSignIn method, we can set active clients after clearing the onyx storage.
```
        if (activeClients) {
            Onyx.set(ONYXKEYS.ACTIVE_CLIENTS, activeClients);
        }
```

**Comment by laurenreidexpensify** [comment]
@tylerkaraszewski @marcaaron @tgolen any comments on @SameeraMadushan's proposal above?

**Comment by tylerkaraszewski** [comment]
I don't have enough background to know if this works, deferring to @tgolen and @marcaaron.

**Comment by tgolen** [comment]
@SameeraMadushan I am a little bit confused about your proposal. I see both `activeClients2` and `activeClients`, but I think they should all be references to `activeClients2`, is that correct? 

I think overall it's a pretty good and simple solution.

I think another possible solution would be to specify a list of keys that _should not_ be cleared out when `Onyx.clear()` is called. These keys could be registered as part of `Onyx.init()` and then a small refactoring of `Onyx.clear()` would be necessary. What are your thoughts on that approach, Marc?

**Comment by SameeraMadushan** [comment]
@tgolen Thanks.
`activeClients2` will be initiate when the first time user loads the page or on a refresh of the page.
When I access `activeClients2` after **clearing the Onyx**, then it will be empty. Because It's pass by reference.
That's why I have to define a new const name as `activeClients` and get the previous value.

**Comment by tgolen** [comment]
OK, thanks for explaining. I think we'll need to work on the naming convention a little bit, but the proposal makes more sense now. 

> I think the onyx library doesn't support defining items that should not clear right?
Seems it's related to the expensify/react-native-onyx library improvement.

That's correct. You'd need to implement a change in that library first and then update the version of `react-native-onyx` in this repo. Still curious for @marcaaron to chime in about that though. I know we've talked about it in the past, but maybe it would be more harmful than good.

**Comment by SameeraMadushan** [comment]
@tgolen Yes, I will change the convention. 😅
Let's get Marc's thoughts as well then. 😃

**Comment by marcaaron** [comment]
>I think another possible solution would be to specify a list of keys that should not be cleared out when Onyx.clear() is called. These keys could be registered as part of Onyx.init() and then a small refactoring of Onyx.clear() would be necessary. What are your thoughts on that approach, Marc?

I think this could be a good future improvement, but not necessarily something we need right now. Looking at the cases where we want to save some data after an `Onyx.clear()` and most of them are conditional anyway. _If_ we have an error, _if_ we have a reportID then persist after the clear etc.

https://github.com/Expensify/Expensify.cash/blob/c3a6aa86d34404599f5239a1dbd84f96505f0e30/src/libs/actions/SignInRedirect.js#L47-L52

This is the only case where we want a key to persist unconditionally so I think we can wait for the optimization.

**Comment by tgolen** [comment]
Cool, thanks Marc. I am fine with that. Let's just use the local variable route to reset the Onyx value after `clear()` then.

**Comment by laurenreidexpensify** [comment]
Great - @tgolen is @SameeraMadushan's proposal good to move forward now?

**Comment by laurenreidexpensify** [comment]
Great @SameeraMadushan can you tag me in the PR when you start it? Thanks!

**Comment by SameeraMadushan** [comment]
@laurenreidexpensify I am about to create the PR now. Could you please send me the contract on Upwork.

**Comment by laurenreidexpensify** [comment]
Done!

**Comment by laurenreidexpensify** [comment]
nice work @SameeraMadushan - we'll issue payment on 18 March if there are no regressions reported 👍🏽
