### ISSUE TITLE
Badge notifications aren't showing when you receive a DM 

### ISSUE THREAD

**Issue by michaelhaxhiu** [Expensify/Expensify.cash#1633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Upwork job post**: https://www.upwork.com/jobs/~0173c5a0ef096b60cc

**Platform - version:**  
- iOS and Android, all versions 
- Tested most recently on Expensify.cash app `V 1.0.1 (465)`

**Action Performed (reproducible steps):**

1. First, I closed the Expensify.Cash mobile app and Expensify.Cash desktop app fully. 
2. Another person direct messaged me a few times.
3. I received the push notifications immediately (for each message), as expected 
<img width=200 src=https://user-images.githubusercontent.com/13206896/109015660-c1452d00-768b-11eb-9527-9f8c3c5b4dee.png>

4. I unlocked my screen

5. I **did not** receive the associated badge notifications for the unread messages (i.e. a red numeric value in top-right of app icon) 
<img width=200 src=https://user-images.githubusercontent.com/13206896/109015862-f3568f00-768b-11eb-9f8c-5133c59c4111.png>

6. When I opened the Expensify Cash mobile app, the messages loaded after a few seconds as expected 
<img width=200 src=https://user-images.githubusercontent.com/13206896/109016234-534d3580-768c-11eb-86a2-eac63f5abd03.png>

**Expected Result:**

Badge notifications should show in the top-right corner of the Expensify.cash app, and enumerate the number of unread direct messages. For example, if I have 3 unread messages, I should see the number `3` as a bad notification on the Expensify.cash app.

**Actual Result:**

Badge notifications are not showing the number of unread messages.

**Notes/Photos/Videos:** 

Screenshots are above. Note this same behavior is reproducible of whether the screen is locked/unlocked. Please make sure the solution works equally for iOS and Android.

**Comment by michaelhaxhiu** [comment]
Upwork job post - https://www.upwork.com/jobs/~0173c5a0ef096b60cc

**Comment by parasharrajat** [comment]
## Proposal
So we can use two small packages `react-native-android-badge` and `react-native-notification-badge` which will help us show the Badges on Android and IOS.

Now using the API from 

https://github.com/Expensify/Expensify.cash/blob/c41b439d3ec1ef4864e01904c87ca3f41f875141/src/libs/Notification/PushNotification/index.native.js#L146-L150

We can hook the setting of the badge and show the badges here.

https://github.com/Expensify/Expensify.cash/blob/c41b439d3ec1ef4864e01904c87ca3f41f875141/src/libs/actions/Report.js#L352-L360

**Comment by AndrewGable** [comment]
I'd be curious if we can solve this without adding a new library and using Urban Airship? https://github.com/urbanairship/react-native-module

**Comment by parasharrajat** [comment]
@AndrewGable  Ah yeah I missed that initially docs are really not helpful.
 
https://github.com/urbanairship/react-native-module/blob/4f31780b11c3a33775a54de3ab1a65ff753e8548/urbanairship-react-native/js/UrbanAirship.ts#L680-L699

says we can use the same for IOS but we still need external lib for Android.

**Comment by AndrewGable** [comment]
Can you please provide an example of the Android badge? The library you mentioned seems to be a wrapper of this library: https://github.com/leolin310148/ShortcutBadger - Which looks quite old and I am not sure it's supported by Android by default, maybe only custom launchers?

@michaelhaxhiu - Can you please double check we want this and it exists for Android?

**Comment by parasharrajat** [comment]
Android does not really have this kind of feature. It recently added only dots and you are correct that lib is really old there are fewer chances that would be helpful.

**Comment by michaelhaxhiu** [comment]
@parasharrajat @AndrewGable good catch!

Let's go with a slightly different solution implementation for **Android** in that case. 

Can we show a badge notification that is simply a dot? These are also called "[dot notifications](https://developer.android.com/training/notify-user/badges)" on Android. It is a similar concept to the iOS solution, but we don't need to quantify the number of notifications shown on Android since that isn't the default behavior.

**Comment by michaelhaxhiu** [comment]
Changing my comment, one moment.

**Comment by michaelhaxhiu** [comment]
@parasharrajat Good catch! 

Android has a similar notification feature actually, but it's not shown the exact same way as iOS (apparently you can see the number of notifications in the[ long-press](https://developer.android.com/training/notify-user/badges) menu on Android). But we haven't implemented that yet, so let's do this instead:

- For the Android solution, let's make sure that the _badge notification_ shows a blue dot if there are unread messages or notifications in Expensify.cash. These are also referred to as "[notification dots](https://developer.android.com/training/notify-user/badges)".

Does that sound good @AndrewGable @parasharrajat? If so, let me know and I'll update the body of the GH issue to clearly state the expectations for iOS vs Android.

**Comment by michaelhaxhiu** [comment]
@parasharrajat did you want to update your solution proposal given my last comment? Just want to make sure we are understanding the full plan.

**Comment by michaelhaxhiu** [comment]
https://docs.airship.com/whats-new/2017-06-21-android-o/

I think Airship should support this too. @parasharrajat Can you please review the link above, and let me know if you think it's something you can accomplish? If so, please update your solution proposal to include a plan for Android notification dots.

**Comment by parasharrajat** [comment]
@michaelhaxhiu. Ah.. Yeah, it is there. I am currently trying to get a push notification on my Android phone. I will update after some time. Thanks.

**Comment by michaelhaxhiu** [comment]
Sounds good @parasharrajat. We'll wait for your follow up here!

**Comment by michaelhaxhiu** [comment]
@parasharrajat My team and I have been discussing this GH the past few days, and we feel this project isn't a good candidate for an External Contributor. 

We are going to solve this internally and close the Upwork job. I appreciate you showing interest and recommend looking at other Expensify Upwork jobs if you want to help with something else.

**Comment by michaelhaxhiu** [comment]
![image](https://user-images.githubusercontent.com/13206896/110484057-b4c7c800-80c0-11eb-8a1d-41653a39cfee.png)
