### ISSUE TITLE
Make entire LHN row clickable

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/Expensify.cash#1661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**
Web/Desktop - v1.0.1-454

**Action Performed (reproducible steps):**

- Place your mouse on a given row in the LHN
- Move your mouse over different parts of the row
- Notice that sometimes the mouse is a cursor (meaning it is clickable) and sometimes it isn't

**Expected Result:**
That as long as your mouse is in the row, you can click it and be taken to the chat.

**Actual Result:**
Only certain parts of the row can be clicked. This is made more obvious by the new zebra highlighting of the row when you hover it. The highlighting makes it feel that clicking will take you to that chat, even though that isn't necessarily the case depending on where your mouse is.

**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/38236554/110370421-05d4af00-8022-11eb-9778-f98f435dd768.mov

https://www.upwork.com/jobs/~017a977a037cf75be4

**Comment by aliabbasmalik8** [comment]
Hi @bfitzexpensify 
It's just padding and height issue.
we need to remove these styling attributes from the top banner and add to the inner row styling object.
```
height: 64,
paddingTop: 12,
paddingRight: 20,
paddingBottom: 12,
paddingLeft: 20,
```
Attached screenshot for better understanding
![image](https://user-images.githubusercontent.com/31027036/110376495-26652f00-804b-11eb-90c8-04e266852b54.png)
![image](https://user-images.githubusercontent.com/31027036/110376525-354be180-804b-11eb-9d21-c0f8c2c594a4.png)

Thanks
