### ISSUE TITLE
Create an Update button in the app's top-bar menu

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/Expensify.cash#1664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Web/Desktop - v1.0.1-454

**Action Performed (reproducible steps):**
- In Expensify/Expensify.cash#1318 we updated the desktop update paradigm. When an update is available, a notification appears (as before). Except now, clicking on the notification opens the UpdateAppModal, which updates and restarts the app.
- However, if the user has notifications disabled, they will never see the update notification and have no way to update the app

**Expected Result:**
- We need users to be able to update, even if they have notifications disabled. On desktop, when an update is available, we need to create an `Update` button in app's top-bar menu — I.e. here:

![image](https://user-images.githubusercontent.com/38236554/110675768-a3a6b600-81a9-11eb-87d5-daa41f313c20.png)

https://www.upwork.com/jobs/~016781e062ce860b84

**Comment by shawnborton** [comment]
@bfitzexpensify is there a mockup for where this button will live?

**Comment by bfitzexpensify** [comment]
Good question, I asked @roryabraham a little while ago but think he's having lunch — Rory, do we have a mockup somewhere or does one need to be created?

**Comment by parasharrajat** [comment]
Yeah, Correct. A mock-up would be good to submit a complete proposal. But as start the Main concept would be as follows:
## Proposal
1. Create the button on the Settings page as per the mockups.
To show the button when the update is available, we will listen to the following Onyx Key.
```
export default withOnyx({
    version: {
        key: ONYXKEYS.UPDATE_VERSION,
        initWithStoredValues: false,
    },
});

```
2. On Press of the Button we have to send a message to the main Process using the
```
ipcRenderer.sendSync('start-update', props.version);
```
Which will start the Update process as it does for closing or submitting the `UpdateAppModal`.

**Comment by roryabraham** [comment]
> Are you looking for the Web platform update as well?

Nope, sorry for the confusion. This is desktop-only.

> To show the button when the update is available, we will listen to the following Onyx Key

That actually won't work because that Onyx key is only set when the update notification is pressed [here](https://github.com/Expensify/Expensify.cash/blob/99a612a2d0f63dbe355e2457e90a386152c41647/src/libs/Notification/LocalNotification/BrowserNotifications.js#L135), but the whole point of adding the button in the settings menu is that it's possible to disable notifications entirely for the desktop client, and if you did that you would then have no way of updating it.

**Comment by parasharrajat** [comment]
Ah sorry, Didn't see this part. So if this is the case. Then We can do is set the key on Onyx if the user has not given the notification permission. Something Like.
```
  pushUpdateAvailableNotification({version}) {
        push({
            title: 'Update available',
            body: 'A new version of Expensify.cash is available!',
            delay: 0,
            onClick: () => {
                Onyx.merge(ONYXKEYS.UPDATE_VERSION, version);
            },
        }).then(((notification) => {
        if(!notification){
        
        Onyx.merge(ONYXKEYS.UPDATE_VERSION, version);
        }
        });
    },
 ```
 updating the push method according. or if throwing the error is not an option.
 
 I see listening on the  `ipcRenderer.on('update-downloaded') ;` would be a repetitive step. As we again need to check the user notification permission and then Set the Onyx Key.

**Comment by Shadows97** [comment]
In order to solve this problem it will be necessary to put in place the update button of the application and define its appearance on two conditions to know according to the platform and the availability of update. So once the update is available it will be displayed.

**Comment by bfitzexpensify** [comment]
cc @nbhargava — ready to go!
