### ISSUE TITLE
[GH Actions] Colorize git diff by character

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/Expensify.cash#1665]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
N/A

**Action Performed (reproducible steps):**
- We have an automation that runs on our PRs that recompiles all our Javascript Github Actions called `verifyGithubActionsBuilds`. This is useful in catching unexpected errors with `ncc` (the library we use to bundle our Node.js scripts with their dependencies), and in preventing developers from forgetting to recompile the scripts.

**Expected Result:**
-  if a diff is found, the diff output should have character-level diff highlighting — but presently, it does not. This makes it difficult to spot differences between the committed script and the recompiled script.

**Actual Result:**
- the diff output does not have character-level diff highlighting. This makes it difficult to spot differences between the committed script and the recompiled script
- Looking at the diff output by `verifyGithubActionsBuilds` can be a useful debugging tool, but it is sometimes very difficult to spot the differences between the the outputted diffs, which wastes time and causes developer headaches. See [this workflow run](https://github.com/Expensify/Expensify.cash/pull/1454/checks?check_run_id=1876184231) for an example of a not-so-useful diff.
**Solution**
- Upgrade the [verifyActions script](https://github.com/Expensify/Expensify.cash/blob/acca7a1dc9ddac7cf4d59e0e1fa373c5d98141b4/.github/scripts/verifyActions.sh) so that it outputs a colored, character-level diff. Something like this:

![image](https://user-images.githubusercontent.com/47436092/109371054-e6869680-7857-11eb-8c16-539dc8be6221.png)

https://www.upwork.com/jobs/~01d11a72b11bec4282

**Comment by roryabraham** [comment]
@mikeattara, can you provide any more detail? How will you ensure that the GH Actions Runner has the correct packages installed? What changes need to be made to the `verifyActions` script to produce a diff?

**Comment by mikeattara** [comment]
@roryabraham I saw he used `diffc` for the image above so updated the proposed solution to use that instead.

The screenshot is attached below
![Screen Shot 2021-03-10 at 6 26 56 AM](https://user-images.githubusercontent.com/31483629/110589298-1d20b300-816e-11eb-89c0-54d58895c2b4.png)

**Comment by FredericoGauz** [comment]
Hi Rory,

My solution is as follows:

[using the bash file]
1 - clone this repository somewhere in the ubuntu machine
2 - `export PATH=/path/to/repo:$PATH`
3 - copy _temporarily_ the lib from this repo to `.github/scripts/lib`
3 - run an updated diff command git (or something more suitable) `diff | diff-so-fancy`

This is a **clean** solution that does not leaves traces and also does not mess up with any other files or diffs. It just runs in the `verifyActions.sh` file and is not persisted in _anyway_!

I already run this in my cloud ubuntu machine with the material I had from previous actions. Please take a look at this screenshot:

![git-diff](https://user-images.githubusercontent.com/18327882/110615034-d61fc700-8147-11eb-9ea3-8f02295efa2a.png)

>Notice: If more then one change is present in the line it will show as only one chunk. If that is not suitable I can try to find a way to make it show character differences also if there is more then one change in line.

**Comment by roryabraham** [comment]
Well at this point it looks like you've converged on the same solution, more or less. Both look acceptable, so I'll go with @FredericoGauz because he got there first (it looks like @mikeattara edited his proposal to use `diff-so-fancy` after @FredericoGauz had already posted his).

**Comment by mikeattara** [comment]
@roryabraham I actually did that, as an alternate solution before that though. I don't really have any problem with you choosing @FredericoGauz but just wanted to clarify

**Comment by mikeattara** [comment]
You can verify from the commits on my fork

**Comment by FredericoGauz** [comment]
Hi @roryabraham  and @bfitzexpensify,

Thank you, I start working on the issue as soon as possible.

**Comment by mallenexpensify** [comment]
@bfitzexpensify was payment ever issued in Upwork for this job? I can't find it.

**Comment by FredericoGauz** [comment]
I don't know if it helps but at least on my side it appears as paid.

2021年8月9日(月) 18:20 Matt Allen ***@***.***>:
