### ISSUE TITLE
[User Settings] Add new Preferences view

### ISSUE THREAD

**Issue by NicMendonca** [Expensify/Expensify.cash#1677]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Having added four new menu items to the Settings page, we now need to begin linking those menu items to actual pages.  This issue pertains to the `Preferences` page. 

The Preferences view will be displayed when the "Preferences" menu item is clicked. It will display a header with a left-facing arrow on the left-hand side, a title, and an `X` button to close the view on the right-hand side. The view will a toggle with the text `Relevant feature updates and Expensify news`.

### Deliverables 

- Clicking on the `Preferences` menu item on the Settings page will route the user to `settings/preferences` the existing preferences in ROUTES.js and display the new view
- The enabled/disabled status of the toggle will depend on the value of the `user.expensifyNewsStatus` key  
    - If the key doesn't exist or is empty, the field should default to true
- Toggling the switch should call `User.setExpensifyNewsStatus`
- Pressing `X` will close the right-hand modal and route the user back to the last viewed report
- Pressing `<` should display the main settings view.

| Mobile  | Web/Desktop |
| ------------- | ------------- |
| <img width="300" alt="" src="https://user-images.githubusercontent.com/16747822/108448293-46f15480-7216-11eb-99ec-4ca56b6e3f27.png"> | <img width="700" alt="" src="https://user-images.githubusercontent.com/16747822/108448116-fe399b80-7215-11eb-8cd3-99a46837f470.png"> |

Job posting: https://www.upwork.com/jobs/~01c4b1365d3b23397b

**Comment by shawnborton** [comment]
@michelle-thompson are you familiar with this screenshot? I am wondering if it should have some kind of small label above the toggle control to indicate that this toggle is for "Notifications"

**Comment by michelle-thompson** [comment]
Perhaps we should just update the toggle copy? 
![image](https://user-images.githubusercontent.com/43361905/110504849-6c091280-80b2-11eb-8ff1-94b12c6fc5fb.png)

**Comment by mikeattara** [comment]
__Proposed solution__
- Add `PREFERENCE` route in `src/ROUTES.js`
- Create _Preferences_ page
- Toggle status based on `user.expensifyNewsStatus` specification

**Comment by Maftalion** [comment]
**Proposed Solution**
- RN's Switch component, behaves different on different platform (screenshot below for android/web). So we can bring in a javascript implementation like https://github.com/Expensify/Expensify.cash/pull/1672 to have design parity across all platforms.
- The default will go based on `expensifyNewsStatus` or default to true, then toggles will update that value by calling `setExpensifyNewsStatus`.

**Questions**
`Pressing X or < should display the main settings view.`
- Current functionality would go back to main when < is pressed and close completely when x is pressed. Do we want to keep that or should both go back to main settings? (if so it might make more sense to just hide the x)

**Comment by NikkiWines** [comment]
> Current functionality would go back to main when < is pressed and close completely when x is pressed. Do we want to keep that or should both go back to main settings? (if so it might make more sense to just hide the x)

Ah, yeah let's keep current functionality here. I've updated the OP to reflect that pressing `<` will take you to the Settings page but pressing `x` will close the modal entirely.

**Comment by Maftalion** [comment]
@shawnborton do you have any opinion on whether the switch should be consistent across all platforms or if it should use the native components? here's a screenshot of how it would look on android/web/desktop:
<img width="127" alt="Screen Shot 2021-03-09 at 9 41 59 AM" src="https://user-images.githubusercontent.com/12075600/110550209-17808a00-80e8-11eb-9383-f7276ae9505c.png">

If we want every platform to look the same as the screenshots in the description then I can bring in a library that is a pure JS implementation and looks the same across all platforms: https://github.com/aminebenkeroum/toggle-switch-react-native

**Comment by shawnborton** [comment]
I like the idea of being able to use the same switch everywhere, regardless of platform. We have to create a switch for web/desktop anyways, so it would be nice to reuse the same thing everywhere.
