### ISSUE TITLE
[GH Actions] Request review of automerge PR if there is a merge conflict

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

# Problem
Typically, PRs that have the `automerge` label don't need to be manually reviewed by anyone. In those cases, we don't want to request a review. However, since we'll be using `automerge` PRs to CP PRs to staging and/or production, we'll have more cases where it can't be automatically merged because of a merge conflict. In these cases, we need to request a reviewer on the PR so that the reviewer can manually resolve the merge conflict.

# Why is this important?
This will be a pre-requisite of our Expensify.cash CP flows.

# Solution
If [this step](https://github.com/Expensify/Expensify.cash/blob/71d00f2e3e10225ff0f335b90175065d181cc6f3/.github/workflows/automerge.yml#L29-L33) of the `automerge` workflow exits with a nonzero exit code, add `pullerbear` as a reviewer on the PR.

**Apply to this posting on Upwork**: https://www.upwork.com/jobs/~01977821838810f422
https://github.com/Expensify/Expensify/issues/155154

**Comment by mikeattara** [comment]
__Proposed solution__
To determine the [mergeability of the PR](https://docs.github.com/en/rest/reference/pulls#mergability), the `mergeable` field on the PR is a Boolean that indicates if the branch can be merged, and `mergeable_state` will indicate if it's `clean`, `dirty`, or `unstable`. So, I will improve the `automerge` workflow by checking if the PR is mergeable, and merge or request a review.
The [Status API](https://docs.github.com/en/rest/reference/repos#statuses) can also be used to mark a commit on the PR that will be used to request for manual review.

**Comment by mikeattara** [comment]
Also add `id` for [this step](https://github.com/Expensify/Expensify.cash/blob/71d00f2e3e10225ff0f335b90175065d181cc6f3/.github/workflows/automerge.yml#L29-L33) so that I can check the `exitcode` of the step to add `pullbear` as reiewer or not like [this](https://github.community/t/using-exit-code-of-previous-step/16798)

**Comment by roryabraham** [comment]
@mikeattara I like your first solution that checks the `mergeable` field! Proposal looks good, but just for clarity the correct actor is `Expensify/pullerbear`, not `pullbear`

**Comment by mikeattara** [comment]
Alright. Thanks for the clarification @roryabraham

**Comment by arielgreen** [comment]
Sending over an offer in Upwork now, @mikeattara .

**Comment by mikeattara** [comment]
Thanks. @arielgreen

**Comment by mikeattara** [comment]
__Question__
How are *reviews* requested on *pull requests* at the moment?
Is it being handled by any *workflow*?
