### ISSUE TITLE
Clicking rapidly on the Backdrop, while the new chat Menu is open, toggles between on and Off state.

### ISSUE THREAD

**Issue by parasharrajat** [Expensify/Expensify.cash#1722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
Platform - version: **Web v1.0.2-27**

## Expected Result:
Clicking out on the backdrop area should close the New chat Fab Modal at once. 

## Actual Result:
Clicking rapidly on the Backdrop, while the new chat Menu is open, toggles between on and Off state.

https://user-images.githubusercontent.com/24370807/110588136-9df5a400-819a-11eb-828f-343d138e8335.mp4

## Action Performed:
1. Click on the Sidebar Fab button.
2. Now click once on the backdrop area to close the Menu. But while the menu is closing(during animation state), click rapidly on the backdrop, the Menu toggles between open and close state.

## Workaround:
This is not affecting the main functionality of the App but it is a bug.

cc @roryabraham @marcaaron

**Comment by parasharrajat** [comment]
### Reason
Due to we are using a toggle method that is being triggered on each click on the backdrop, the modal state toggles between on and off.

### Fix for above mentioned issue
1. Add a parameter to this function, like this
https://github.com/Expensify/Expensify.cash/blob/9aefbc575247a9a715ea28d3e49a7d9b22f7c047/src/pages/home/sidebar/SidebarScreen.js#L86-L89
``` 
      toggleCreateMenu(isOpen) {
        console.debug('fab pressed', isOpen);

        // Prevent from possibly toggling the create menu with the sidebar hidden
        if (!this.props.isSidebarShown) {
            return;
        }
        this.setState(state => ({
            isCreateMenuActive: typeof isOpen === 'boolean' ? isOpen : !state.isCreateMenuActive,
        }));
    }
``` 
Then modify the code here

https://github.com/Expensify/Expensify.cash/blob/9aefbc575247a9a715ea28d3e49a7d9b22f7c047/src/pages/home/sidebar/SidebarScreen.js#L166-L176
```
                                  <FAB
                                    isActive={this.state.isCreateMenuActive}
                                    onPress={() => this.toggleCreateMenu(true)}
                                />
                            </View>
                            <CreateMenu
                                onClose={() => this.toggleCreateMenu(false)}
                                isVisible={this.state.isCreateMenuActive}
                                onItemSelected={this.onCreateMenuItemSelected}
                            />

**Comment by marcaaron** [comment]
I might be missing something about how likely people will be effected by this... but I'm not sure there is much value in fixing this right now 🤔 

We are changing the way that modals like the Search page when adopting `react-navigation` and also removing the `isSidebarShown` concept very soon.

**Comment by parasharrajat** [comment]
@marcaaron  Ok. Will close it.
