### ISSUE TITLE
Pinning icon is not well aligned.

### ISSUE THREAD

**Issue by parasharrajat** [Expensify/Expensify.cash#1728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
Pin icon on the sidebar is not aligned correctly.  Suspected PR https://github.com/Expensify/Expensify.cash/pull/1721

## Action Performed:
 Pina chat and see the Sidebar

## Platform:
Where is this issue occurring?

 Web
 
![image](https://user-images.githubusercontent.com/24370807/110842599-4e63c500-82cd-11eb-8cd0-1f2c8bce9aee.png)
#1728 
cc @roryabraham

**Comment by parasharrajat** [comment]
I think we should merge the `TouchableOpacity` and upper `View` into `TouchableOpacity`.
https://github.com/Expensify/Expensify.cash/blob/6e86f75f687bac0d88dbc09a7d7d8832d87c108b/src/pages/home/sidebar/OptionRow.js#L71-L89

**Comment by roryabraham** [comment]
Seems reasonable to me, thanks for reporting @parasharrajat. @aliabbasmalik8, since [your PR](https://github.com/Expensify/Expensify.cash/pull/1721) likely caused this regression, do you want to submit a PR to fix it?

**Comment by aliabbasmalik8** [comment]
@roryabraham sure, I'll fix it.

**Comment by shawnborton** [comment]
Just a heads up that the PR did not actually fix the issue - the entire row is not clickable. Left a comment over here: https://github.com/Expensify/Expensify.cash/pull/1737#issuecomment-800598974

**Comment by parasharrajat** [comment]
@shawnborton I think https://github.com/Expensify/Expensify.cash/issues/1728#issuecomment-796987224 has a point.

**Comment by aliabbasmalik8** [comment]
@shawnborton I'm on it
