### ISSUE TITLE
IOUModal View Issue

### ISSUE THREAD

**Issue by tugbadogan** [Expensify/Expensify.cash#1769]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

IOUModal view does not show chat view.

## Expected Result:
Chat view should be visible when user is redirected to `/iou/request` page.

<img width="400" alt="Screenshot 2021-03-14 at 19 51 59" src="https://user-images.githubusercontent.com/3853003/111082178-d2e95a00-84fe-11eb-80f2-96641610800b.png">

Page header should have some margin from top.

<img width="200" src="https://user-images.githubusercontent.com/3853003/111082261-3d01ff00-84ff-11eb-9803-b00a3c1c4c1d.png">

## Actual Result:
IOU Modal view is shown on the right sidebar, but the background is solid gray instead of chat view. In addition, close button doesn't work.

<img width="500" alt="Screenshot 2021-03-14 at 19 43 02" src="https://user-images.githubusercontent.com/3853003/111082208-fad8bd80-84fe-11eb-9d41-ecef8ec27e7c.png">

Page header is overlapping with iOS status bar and close/back buttons don't work.

<img width="200" src="https://user-images.githubusercontent.com/3853003/111082306-7470ab80-84ff-11eb-8116-e473a2ac5d2c.png">

## Action Performed:
1. Login to expensify cash
2. Replace http://localhost:8080/ with http://localhost:8080/iou/request

## Platform:
Where is this issue occurring?

- [X] Web
- [X] iOS
- [?]  Android
- [?] Desktop App
- [X] Mobile Web

 
**Version Number:** v1.0.2-49

**Comment by Julesssss** [comment]
Thanks for raising this, it was most likely caused by the recent [React Native Navigation PR](https://github.com/Expensify/Expensify.cash/pull/1559)
