### ISSUE TITLE
Update the UpdateAppModal for easier visibility

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#1853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Expected Result:
When a new update happens, the modal that appears should be non-invasive and modern looking, like this:

![image](https://user-images.githubusercontent.com/59587260/111553665-ba708c80-87e9-11eb-8249-998109b5e394.png)

## Actual Result:

The current modal is clunky and hard to digest, and the button looks humungous:

![image](https://user-images.githubusercontent.com/59587260/111553710-cf4d2000-87e9-11eb-94ce-78840a6bf4a8.png)

## Action Performed:

1. Log into Expensify.cash
2. Wait for an update to be deployed
3. Observe the modal that appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes, this is a style update that does not majorly impact the functionality of the site.

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web
 
**Version Number:** Not applicable
**Logs:** Not Applicable
**Notes/Photos/Videos:** Not applicable

**Comment by kadiealexander** [comment]
Upwork post:

https://www.upwork.com/jobs/~01b6adc982355988c0

**Comment by bilalyaqoob** [comment]
The issue is with the width of modal and also need to add the cancel button to again hide and cancel the popup.

**Comment by shahkeel** [comment]
The issue is with the width of the modal we need to reduce the width based on dimensions of window and also need to add the cancel button to again hide and cancel the popup.

**Comment by shahkeel** [comment]
Proposal:

The width of the modal is not correct we need to reduce the width based on dimensions of window and also need to add the cancel button to again hide and cancel the popup.

First import this
import { Dimensions } from 'react-native'

then give this to the width of modal
width: Dimensions.get('window').width/3,

and also add the cancel btn

**Comment by npsedhain** [comment]
Hi @kadiealexander, I would love to work on this issue! 

I propose to do the following: 

1. Discard `HeaderWithClose` component currently used, and use `Header` component instead (this also removes the border underneath). 
2. Add a `Cancel` button below the `Update App` button.
3. Increase the border radius of the modal container using `modelContainerStyle`. 
4. Use existing props from `withDimensions` to figure out the height and width - we have to decrease the width primarily as per the new design.

Questions: 

1. Do we have a Figma file or specification already available for the height and width of the modal? Like the percentage of the total screen width?

**Comment by SameeraMadushan** [comment]
Working on this proposal

**Comment by roryabraham** [comment]
@SameeraMadushan, your proposal looks good. My only early piece of feedback is that the new generic modal type should just be called `CONFIRM` rather than `CENTER_MIDDLE`.

**Comment by SameeraMadushan** [comment]
@roryabraham Sure. I will change the type to `CONFIRM` 🙂

**Comment by SameeraMadushan** [comment]
@kadiealexander  Let me know if I'm good to go with the PR.

**Comment by kadiealexander** [comment]
Hey @SameeraMadushan! Sorry, we had an internal hiccup that prevented me from moving forward before the weekend. I've just accepted your proposal in Upwork, please go ahead!

**Comment by SameeraMadushan** [comment]
That's fine @kadiealexander. I will start working on it. Thanks.
