### ISSUE TITLE
[Chat] Swipe to close keyboard on iOS

### ISSUE THREAD

**Issue by NicMendonca** [Expensify/Expensify.cash#1870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Expected Result:
Swipe collapses the keyboard, by dragging your thumb from the message window to the keyboard.

## Actual Result:
Swipe to close keyboard is not a supported gesture.

## Action Performed:

- Tap into a chat
- Tap in the comment box
- Notice keyboard is now open
- Attempt to swipe down to close keyboard
- Notice keyboard doesn't close

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
iOS
 

**Notes/Photos/Videos:** 

![image](https://user-images.githubusercontent.com/24947345/111700835-5a411100-8810-11eb-9964-047e1b065d63.png)

Upwork job posting: https://www.upwork.com/jobs/~0104d324e7e78c07ea

**Comment by OnlineSmileDev** [comment]
@NicMendonca I fixed the above issues with adding ScrollView to your total component.
And we have to give the keyboardShouldPersistTaps='handled' permission to ScrollView.

<ScrollView contentContainerStyle={{flexGrow: 1}}
  keyboardShouldPersistTaps='handled'
>
  <TextInput />
</ScrollView>

**Comment by barun1997** [comment]
Hi @NicMendonca! 

I would love to work on the issue!

I did a bit of research and have two solutions for this: 

**Solution 1:** 

1. Wrap `ReportActionCompose` with a `ScrollView` and use `keyboardDismissMode` to dismiss the keyboard in response to a drag. iOS has 'interactive' which dismisses the keyboard interactively. 
2. Wrap the` ScrollView `around a `View` to remove extra padding 

During the testing phase, I faced the problem of the ReportActionCompose component bouncing while scrolling, so I will have to spend more time figuring out this solution. 

**Solution 2:** 

1. Use `PanGestureHandler` from `react-native-gesture-handler` to wrap the above component and dismiss the keyboard using Keyboard.dismiss() whenever a gesture event is registered. 

We will have to install `react-native-gesture-handler` package for this solution. 


I implemented the solution below using the second option: 

https://user-images.githubusercontent.com/19339044/111713243-51375a80-8877-11eb-944f-08ad66884f68.mov

**Comment by wildanmuhlis2** [comment]
Hi,

I've applied for the Upwork job.

My proposed solution:

Attach PanResponder to ReportActionCompose component and make the PanResponder and the Textinput coexist so that a tap will focus on the TextInput and a swipe will still trigger the PanResponder callbacks.

**Comment by marcaaron** [comment]
@barun1997 The PanResponder solution sounds preferable. Could we  perhaps design this in a way so that any element could be wrapped with something like `SwipeableView` and have an `onSwipeDown` prop?

```jsx
<SwipeableView
    onSwipeDown={() => Keyboard.dismiss()}
>
   <SomeOtherComponent />
</SwipeableView>
```

**Comment by barun1997** [comment]
@marcaaron Of course! Will do. I am guessing, we pass `onSwipeDown` as a prop to the component as well?

**Comment by marcaaron** [comment]
Right, it would be fired whenever we swipe down, but will be a callback function.

**Comment by barun1997** [comment]
Great, gotcha @marcaaron ! Am I good to go with working for the PR on the issue?

**Comment by kaushiktd** [comment]
Hi,

This is Kaushik here and I would like to suggest a simple and effective explanation for this,

  1.  it will be handle by adding keyboardShouldPersistTaps='handled' to scroll view.

**Comment by marcaaron** [comment]
Just merged this but the issue did not close I think it should have?
