### ISSUE TITLE
LHN background color is not correct.

### ISSUE THREAD

**Issue by parasharrajat** [Expensify/Expensify.cash#1967]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
There are a couple of styling issues. 

- [ ] LHN Bg color.
- [ ] LHN Chat hover style.

## Expected Result:

![Screenshot_2021-03-20 Expensify cash - Chat with friends to send and receive money](https://user-images.githubusercontent.com/24370807/111876954-04629980-89c7-11eb-8f91-dadc568fb061.png)

## Actual Result:
![Screenshot_2021-03-20 Expensify cash - Chat with friends to send and receive money(1)](https://user-images.githubusercontent.com/24370807/111876959-0a587a80-89c7-11eb-9896-4e92b575909c.png)

## Platform:

 Web
 iOS
 Android
 Desktop App
 Mobile Web

**Comment by parasharrajat** [comment]
@shawnborton I think due to migration to the `react-navigation` we missed this. I noticed when hovering over the row there was no effect on the LHN. Please confirm if this is legit. I have PR ready to fix this.

**Comment by shawnborton** [comment]
Good catch @parasharrajat! You are correct, your bug is legit. For your PR, you might also want to make sure the color of the LHN matches the color of the status bar on iOS - I vaguely recall there being a small discrepancy there.

**Comment by parasharrajat** [comment]
Ok.

**Comment by shawnborton** [comment]
Yes, but think of it the other way around - the status bar should match the LHN (`gray1`). Then when we navigate to a chat, the status bar should match the background color of a chat (white).

**Comment by parasharrajat** [comment]
Oh yeah. Sure.
