### ISSUE TITLE
Updates to validation check messaging when inviting email/phone numbers

### ISSUE THREAD

**Issue by puneetlath** [Expensify/Expensify.cash#1968]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Current 
Right now, when start a chat with a new user who you've never chatted with before, and you enter only letters this is what you see. 
![image](https://user-images.githubusercontent.com/1371996/111914553-74f9cc80-8a40-11eb-86de-0e949c3602be.png)
This shows until you enter a valid email format, at which point you see this. 
![image](https://user-images.githubusercontent.com/1371996/111914597-98bd1280-8a40-11eb-85c2-b854bbf6c9ab.png)

Alternatively, if you enter just numbers, this is what you see from the start. 
![image](https://user-images.githubusercontent.com/1371996/111914625-ac687900-8a40-11eb-94e8-f7091db7482c.png)

Unless you enter a number starting with 0, in which case you see this. 
![image](https://user-images.githubusercontent.com/1371996/111914643-c2763980-8a40-11eb-881e-54a4a412ce11.png)

## New
Instead of this, here's how we'd like it to work: 

1. Remove the feedback message "Don't see who you're looking for? Type their email or phone number to invite them to chat."
2. When typing, if the input does not match a valid email or phone number format then show the what they've typed below, but greyed out and unselectable.
3. Once the input matches a valid email or phone number format then show the option as selectable (as we do today)
4. If the input is only numbers *and* begins with 0, then display message `Please enter a phone number including the country code e.g +447814266907`

Internal issue: https://github.com/Expensify/Expensify/issues/154200
Upwork job: https://www.upwork.com/jobs/~01c64a96ae738dcc05

**Comment by muhammadzaman0510** [comment]
This is how I'll fix the issue.

- I will search for those message where those are implemented in code
- Will change the implementation so that instead of showing those message I will pass the updated text whatever is written in text input by the user as explained in job
- For digits I will change the message as explained in job, I believe code already differentiating between string and digits so I only need to update the message there.
- At the end I will verify the happy path when match is found so it should be clickable and for not found it should be grey.

**Comment by umarsalahudin** [comment]
#Quick Fix

- Review the code carefully and remove the feedback message.
- Make the selectable field border grey and unselectable until the correct email and number is enetered
- Show the field selectable or optional (add green border) if the email is correct.
- Also for digit show the message "Please enter a phone number including the country code e.g +447814266907" if it begins with 0.

**Comment by jwh315** [comment]
I can see that the `Don't see who you are looking for...` error message is defined in a [constant here](https://github.com/Expensify/Expensify.cash/blob/4bc32214cd2158a02053da8bf6c3619ad3505d63/src/CONST.js#L58). 

This constant is referenced in a [helper function](https://github.com/Expensify/Expensify.cash/blob/3431bf0b59f531bee31cee0f9e11e6fc1ad12bcf/src/libs/OptionsListUtils.js#L413) that is used from 3 areas of the application. One of those areas is the [NewChatPage](https://github.com/Expensify/Expensify.cash/blob/3431bf0b59f531bee31cee0f9e11e6fc1ad12bcf/src/pages/NewChatPage.js#L108). 

All three references to this helper method are being called as an attribute for the `OptionsSelector` component. My initial thought, to maintain consistency. I will need to implement the new phone number error message as a constant in the constants object and update the helper method accordingly. The UI updates to show the user's currently typed text as unselectable will likely be done in the `OptionsSelector` component, if the functionality is not already available in that component.

**Comment by SameeraMadushan** [comment]
Working on the proposal.

**Comment by johndev0711** [comment]
Hello. This is John.
I've solved the issues simply and perfectly.
The solutions are as following:
It needs to modifying for mainly only one file. ( getHeaderMessage in OptionsListUtils.js, )
In a word, we have to add the props-searchValue in the getHeaderMessage function and modify the function comments.
![image](https://user-images.githubusercontent.com/74647446/112455350-eb0c7500-8d59-11eb-8477-048ed9c5593f.png)
By modifying the only four line code, I've fixed all issues.
1. **1.Remove the feedback message "Don't see who you're looking for? Type their email or phone number to invite them to chat."**
2. **When typing, if the input does not match a valid email or phone number format then show the what they've typed below, but greyed out and unselectable.**
3. **Once the input matches a valid email or phone number format then show the option as selectable (as we do today)**
4. **If the input is only numbers and begins with 0, then display message Please enter a phone number including the country code e.g +447814266907**

Thanks.

**Comment by kaushiktd** [comment]
Hi,

This is Kaushik here. I would like to put a technical and pretty self explanatory solution for this 

 1.  Remove the feedback message "Don't see who you're looking for? Type their email or phone number to invite them to chat."
    2.  When typing, if the input does not match a valid email or phone number format then show what they've typed below, but greyed out and unselectable.
    3.  Once the input matches a valid email or phone number format then show the option as selectable (as we do today)
    4.  If the input only numbers and begins with 0, then display message Please enter a phone number including the country code e.g +447814266907
