### ISSUE TITLE
[Pay on Thursday 27th May] [IOU] Create Currency Modal, with geolocation and Location permissions

### ISSUE THREAD

**Issue by jliexpensify** [Expensify/Expensify.cash#1970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Context

This issue builds on top of the existing IOU Modal, which was implemented [in this PR](https://github.com/Expensify/Expensify.cash/pull/1561). The `IOU Amount` step page has already [been created](https://github.com/Expensify/Expensify.cash/blob/master/src/pages/iou/steps/IOUAmountPage.js) and is a controlled component ([IOUModal](https://github.com/Expensify/Expensify.cash/blob/fa6185b2c51fdc0f28ab9cbc48b8a306f64a537d/src/pages/iou/IOUModal.js#L194-L198) manages its state). The amount step allows users to select the IOU request or bill split amount, depending on how they launched the Modal. 

We now seek to extend functionality. We want to use a Geolocation library and an existing API to detect the users preferred currency, allowing them to change it manually, too. We also need to implement a permissions library to request location permission from the user if they decide to change their currency, as we will then seek to detect it automatically from then on.

To open the Modal, you can navigate to `localhost:8080/iou/request` AND `localhost:8080/iou/split`.

You can also launch the IOUModal by temporarily modifying the routes in CreateMenu. Launch the request money flow with `Navigation.navigate(ROUTES.IOU_REQUEST)` and the bill split flow with `Navigation.navigate(ROUTES.IOU_BILL)`

**Mobile & mobile web**
![Currency Selector - Mobile](https://user-images.githubusercontent.com/10736861/111804442-009c1d80-88c8-11eb-8cdf-80a04da0e1ed.png)

**Web & Desktop**
![Currency Selector - Desktop (1)](https://user-images.githubusercontent.com/10736861/111804482-085bc200-88c8-11eb-9ed4-3a94bb6b5fee.png)

**Deliverables:**

1. Create a new API.js function for calling our `GetPreferredCurrency` API and another for calling `GetCurrencyList`. Details at the bottom of this post.
2. Add the [react-native-geolocation](https://github.com/react-native-geolocation/react-native-geolocation#getcurrentposition) and [react-native-permissions](https://github.com/zoontek/react-native-permissions) libraries to the project.
3. We should create a new function within the [PersonalDetails.js Action](https://github.com/Expensify/Expensify.cash/blob/master/src/libs/actions/PersonalDetails.js) which calls the new `GetPreferredCurrency` API.js function
    1. If the location permission has already been granted, we will get lat and lon from getCurrentPosition and pass the params to `GetPreferredCurrency`, else we ignore those query params (as they are optional)
    2. We should then call `GetCurrencyList` matching the currency we received from the previous request to get the correct symbol for that currency. (the full currency list should also be persisted to Onyx via a new key: `currencyList`)
    3. We then persist both the `preferredCurrencyCode` AND `preferredCurrencySymbol` data in Onyx, similar to [how we store the users timezone](https://github.com/Expensify/Expensify.cash/blob/dbb40b9ea4358ea8a0d192a72d1fd232169bcc8c/src/libs/actions/PersonalDetails.js#L113-L114)
3. When the IOUModal is opened, we should subscribe to the `MY_PERSONAL_DETAILS` Onyx key:
    1. We take updated values of `preferredCurrencySymbol` and `preferredCurrencyCode`, setting IOUModal props for both of these (`currencySelected` prop should be deleted,  `selectedCurrency` should be modified to be of type Object: `selectedCurrency: { currencyCode: String, currencySymbol: String }`)
    2. The currency Text component should be updated with `this.props.selectedCurrency.currencySymbol` 
4. When the currency symbol is tapped, a CurrencyModal should be displayed. This is a new Modal which needs the following functionality:
    1.  The Modal should follow the structure of our existing Modals
    2. Retrieve all currencies from `GetCurrencyList` via another new Action function and again persisting this data to Onyx under the `currencyList` key.
    3. using the above data, we should display all currencies to the user in a FlatList, using a new [OptionsListUtils](https://github.com/Expensify/Expensify.cash/blob/master/src/libs/OptionsListUtils.js) variant 
    4. If the user makes a currency selection then we should pass this value back to the IOUModal via a callback and update the `preferredCurrencyCode` AND `preferredCurrencySymbol` Onyx data
    5. The modal should then close, returning the user to the IOUAmount step, with the updated currency symbol

**GetPreferredCurrency API**
Example of the API which is used to retrieve the users preferred currency
```
https://www.expensify.com/api?command=GetPreferredCurrency&latitude=0.01&longitude=-1.44
latitude - optional param
longitude - optional param

// Response
{
  "currency": "GBP",
  "jsonCode": 200,
  "requestID": "0uBdrX"
}
```

**GetCurrencyList API**
Example of the API which returns all supported currency and symbol parings
```
https://www.expensify.com/api?command=Mobile_GetConstants&data=[%22currencyList%22]

// Response
{
  "currencyList": "{"AED":{"symbol":"Dhs","name":"UAE Dirham","ISO4217":"784"},"AFN":{"symbol":"Af","name":"Afghan Afghani","ISO4217":"971"},"ALL":{"symbol":"ALL","name":"Albanian
	...
  }}",
  "jsonCode": 200,
  "requestID": "wjy42x"
}
```

## Upwork Issue: https://www.upwork.com/ab/applicants/1373765458169090048/job-details

**Comment by rameshhpathak** [comment]
Hi, I would love to work on this issue! 


### My proposal:    

1. I will create a new API.js function for calling `GetPreferredCurrency` and another for calling `GetCurrencyList `

2. Install the `react-native-geolocation `as well as `react-native-permissions` libraries to the project. 

3. Create a new function within the `PersonalDetails.js` action which calls `GetPreferredCurrency` API.js function.   

    i. If the location permission has already been granted, we will then use` geolocation.getCurrentPosition(geo_success,[geo_error], [geo_options])` from the` react-native-geolocation` library to get lat and long and will pass these to `GetPreferredCurrency`, or else we will ignore lat and long query parameters.
    
    ii. Or else, use the `react-native-permissions` library to request the location permission from the user.

**Comment by Julesssss** [comment]
Hi @rameshhpathak -- thanks for your proposal. 

> Should we use SectionList instead of a FlatList — similar to how I think OptionsList is implemented?

Nice spot. Yeah, that would be preferred.

**Comment by rameshhpathak** [comment]
Got it. Thanks.  Also, have submitted the proposal on job posting under the name Ramesh Pathak.

**Comment by iwiznia** [comment]
Is this being worked on? I can't find a PR for this.

**Comment by rameshhpathak** [comment]
Hi @iwiznia yeah, I will be submitting PR first thing tomorrow as I'm almost done.

**Comment by kadiealexander** [comment]
Hi @rameshhpathak, how are you getting on with this one? Just as an FYI, the deadline for these issues is typically 7 days from when it's assigned. 😊

**Comment by rameshhpathak** [comment]
@kadiealexander Hi, sorry! I am resolving the outstanding issues within next half an hour!

**Comment by trjExpensify** [comment]
Paid, thanks Ramesh!
