### ISSUE TITLE
Expand swipe area for navigating between screens

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/Expensify.cash#2025]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Expected Result:
Ideally you could swipe either all or most of the screen to navigate backwards/forwards from the LHN to the chat. 

## Actual Result:
The swipe area is like a single pixel right on the edge.

## Action Performed:
1. Open a chat
2. Try to swipe back to the LHN
3. Notice you have to grab the *very* edge of the screen to swipe.

## Workaround:
Yes, you can still swipe. 

## Platform:
iOS

**Version Number:** iOS - v1.0.5-5
**Notes/Photos/Videos:** We can use `gestureResponseDistance` [here](https://reactnavigation.org/docs/stack-navigator/#gestureresponsedistance) and the default distance for horizontal direction of 50 pixels.
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/157460
**Upwork link:** https://www.upwork.com/jobs/~01c070188386b953ec

**Comment by tugbadogan** [comment]
Hi,

I would like to work on this issue. Here is my proposal:

I'm going to add `edgeWith={50}` prop to `Drawer.Navigator` in `MainDrawerNavigator` component.

https://github.com/Expensify/Expensify.cash/blob/87c154059813dd0994686cc8e83b77a62e076be8/src/libs/Navigation/AppNavigator/MainDrawerNavigator.js#L20-L25

This is how swipe gesture works for drawer navigator. I think it's different from Stack navigator, so we don't need to use `gestureResponseDistance` here.
https://reactnavigation.org/docs/4.x/drawer-navigator/#drawernavigatorconfig

**Comment by marcaaron** [comment]
Just took a look at the docs and that makes sense to me @tugbadogan (also we are on react-navigation v5)
https://reactnavigation.org/docs/drawer-navigator/#edgewidth

**Comment by tugbadogan** [comment]
Thanks for the offer, I will send the PR soon. I'm planning to set `edgeWidth` to 500. Is that OK?

**Comment by tylerkaraszewski** [comment]
Thanks @marcaaron!
