### ISSUE TITLE
[User Settings] Allow users to add secondary logins 

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#2029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

With the new Settings > Profile page having been added, we need to add some new functionality: Allowing users to add new secondary logins.

### Deliverables 
- **Logins (Email and Phone Number):**
    - Get the `loginList` from the `user` onyx key and determine if the user has any secondary logins that we should display 
         - If the primary login is an email address, we want to display a phone login if one exists 
         - If the primary login is a phone number, we want to display an email address if one exists
    - If no secondary login exists, ensure there is an `Add` button next to the requisite field. 
        - When this button is clicked we should display a text field for the user to enter their password. 
        - Once the password has been entered we should call `User.addSecondaryLogin`
    - If a secondary login exists but is not validated, show a `Resend` button next to the text field. Clicking on this button should call `User.resendValidateCode` 
    - If a secondary login exists and is validated, ensure the field is locked.
         - If the user has multiple validated secondary logins, choose the first one from the list.
    - The phone number field should have a note beneath it, which changes depending on the status of the phone login
        - **Non-Existant:** `Add your phone number to settle up via Venmo.`
        - **Unvalidated:** `The number has not yet been validated. Click the button to resend the validation link via text.`
        - **Validated:** `Use your phone number to settle up via Venmo.`

**Mobile**

| No Phone Number  | Add Phone Number | Password Prompt | Unvalidated Phone Number | Validated Phone Number
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575516-5385b380-72cf-11eb-9e4e-ac55dccdc56b.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575544-744e0900-72cf-11eb-9786-5d8faedd7f20.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575585-9d6e9980-72cf-11eb-918c-de67dd0a4553.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575629-bc6d2b80-72cf-11eb-8942-d65f198414f2.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575652-c98a1a80-72cf-11eb-8eaf-c25c53f7f722.png"> | 

**Web**: should follow the same flow as mobile and looks the same except the view is within a right-hand-modal 
eg. **Unvalidated Phone on Web:** 
<img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575785-3bfafa80-72d0-11eb-9984-39e493387db8.png">

**Mobile flow with Email as Secondary Login:**
| No Email  | Add Email | Password Prompt | Unvalidated Email | Validated Email |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575876-7d8ba580-72d0-11eb-8f33-f54d80e367ad.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575895-8a0ffe00-72d0-11eb-9dff-f360b53f6949.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575585-9d6e9980-72cf-11eb-918c-de67dd0a4553.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575924-9b590a80-72d0-11eb-91ee-5daf87b387a6.png"> | <img width="400" alt="" src="https://user-images.githubusercontent.com/16747822/108575652-c98a1a80-72cf-11eb-8eaf-c25c53f7f722.png"> | 

## Platform:
Where is this issue occurring?

- [x] Web
- [x]  iOS
- [x]  Android
- [x]  Desktop App
- [x]  Mobile Web

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/154988

**Comment by kadiealexander** [comment]
Upwork link: https://www.upwork.com/jobs/~01de860349951ca871

**Comment by Regaron** [comment]
Hi, I applied for the job in Upwork. Let me know if I can work on this issue.

Here’s how I will approach this issue: 

1. I will get the `loginList` from `Onyx` using the user key. This will give us login lists, so we can find if we have any secondary logins that we could display. 



	loginList is an array `[ { partnerName: ‘…’, partnerUserId: ‘…’, validatedDate: ‘’}]`

2. Through the login list, if the email address is primary, we want to display a phone login as secondary if it exists


3. Similarly, if the phone number is primary login, we want to display an email address as secondary if it exists


4. If no secondary login exists, I will add a `TextInputWithFocus` field and an Add button next to the field 



      I. When the button is clicked, we will take the user to PasswordPrompt where they will enter the password using the same `TextInputWithFocus` component

      
      II. After the correct password has been entered, we will call `User.addSecondaryLogin` using the secondary login detail we obtained from the user before 

5. Also, we will have to validate the secondary login, so in that condition, I will show a Resend button next to the text field. This button will call User.resendValidateCode so user can validate their second login. 

6. If secondary login exists and is also validated, I will lock the field, and in case, the user has multiple validated secondary logins, I will choose the first one from the list. 

7. The text beneath the phone number should have different text depending on the validation status: 


	
	  I will use conditional logic to set a message — 


	  
	  **For non-existent:** “Add your phone number to settle up via Venmo.”


	  
	  **For unvalidated:** “The number has not yet been validated. Click the button to resend the validation link via text.”
	  


	  **For validated:** “Use your phone number to settle up via Venmo.”

**Comment by mallenexpensify** [comment]
@kadiealexander I assigned @NikkiWines because she was the engineer who created the issue in the Expensify repo.  Either of you update as needed

**Comment by mallenexpensify** [comment]
Updated Upwork job link https://www.upwork.com/jobs/~0106579357feaa2345

**Comment by Maftalion** [comment]
**Proposal**

- I'll add the `USER` onyx key to the ProfilePage to access the `loginList`
- Email/Password would re-use the same component to determine non-existant/unvalidated/validated
- If there are multiple secondary logins, I'd check to see if one is verified and if not I'd use the first one
- If secondary login is verified, it will be disabled
- if it's unverified, the input would be disabled and a "Resend" button would appear
- Clicking Resend would call `resendValidateCode`. This method would be updated to make it clear that an email or phone can be passed & `@expensify.sms` would be appending if the value is a phone number
- If no secondary login exists, the text input will have an "Add" button next to it.
- Clicking Add would replace the view with another that asks for password entry. Upon adding the password and clicking "Send Verification", `setSecondaryLogin` would be called with the login value and password.
- the phone number field would also display the text defined above depending one the status

**Questions**
- should email also have text below? maybe for unvalidated emails?
- how should validation/errors be handled? for example should "Add" be disabled until a valid number/email is entered & for the password screen, should the "Send Validation" be disabled until a password is entered. Also if the password is incorrect or any other error, should it be displayed below the input?
- for adding a non-existent value, it might be a little unclear that they need to click "Add" vs just clicking "Save" at the bottom. Was wondering what your thoughts would on not having a text input and just an "Add" button then on the password page have both login/password inputs there @shawnborton
- does calling `setSecondaryLogin` automatically send a verification code?

**Comment by NikkiWines** [comment]
> should email also have text below? maybe for unvalidated emails?

Both emails and phone numbers should have the text `This <email/phone number> has not yet been validated. Click the link to resend the validation link via <email/text>.

> how should validation/errors be handled? for example should "Add" be disabled until a valid number/email is entered & for the password screen, should the "Send Validation" be disabled until a password is entered. Also if the password is incorrect or any other error, should it be displayed below the input?
Good questions! 

1. Let's disable the add button until a valid phone number/email has been entered 
2. Let's also disable the `Send Validation` button until a password has been entered (I don't think we need to check for password complexity though, just as long as they've entered a value)
3. Similar to what we do on the `Change Password` view, if we get errors back from the API let's display it underneath the password field. 

> for adding a non-existent value, it might be a little unclear that they need to click "Add" vs just clicking "Save" at the bottom. Was wondering what your thoughts would on not having a text input and just an "Add" button then on the password page have both login/password inputs there @shawnborton

This is a good point. The user might think they could add a secondary login by clicking `Save` at the bottom of the screen instead of `Add`. I saw you tagged @shawnborton but @michelle-thompson I'm curious to your thoughts here too and if we should disable the save button or consider modifying the view at all. 

> does calling setSecondaryLogin automatically send a verification code?
Yes, it'll automatically send a code.

**Comment by michelle-thompson** [comment]
Hmm, you're right that this could potentially be confusing for the user. With that said, I think the clearest way to do this would be remove the `Add` button altogether and rely on the `Save` button to prompt the password screen. This also means `Save` would be disabled until a proper email/number is detected.

To be clear, I'm suggesting we keep the `Resend` button still.

Would love a second opinion from Shawn on this too.

**Comment by kaushiktd** [comment]
Hi,

This is Kaushik and have applied on your job under my name Kaushik Kapadiya. This is my technical explanation that can be understood easily,

1.  First of all get all user login list from onyx then check
   a.  if the email address is primary, we have to display a phone login as secondary if it exists. 
   b.  if the phone number is primary login, we have to display an email address as secondary if it exists.

2.  If secondary login is not mentioned then show a textinput to add email or phone as well as ADD button.
3.  If user has added secondary login like an email but still not verified that email is real or fake, we'll show a resend button near secondary login to send a new verification link.
4.  If user has secondary login which has validate then show ADD button as disabled so user can not send any validaton link.
5.  When user enter secondary login and click to add button, we'll ask for password if user enters correct password then will send validation message link.
6.  Phone number field would display the text defined above depending on the status like: Non-Existant, Unvalidated, Validated etc.

**Comment by shawnborton** [comment]
@michelle-thompson @Maftalion that sounds great to me - I like just having one save button for the entire page, and I agree it makes sense to keep the resend button.

**Comment by kaushiktd** [comment]
> @michelle-thompson @Maftalion that sounds great to me - I like just having one save button for the entire page, and I agree it makes sense to keep the resend button.

Glad you liked my suggestion.

**Comment by NikkiWines** [comment]
> @michelle-thompson that sounds great to me - I like just having one save button for the entire page, and I agree it makes sense to keep the resend button.

Wouldn't it be confusing given the `Save` button would now create two different results? With this proposed solution, in some cases it would route the user to the password page to input their password for the secondary login, and in some cases it would just save the results on the page.

**Comment by Maftalion** [comment]
Yeah, I think it makes the disable logic for the button a little more complex as well. I can set it up either way but my suggestion would be to make it independent of the rest of the form where you'd have a "Add" button with no text input which would take you to another page to enter the value & password. once completed, it would return back to the profile page but now in the "Unverified" state with the resend button

**Comment by kaushiktd** [comment]
Sounds good! So what do you think about working with me?

**Comment by kaushiktd** [comment]
> Yeah, I think it makes the disable logic for the button a little more complex as well. I can set it up either way but my suggestion would be to make it independent of the rest of the form where you'd have a "Add" button with no text input which would take you to another page to enter the value & password. once completed, it would return back to the profile page but now in the "Unverified" state with the resend button

Sounds good! So what do you think about working with me?

**Comment by michelle-thompson** [comment]
@Maftalion Are you suggesting `Save` is disabled when editing the email/phone field? And once an appropriate email/phone is detected, `Add` then becomes active while `Save` continues to be disabled? If so, I'm happy to move forward with that.

**Comment by NikkiWines** [comment]
@Maftalion, I know we were discussing some weirdness with getting the `user.loginList` when building this on the iOS sim. 
I've figured out this issue and it looks like we need to be passing `'account, loginList, nameValuePairs'` not `['account', 'loginList', 'nameValuePairs']` [here](https://github.com/Expensify/Expensify.cash/blob/master/src/libs/actions/User.js#L44-L47).

If you do that you should get all the requisite info in the response! 🎉

**Comment by Maftalion** [comment]
@michelle-thompson what I'm suggesting is that the input for the secondary login doesnt live on the profile page, instead there would only be an Add button which when it's clicked would go to the "Password Prompt" view where they would add both the email/phone and the password. upon returning to the profile view, the "unverified" email/phone would now appear but uneditable (with the resend button until verified).

**Comment by NikkiWines** [comment]
One other alternative that might be work and keeps things inline with our initial implementation is the following: 

If the user has added a value for the secondary login, hasn't clicked `Add`, and then clicks `Save`, we clear that secondary login field - effectively "resetting" the form. 

The main issue I see with this is it runs a bit counter to the rest of how that view works, where clicking `Save` saves any fields with text in them. However, at least it makes it clear that unless you click `Add` we don't save or store that secondary login anywhere.

**Comment by michelle-thompson** [comment]
![image](https://user-images.githubusercontent.com/43361905/112557845-a816c580-8d8a-11eb-8d16-dba1542cb3ae.png)
So I took @Maftalion idea and tried out a couple options here (+ what the new password prompt screen would look like). None of these feel quite right to me, but curious for feedback here.

I actually prefer @NikkiWines suggestion above. My only minor concern would be that there's potential for user frustration if, say, a user clicks `Save` thinking they're adding their phone number and it ends up getting deleted. Though I think we make it _pretty_ clear via proximity that `Add` is what should be clicked.

**Comment by shawnborton** [comment]
I actually quite like what you explored above Michelle! We've been using a pattern more and more where we use a row that has `+ Action Text` for adding things, and saving buttons for when the state of something gets changed. For example, in the Wallet flow for adding a payment method (I put this below on the left) we use this pattern and I think it works well. 

So here is what that might look like:
![image](https://user-images.githubusercontent.com/2319350/112615065-53bf2480-8e22-11eb-95db-8958dcfc93a1.png)


Also sorry for the late feedback on this, but I wonder if we should make the read-only field look more like plain text, like we do in the profile view for instance:
![image](https://user-images.githubusercontent.com/2319350/112615164-6e919900-8e22-11eb-9d46-24d57ea8f4bb.png)

**Comment by michelle-thompson** [comment]
@shawnborton I like those suggestions! Happy to move forward if @NikkiWines and @Maftalion agree :)

**Comment by NikkiWines** [comment]
Cool! Yeah that looks great to me 👍

**Comment by Maftalion** [comment]
Awesome, lgtm as well!
