### ISSUE TITLE
[User Settings] Allow users to modify avatar photo

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#2053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

With the new Settings > Profile page having been added, we need to add some new functionality: Allowing users to modify their avatar. 

### Deliverables 
- Add a button with `Edit Photo` beneath the avatar on the Settings > Profile page. If this button is pressed we should display two menu options allowing the user to either add the photo or remove it. 
- **Adding a Photo:** Utilize the existing `AttachmentPicker` component to allow users to select an image to upload. On submission call  `PersonalDetails.setUserAvatar` 
- **Removing a Photo:** Replace the existing avatar with one of our default avatars via `getDefaultAvatar`

| Mobile  | Web/Desktop |
| ------------- | ------------- |
| <img width="700" alt="" src="https://user-images.githubusercontent.com/16747822/108561633-71ddb600-72b3-11eb-833b-d6f6ac1a2fbe.png"> | <img width="900" alt="" src="https://user-images.githubusercontent.com/16747822/108561672-7efaa500-72b3-11eb-8d4d-fb4961b3cba4.png"> |

## Platform:

- [x]  Web
- [x]  iOS
- [x]  Android
- [x]  Desktop App
- [x]  Mobile Web

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/154987

**Comment by kadiealexander** [comment]
Upwork post: https://www.upwork.com/jobs/~017152423e80b99dba

**Comment by yuriitarnavskyi** [comment]
Hello, Nikki Wines.
I am Yurii Tarnavskyi from Ukraine. Just I have submitted a proposal via upwork to this job.

**Comment by Regaron** [comment]
Hi, @kadiealexander! 

I will solve the issue by doing the following: 

1. Add a button with Edit Photo beneath the avatar on the Settings > Profile page. When the button is pressed, I will leverage the existing `CreateMenu` component to display two menu options to either add or delete photos. 

It will be done using `MENU_ITEMS` quite similar to this: 
```

     const MENU_ITEMS = {
            'ADD_NEW_PHOTO': {
                icon: UploadIcon,
                text: 'Add New Photo',
                onSelected: () => this.props.onAttachmentPickerSelected(),
            },
            'REMOVE_PHOTO': {
                icon: DeleteIcon,
                text: 'New Group',
                onSelected: () => this.props.onDeleteAvatar(),
            },
        };
```

`onAttachmentPickerSelected()` will leverage the currently existing `AttachmentPicker` component and open the PickerOptions to upload the picture. 

`onDeleteAvatar()` will be used to replace the existing image with a default avatar from `getDefaultAvatar`

**Comment by yuriitarnavskyi** [comment]
Hello, Nikki Wines
Here is my solution.
- Add a button with Edit Photo beneath the avatar on the Settings > Profile page. If this button is pressed we should display two menu options allowing the user to either add the photo or remove it.
    * Create "Edit Photo" using Pressable Compontn of react-native.
    * When press this button, Create popup menu with 2 menus(Add New Photo & Remove Photo ) with similar way of CreateMenu Component and then Add clicking event following 2 features.
      const MENU_ITEMS = {
            [CONST.MENU_ITEM_KEYS.ADD_NEW_PHOTO]: {
                icon: uploadIcon,
                text: 'Add New Photo',
                onSelected: () => {/* show AttachmentPicker Component*/},
            },
        };
- Adding a Photo: Utilize the existing AttachmentPicker component to allow users to select an image to upload. On submission call PersonalDetails.setUserAvatar
   This feature will be implemented with provided AttachmentPicker Component and PersonalDetails.setUserAvatar API.
- Removing a Photo: Replace the existing avatar with one of our default avatars via getDefaultAvatar
   This feature will also be implemented with provided remove API and getDefaultAvatar method.

**Comment by Maftalion** [comment]
**Proposal**
- Add button that would user the CreateMenu component
- Add two new values to the MENU_ITEMS for: UPLOAD_PHOTO, DELETE_PHOTO
- For the `menuOptions` one or both values would be passed in. (I can hide the DELETE_PHOTO option if the avatar is already a default avatar by looking for `/images/avatars/avatar` in the URL)
- As far as handling the menu item selection, either it can be done with the current setup by passing a prop similar to `onAttachmentPickerSelected` or I was thinking to just refactor the `menuOptions` prop to accept an object instead of an array so it would look something like:
```
menuOptions={{
    [CONST.MENU_ITEM_KEYS.UPLOAD_PHOTO]: {
        onSelected: () => {
            openPicker({
                onPicked: (file) => {
                    // convert selected file to base64
                    PersonalDetails.setAvatar(base64);
                },
            });
        },
    },
    [CONST.MENU_ITEM_KEYS.DELETE_PHOTO]: {
        onSelected: () => {
            const defaultAvatar = PersonalDetails.getDefaultAvatar(login)
            PersonalDetails.setAvatar(defaultAvatar);
        },
    }
}}
```

**Comment by TechCode-R** [comment]
Hi Team,
 My steps to add this feature:
1- Add Edit Photo button which opens a bottom sheet on mobile apps and dialog on web with 2 options.
2- Design a component with Upload photo & delete photo. 
Suggestion: ( We can hide or disable delete photo button if there is already a default avatar) 
3- On click upload Image, open camera or gallery and pick image path, type, size etc of selected image and upload it to server using AttachmentPicker component as you suggested.
(Show image from local path until we get updated imageUrl from the server)
4-On delete remove PersonalDetails.setUserAvatar() value and set default image again.
 
Thanks 👍

**Comment by kaushiktd** [comment]
Hi,

This is Kaushik here. I would like to put a solution that actually explain itself instead of copy-pasted coding structure,

  1.  When press edit photo shows two option in floating same as in screenshot if choose a select new picture, we will upload a new profile image.
  2.  If remove then, replace the existing profile with the default profile image.

**Comment by Maftalion** [comment]
The app currently doesn't have an upload icon. When you get a chance, can you send that over? @shawnborton @michelle-thompson

**Comment by shawnborton** [comment]
Added the icon over on the PR, but for posterity, here it is again: [upload.svg.zip](https://github.com/Expensify/Expensify.cash/files/6220257/upload.svg.zip)
