### ISSUE TITLE
Issues signing up, Error on new account sign in

### ISSUE THREAD

**Issue by mernxl** [Expensify/Expensify.cash#2073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
Hello, i am a new dev, was trying to replicate #2063, I did encounter the following issues when signing up on .cash (both localhost and the online expensify.cash site)

FYI: I could not replicate the issue (#2063), does marking an issue with the `Exported` label mean resolved?? I really wish i could work with you guys.

## Expected Result:
1. After signup, password reset should not take too long
2. After successful login with  **new account**, report screen page should display normally.

FYI: I tried this with 2 new accounts, same results. (used separate browsers - chrome).

## Actual Result:
1. After signup link was clicked, inserting a password and validating just kept spinning forever.
2. Then after using workaround to reset password signing into the site will show up a blank screen, (error occurred)
![image](https://user-images.githubusercontent.com/16241595/112411670-95b27280-8d1d-11eb-8435-abc3e58347b2.png)

## Action Performed:
Break down in numbered steps

## Workaround:
A **new client** without access to source code won't use Expensify.
1. I bypassed by going to Expensify.com to signin with email, was told account not activated and eventually getting a new reset link that worked with the Expensify.com site. I later signed in on the .cash site.
2. I was able to bypass this by returning a default moment object instead of getting from the `getLocalMomentFromTimestamp` method. After that bypass, i could now use both local and online .cash sites.
![image](https://user-images.githubusercontent.com/16241595/112412344-ac0cfe00-8d1e-11eb-9b2c-ca475516689a.png)
 

## Platform:
Where is this issue occurring?

 Web

**Version Number: 1.0.5-31**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

**Comment by mernxl** [comment]
For the first account, i refreshed it didn't fix the issue.
The second rather, after sending a message from first account, waiting long on the .cash site, i refreshed and I could see my messages.

**Comment by AndrewGable** [comment]
Thank you for the report @mernxl - I believe this was fixed in https://github.com/Expensify/Expensify.cash/pull/2040 - @NikkiWines please correct me if I am wrong.

**Comment by NikkiWines** [comment]
Yes, that's correct - Resolved in https://github.com/Expensify/Expensify.cash/pull/2040
