### ISSUE TITLE
CreateMenu should display within the chat window area

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/Expensify.cash#2090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
CreateMenu should display within the chat window area
![image](https://user-images.githubusercontent.com/22508304/112544870-c671c680-8d74-11eb-9f4c-3a061ad7726c.png)

## Actual Result:
CreateMenu displayed above the chat list in Left Hand Navigation
![image](https://user-images.githubusercontent.com/22508304/112544978-e86b4900-8d74-11eb-8d1d-b944b6c7c15a.png)

## Action Performed:
When tapping the + button from a chat on desktop and web, the CreateMenu is displayed above the chat list, rather than within the chat window

## Platform:
Web and Desktop v 1.0.5-36

**Notes/Photos/Videos:** 
**Please note**: the missing 'Split Bill' option is expected for now

**Expensify/Expensify Issue URL:**
https://github.com/Expensify/Expensify/issues/158164

**Comment by mallenexpensify** [comment]
Job on Upwork https://www.upwork.com/jobs/~01ca7ce2254d69fcb5

**Comment by npsedhain** [comment]
Hi, I would love to work on this issue!

As a part of my proposal, I will: 




Use a prop anchorPosition as style in CreateMenu for the anchor position of the PopOver: 




https://github.com/Expensify/Expensify.cash/blob/46d6cb4911c923bb9ee367e42076f33e8cd93f45/src/components/CreateMenu.js#L102-L110

This will be: anchorPosition = {this.props.anchorPosition}  instead. 

Create a new style styles.createMenuReportAction and use {
        left: 18 + variables.sideBarWidth,
        bottom: 100,
    } it as the prop for the CreateMenu in ReportActionCompose. 

https://github.com/Expensify/Expensify.cash/blob/46d6cb4911c923bb9ee367e42076f33e8cd93f45/src/pages/home/sidebar/SidebarScreen.js#L87-L95


Similarly, use the existing style  `styles.createMenuPosition` (rename it as `styles.createMenuSidebarPosition` instead) as a prop for the `CreateMenu` in `SidebarScreen`.

Looking forward to working on this issue.

**Comment by mallenexpensify** [comment]
@stitesExpensify I just assigned to you since you were assigned to the issue in the Expensify/Expensify repo.  Can you review incoming proposals? @npsedhain submitted one above

**Comment by kaushiktd** [comment]
Hi,

This is Kaushik here and instead of making long coding structure here is simple explanation for this,

1.  create a new stylesheet for this popover.

**Comment by stitesExpensify** [comment]
Hi @kaushiktd, are you saying that you think this could be solved just by editing styles rather than creating an anchor prop? If so I think that may be the better solution in this case

**Comment by mallenexpensify** [comment]
Hi @kaushiktd , are you still interested in helping? If so, can you reply to @stitesExpensify comment above? Thanks

**Comment by kaushiktd** [comment]
@stitesExpensify 

<Popover
     onClose={this.props.onClose}
     isVisible={this.props.isVisible}
     onModalHide={() => {
         this.onModalHide();
         this.resetOnModalHide();
     }}
     anchorPosition={styles.createMenuPosition}
 >

In Your code, you've added "createMenuPosition" in which left is define: 18, and bottom is: 100
like:
createMenuPosition: {
    left: 18,
    bottom: 100,
},

Now there is two posibilities
1.  Add side bar width to left anchorPosition
like:
createMenuPosition: {
    left: 18 + sideBarWidth,
    bottom: 100,
},

2.  Add position absolute to "createMenuPosition" and position relative to its parent view in which view popover is displayed and set position left according device width.

**I can do this on Upwork if you can assign this job to me on upwork**

**Comment by npsedhain** [comment]
@kaushiktd, I had actually tried solution number 2 as well, and I don't think it is possible without any kind of DOM manipulation. CreateMenu and FAB, for instance, aren't parent-child components, they are in different branches in the DOM. So, I am curious to know how you'd address this problem.
cc: @mallenexpensify

**Comment by trjExpensify** [comment]
Thanks, Anup. We've sent you the offer on Upwork. Please remember to link your PR to this issue when you're ready! 👍

**Comment by parasharrajat** [comment]
@trjExpensify. Just a point here. I think the animation should be from bottom to top for the menu.

**Comment by npsedhain** [comment]
Thanks, @trjExpensify, will raise a PR tomorrow and link to this issue. :)

**Comment by trjExpensify** [comment]
Yep, bottom to top from within the chat screen makes sense. 👍

**Comment by mallenexpensify** [comment]
@npsedhain can you provide an update? It appears things might have stalled a bit

**Comment by npsedhain** [comment]
Hey @mallenexpensify, thanks for reaching out, I am actually waiting on @tgolen on the PR as I have done what had been asked on the comments. Maybe he has been busy lately? I don't really know!

**Comment by parasharrajat** [comment]
I think, this issue is resolved & should be closed.

**Comment by mallenexpensify** [comment]
Thanks for the ping @parasharrajat .  @stitesExpensify can you confirm everything is good and done here and that @npsedhain should be paid?

**Comment by npsedhain** [comment]
Let me know if there is anything I can do. 😅

**Comment by roryabraham** [comment]
As discussed [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1619192999424100), yes @npsedhain should be paid. Even though his pull request caused a regression, he wasn't given a chance to resolve that due to random one-off circumstances. The base branch was renamed in the E.cash repo, so GitHub was broken and didn't allow us to revert the pull request like we normally would. So let's pay out and close this issue.

> Let me know if there is anything I can do. 😅

@npsedhain As far as I can tell, there are no remaining TODOs for this issue. These things happen, and that's why we have a QA process. Just so you know, what would _normally_ happen would be that your PR would just be reverted, and you'd be given another chance to fix the issue without causing a regression. Does that make sense?

**Comment by npsedhain** [comment]
Thanks @roryabraham. It totally makes sense and I get it that the issue was one off provided that I didn't have such experiences in the issues I jad contributed before hand. So I totally get it. But let me know if anything else comes up even after this is closed. Happy to help and be a part of this. :)

**Comment by mallenexpensify** [comment]
@roryabraham should I wait to see if there are any more regressions or pay @npsedhain _now_?

**Comment by roryabraham** [comment]
At this point, I would just pay him, because if there are any regressions they are on me now (because I fixed the regressions caused by this PR with my own PR). Sorry if that was poorly worded, but hopefully you get what I'm saying.

**Comment by mallenexpensify** [comment]
Thanks, I just wanted to double check to be safe. I need to split now but planning to pay this afternoon

**Comment by mallenexpensify** [comment]
The contributor has been paid, the contract has been completed, and the Upwork post has been closed
