### ISSUE TITLE
Create a group chat info view, with additional participant info

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/Expensify.cash#2105]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Problem -**
Currently there isn't a way to view the full list of participant information in a group chat, so there isn't a way determine who is included in the private discussion, and to find additional info about participants.

**Solution -** 
Tapping the title bar should show the right sidebar/full screen modal, which will list the group participants.

- Create a ParticipantsPage that has the following route structure /participants/:reportID
- When there are multiple participants update this code to navigate to the interstitial screen https://github.com/Expensify/Expensify.cash/blob/2b0674b94819926f38e71b4c5c8edf25bebe1ecb/src/pages/home/HeaderView.js#L82-L85
- ParticipantsPage will subscribe to the reportID ${ONYXKEYS.COLLECTION.REPORT}${reportID} passed in the route param
- And show a list of participants that when tapped on will navigate to /details/:login like we do when there is only one participant.

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/145056
**Upwork Job Link:** https://www.upwork.com/jobs/~01794b62eeeb8680e7

**Comment by npsedhain** [comment]
Hi, I would love to work on the issue! 

I will: 

Create a new Participants Page. Add the route `/participants/:reportID` in `ROUTES`. 

Update the code to navigate the user to the new Participants page whenever there are multiple participants in the report

I will subscribe to the new Participants Page to the report ID `${ONYXKEYS.COLLECTION.REPORT}${reportID}` using the `reportID` param in the route `/participants/:reportID`. 

This way, we will be able to get all Participants for the report. 

The Participants Page will have a view for a list of participants. Whenever tapped on it, it will navigate to `/details/:login`.

Question: 

Do we have a UI design for how the Participants Page looks like?

**Comment by laurenreidexpensify** [comment]
Thanks @npsedhain - can you also apply via https://www.upwork.com/jobs/~01794b62eeeb8680e7 so we can move forward to hiring?

**Comment by Julesssss** [comment]
Hi @npsedhain, here's our latest mockup. Tagging @Expensify/design to confirm this is still the plan.

Please let us know if you have any thoughts or questions related to this. 

![108827921-7a413400-75c6-11eb-9f7f-37caccc81426](https://user-images.githubusercontent.com/10736861/112820882-ff17e580-907d-11eb-9891-c2bac7cda05a.png)

**Comment by shawnborton** [comment]
Yup, that looks good to me.

**Comment by npsedhain** [comment]
Thanks, @laurenreidexpensify, I will apply to the posting ASAP.

@Julesssss Thanks I will get started soon and let you in if I have any questions. :)

**Comment by laurenreidexpensify** [comment]
@npsedhain can you please tag me when you have a PR up? Thanks

**Comment by npsedhain** [comment]
Okay @laurenreidexpensify, I am working on it. Will raise a PR tonight!

**Comment by npsedhain** [comment]
@laurenreidexpensify, I have opened the PR. :)
