### ISSUE TITLE
[PAYMENT DUE 20 APRIL + BONUS FOR CREATING ISSUE] - mWeb/Web Safari - Selecting add attachment does not open the file picker

### ISSUE THREAD

**Issue by kidroca** [Expensify/Expensify.cash#2109]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Selecting "Add Attachment" from the chat menu should open the Browser's file picker

## Actual Result:
After pressing on "Add Attachment" the menu closes and focus is brought back to the chat input field

## Action Performed:
1. Start the local dev server
2. Open or start a chat
3. Press on the plus button (+) inside the input field
4. Select "Add Attachment"

## Workaround:
Use a different browser

## Platform:
Where is this issue occurring?

Web❌ 
 iOS 
 Android
 Desktop App 
 Mobile Web ❌

**Version Number:** expensify.cash@1.0.6-3
using the code in the `master` branch

**Notes/Photos/Videos:**  

https://user-images.githubusercontent.com/12156624/112666303-b5a07e00-8e64-11eb-8d35-0cb0634f7920.mp4

- first part Safari
- second part Chrome

**Comment by kidroca** [comment]
### Proposal

Doing a quick search on stackoverflow review that using: `<input hidden />` or an input with `display: none` does not work for this purpose in Safari: https://stackoverflow.com/questions/28721679/trigger-the-file-input-prompt-with-a-hidden-label-element-safari

The suggested approach is to make the input invisible taking 0 width/height which would allow you to programatically trigger a click in all browsers. 
We can further add an `aria-hidden="true"` attribute to remove the element from the accessibility API 

I can also apply the fix for resetting the selected file listed here: #1159 as I've recreated the issue successfully

**Comment by Julesssss** [comment]
Confirmed this issue currently exists for prod on Safari.

**Comment by laurenreidexpensify** [comment]
@kidroca would you like to submit a PR to fix this via the solution you've proposed?

**Comment by kidroca** [comment]
Yes 👍

**Comment by kidroca** [comment]
I would like to extend the scope to also make sure a suitable options appear for mWeb:
![image](https://user-images.githubusercontent.com/12156624/112978148-a751ab00-915f-11eb-9717-99c857dfe911.png)

Currently the functionality does not work at all on mWeb (tested Chrome and Safari) so I don't know what options appear for the current configuration of the file attachment

https://developers.google.com/web/fundamentals/media/capturing-images

---

@laurenreidexpensify How can I apply for this task on Upwork ?

**Comment by kidroca** [comment]
Bump @laurenreidexpensify 
I haven't started to work on this as I'm not hired for this task on Upwork

**Comment by laurenreidexpensify** [comment]
hi @kidroca https://www.upwork.com/jobs/~01316cac66af339ce4 is now live - if you apply will make sure you're hired

**Comment by kidroca** [comment]
Thanks @laurenreidexpensify just did: https://www.upwork.com/ab/proposals/1377573217104883713

**Comment by laurenreidexpensify** [comment]
Excellent, Thanks!

**Comment by laurenreidexpensify** [comment]
Assuming no regressions, will issue payment on 20 April @kidroca 👍🏽

**Comment by kidroca** [comment]
@laurenreidexpensify 
Thank You Lauren!

Is each ticket managed individually, because this is the first time I see a message like that - none of my other completed PRs would mention a payment due date. Should I worry?

**Comment by laurenreidexpensify** [comment]
Ah good catch @kidroca - the only reason that you're seeing this is, because unlike the other issues you've worked on, you created this one :) and usually all the back end management for this is taken care of in our private repos, where someone from Expensify will have first logged the issue being fixed. 

So all in all nothing to worry about here, we're still in the beta phase of this, so do keep asking when you see anything that seems confusing to you from a process perspective, we greatly appreciate the feedback!

**Comment by laurenreidexpensify** [comment]
Paid and ended contract after no regressions 👍🏽 @kidroca also I will post that other update we discussed today in the Slack channel.  Thanks for your work here!
