### ISSUE TITLE
FAB hidden by Keyboard on iPad

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/Expensify.cash#2151]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
The FAB should always be visible so users can easily trigger their desired action, on every platform

## Actual Result:
FAB hidden by keyboard on iPad

## Action Performed:
1. Log in to E.cash with iPad
2. Reveal software keyboard
3. Observe FAB menu is not visible

## Workaround:
None

## Platform:
 iOS (iPad)
![Screen Shot 2021-03-29 at 12 56 06 PM](https://user-images.githubusercontent.com/32969087/112910277-c0d6f200-908e-11eb-8940-bb09e3d34f67.png)

**Version Number:**
v1.0.7-0
**Logs:** None
**Notes/Photos/Videos:** See above
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/158758
**Upwork link:** https://www.upwork.com/jobs/~0158125c819a6e8fac

**Comment by JmillsExpensify** [comment]
@marcaaron this is my first triage, let me know if I missed something!

**Comment by marcaaron** [comment]
Looks perfect !

**Comment by aliabbasmalik8** [comment]
The solution is just needed to add `KeyboardAvoidingView` in FAB component like this 
```
            <KeyboardAvoidingView behavior="position">
                <AnimatedPressable
                    onPress={this.props.onPress}
                    style={[
                        styles.floatingActionButton,
                        {transform: [{rotate}], backgroundColor},
                    ]}
                >
                    <AnimatedIcon src={Plus} fill={fill} />
                </AnimatedPressable>
            </KeyboardAvoidingView>
```

**Comment by marcaaron** [comment]
Alright sounds good. Please let's make sure to also show screenshots of this working ok on all platforms when the PR is ready (tablet Android too thanks).

**Comment by JmillsExpensify** [comment]
Hi @aliabbasmalik8, I wanted to confirm that you added a proposal on Upwork? You'll need to do that so we can hire you officially for the job. Thank you!

**Comment by aliabbasmalik8** [comment]
@JmillsExpensify Proposal submitted on Upwork.
Thanks

**Comment by JmillsExpensify** [comment]
Awesome, thank you!

**Comment by JmillsExpensify** [comment]
Thanks @aliabbasmalik8. We settle Upwork jobs 7 days after the PR is merged to ensure no regressions.

**Comment by marcaaron** [comment]
There are a couple of issues with this PR so I'm reopening until they are resolved.

**Comment by JmillsExpensify** [comment]
Changes requested on the linked PR.

**Comment by JmillsExpensify** [comment]
PR merged on Apr. 13. Waiting for any regressions until April 19, then we'll issue payment.

**Comment by JmillsExpensify** [comment]
Issuing payment via Upwork, as we haven't seen any regressions.

**Comment by JmillsExpensify** [comment]
Hmm, I'll have to look into a possible regression on this one. That said, I'm actually not sure if this is truly a regression, as these comments can get kind of spammy.

**Comment by marcaaron** [comment]
Agree it's not a regression - the comment happens anytime we mention any issue so we can at least attempt to see if they are mentioning something about it being a regression. Looks like the contributor is just linking to this PR to explain when the original code was added - so not likely that this super old issue has caused any recent regression 😄

I think we are going to remove this, because everyone hates it. I don't really understand why it gets so much hate and think we have to do _something_ to try to figure out if things are regressions otherwise we will never do RCA for anything.

**Comment by JmillsExpensify** [comment]
> I think we are going to remove this, because everyone hates it. I don't really understand why it gets so much hate and think we have to do something to try to figure out if things are regressions otherwise we will never do RCA for anything.

Oh to be clear, I don't hate them. I agree, it's net good and worth the time. Probably what would make this more helpful (and less confusing) is an expectation around issue linking. A lot of people link for context rather than to point to regressions.
