### ISSUE TITLE
URL on mobile web does not update correctly at mobile screen sizes

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#2188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Upwork Job
https://www.upwork.com/jobs/~016463e249d6e050b1

## Expected Result:
The URL should update accordingly at all screen sizes. 

## Actual Result:
When in mobile web screen widths, the URL is not updating consistently. Note that this does not affect navigation, just the URL that displays.  At wider screen widths the path displays is fine. Only when the drawer is not permanently shown does this cause issues.

## Action Performed:
1. Open the website at a small screen width
2. Navigate between various chats
3. Observe that the URL in the browser inconsistently shows the correct reportID for what is displayed

## Platform:
 Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![110539790-c497da00-80c9-11eb-9fbf-54d3095cc5d2](https://user-images.githubusercontent.com/37308300/113227133-e49d6200-925f-11eb-91ec-23968fedacb7.gif)
![113039452-62b01a80-9133-11eb-90ff-3333826062fb](https://user-images.githubusercontent.com/37308300/113227200-17475a80-9260-11eb-8643-9c1b9c772197.png)
![113039444-60e65700-9133-11eb-9783-df0e857d042a](https://user-images.githubusercontent.com/37308300/113227205-19111e00-9260-11eb-8c2a-170455fb9cf7.png)
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/157239

**Comment by longman0512** [comment]
Hello
It is very interesting.
Can you share your  source code?
I am going to fix it.
Regards

**Comment by SameeraMadushan** [comment]
I was digging into this issue for some time.
But the only things I notice,

- In small screens drawer is open
- When I click on report -> drawer gets hidden and the report screen comes visible.
- I noticed when the report opens and the drawer gets hidden browser navigation goes back one step. 
- You can notice it with browser navigation buttons. (forward button becomes available)
- When you press the forward button, the correct reportID will display in the browser URL.
Eg: 
reportID: 111
reportID: 222
reportID: 333
First, navigate to 111 then come back and navigate to 222
Page navigates to 222 and the browser instantly goes back to 111.
When we press the browser next button it will show the 222 in the URL.

Couldn't find it by debugging. 🤔 😟   Just wanted to comment on the findings. 😀

**Comment by arielgreen** [comment]
**Note**: The price for this fix has been upped to $500.

**Comment by SameeraMadushan** [comment]
@arielgreen is it possible to share the logs here? Don't have access to StackOverflow.

**Comment by marcaaron** [comment]
Heads up I have a solution for this one so I'm going to open a PR.

**Comment by marcaaron** [comment]
Opened an issue in the `react-navigation` repo + added some more context and a reproduction 
https://github.com/react-navigation/react-navigation/issues/9499
