### ISSUE TITLE
Android - Chat - Tapping plus opens chat instead of new or group chat options

### ISSUE THREAD

**Issue by isagoico** [Expensify/Expensify.cash#2207]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
2 options appear. One to create a new chat and one to create a group.

## Actual Result:
Opens the chat window, + button non functional

## Action Performed:
1. Launch the app and login
2. Tap the +button

## Workaround:
No workaround. 

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.11-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Issue not reproducible in production. 

https://user-images.githubusercontent.com/44479856/113362234-eb89aa80-931b-11eb-9f81-1b667ce59ddb.mp4

**Expensify/Expensify Issue URL:**

**Comment by marcaaron** [comment]
This regression was caused by https://github.com/Expensify/Expensify.cash/pull/2183

**Comment by marcaaron** [comment]
https://github.com/Expensify/Expensify.cash/issues/2151

**Comment by marcaaron** [comment]
cc @aliabbasmalik8
