### ISSUE TITLE
Skip IOU participants step if launched from within chat

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/Expensify.cash#2246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This issue builds on top of the existing IOU Modal, which was implemented [in this PR](https://github.com/Expensify/Expensify.cash/pull/1561). The second step (`IOUParticipant`) should be skipped if the user has launched the IOUModal from within a chat/group chat.

**Displaying the IOU menu options**
- Make the [following changes](https://github.com/Expensify/Expensify.cash/compare/jules-showIOUMenuOptions?expand=1) to temporarily display the IOU menu options -- but please do not commit them!

**Deliverables:**
-  When opening the IOUModal from a 1:1 or group chat, we should retrieve the participant list and pass that list to the Modal. Then, within IOUModal:
    1. If user list empty, include the IOUParticipants step within the step array
    2. Else, exclude the participant step and set the IOUModal `participants` 
- Use `react-navigation` and add participants as screen props. Build out a second param for `Navigation.navigate()` to pass data to the view and make them available ([see react-nav docs](https://reactnavigation.org/docs/params/))

**Expensify/Expensify Issue URL:**
https://github.com/Expensify/Expensify/issues/156863# 

**Job on Upwork**
https://www.upwork.com/jobs/~012decdc661dbfa12b

**Comment by Maftalion** [comment]
**Proposal**
- First I would update `navigate` and `linkTo` to be able to pass navigation params since that's not supported with the current setup:
https://github.com/Expensify/Expensify.cash/blob/5f477a20dae70b0d849db5f1b11d3420bb893f2b/src/libs/Navigation/Navigation.js#L35-L42
- I would pass the navigation params with the initial navigation in ReportActionCompose: `onSelected: () => Navigation.navigate(ROUTES.IOU_REQUEST, {participants: this.props.participants})`
- Then I would break up the current IOU screen into 3 different screens for Amount/Participants/Confirm. Amount screen would navigate to Confirm directly if participants were passed in as nav params, otherwise it will navigate to Participants.
- Confirmation page would always get amount/participants passed in regardless of whether they came from Amount or Participant screens.

**Questions**
- the report only has the participants as an array of their logins, whereas the participants data from the Participants screen has a lot more data:
```
alternateText: "maftalion1@gmail.com"
hasDraftComment: false
hasOutstandingIOU: false
icons: ["https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_8.png"]
iouReportID: undefined
isPinned: true
isUnread: false
keyForList: "70416065"
login: "maftalion1@gmail.com"
participantsList: [{…}]
reportID: 70416065
searchText: "Matthew Aftalion maftalion1@gmail.com"
text: "Matthew Aftalion"
tooltipText: "maftalion1@gmail.com"
```
Would the final confirmation page need just the participant logins or would it have to be mapped to match the similar shape created in the participants screen?

**Comment by saudkhan1391** [comment]
Why don't you create a Custom modal for it if the IOU doesn't work ? You can use Redux or Context API for state management and then you can pass the props through any component wherever you like.
Let me know what are your thoughts on this ?

**Comment by Julesssss** [comment]
Hi @Maftalion, thanks for the detailed proposal. 

> Then I would break up the current IOU screen into 3 different screens for Amount/Participants/Confirm.

As these 'steps' are already separated and [managed by the IOUModal](https://github.com/Expensify/Expensify.cash/blob/f0a068b5f2979e6390968bcbb76144a01bec12e2/src/pages/iou/IOUModal.js#L175-L199), is the proposal here to make them actual `react-native-navigation` Screens, or something else entirely?

> Would the final confirmation page need just the participant logins or would it have to be mapped to match the similar shape created in the participants screen?

The plan was to just require emails, as that is all the final API request requires. But it looks like the WIP PR includes much more data -- I'm not sure that this is necessary though, so I've asked the [author to confirm here](https://github.com/Expensify/Expensify.cash/pull/2120/files#r608480053). 

The IOUConfirm step is nearing completion but still WIP ([here's the PR for reference](https://github.com/Expensify/Expensify.cash/pull/2120)).

**Comment by Julesssss** [comment]
Hi @saudkhan1391. Thanks for the comment, but I'm not sure exactly what your proposal is here. Could you please clarify how you would implement the listed requirements?

**Comment by Julesssss** [comment]
@Maftalion for the participant details, we should be able to retrieve them via [getPersonalDetailsForLogins](https://github.com/Expensify/Expensify.cash/blob/9194fd9131e16c65d20f14d3b8b72cb3630c1671/src/libs/OptionsListUtils.js#L32-L46). I think it would be simplest to do this step as the modal opens, as we use a different method to retrieve the participant details at the second step.

**Comment by Maftalion** [comment]
@Julesssss thanks for clarifying!

>As these 'steps' are already separated and managed by the IOUModal, is the proposal here to make them actual react-native-navigation Screens, or something else entirely?

Yeah basically splitting out these components into their own screens to clean things up a bit and getting rid of all the index/step logic since that would all be provided out of the box. (I can also leave it how it is if needed)

>Yeah... we need a few other fields for the UI (name, avatar). Open to suggestions to how best to handle this (perhaps it makes sense to retrieve this at the confirm step where we render them) -- if so then we'll need to await the following PR most likely (which is close to review).

Cool! yeah I think I can just use `getPersonalDetailsForLogins` on the final step (confirm) to get all the details for the logins.

**Comment by Julesssss** [comment]
> Yeah basically splitting out these components into their own screens to clean things up a bit and getting rid of all the index/step logic since that would all be provided out of the box. (I can also leave it how it is if needed)

I think it is a good plan, but one fear I have is that web users would then be able to navigate via the root to a specific step in the IOU flow. Perhaps this isn't a huge problem, but I wonder if you have any thoughts on how to avoid this?

**Comment by parasharrajat** [comment]
Making these into separate screens will give us clean code but I think it won't be useful. I follow this.
> Make a screen if want users to navigate to that component via URL

In our case, these are immediate steps and we don't any draft for creating a request so jumping directly to any step will never happen.

**Comment by Maftalion** [comment]
Hmm yeah that makes sense. I wonder if something like https://reactnavigation.org/docs/navigation-container#linkingenabled could be used for those routes. But I'll leave it as is for now.

**Comment by Maftalion** [comment]
@Julesssss I have a question around the params for this task.

I can pass the params like this using the navigation method:
```
navigationRef.current.navigate('IOU_Bill', {
    screen: 'IOU_Bill_Root',
    params: {
        participants: this.props.report.participants,
    },
});
```
but this builds a url like: `http://localhost:8080/iou/split?participants=concierge%40expensify.com%2C%2B13106668155%40expensify.sms%2Cmaftalion1%40gmail.com`

I was wondering if it would be better to just use the reportID like `/iou/split/:reportID` and use the reportID to grab the participants from onyx?

That way the url is simpler like:  `http://localhost:8080/iou/split/1234`
and the navigation method can remain consistent with our current way of navigating to screens:
`Navigation.navigate(getIouRoute(reportID))`

**Comment by Julesssss** [comment]
> I was wondering if it would be better to just use the reportID like /iou/split/:reportID and use the reportID to grab the participants from onyx?

Oh definitely, that's what I had in mind too. 

Looks like we're good to go here now? 

> Just noticed some weird navigation behavior with the current setup:

Thanks! Please feel free to create the issue and claim the bounty. Else, let me know and I'll create this.

**Comment by Maftalion** [comment]
@Julesssss I have the work basically completed, do you want me to open a draft PR or should I just wait for this to get merged before opening a PR? https://github.com/Expensify/Expensify.cash/pull/2120

**Comment by Julesssss** [comment]
Let's get the WIP PR created for now 👍

**Comment by Julesssss** [comment]
Hey @Maftalion, just wanted to let you know that we've merged the [blocking PR](https://github.com/Expensify/Expensify.cash/pull/2120).

**Comment by JmillsExpensify** [comment]
Looks like our blocking PR has made it to staging.

**Comment by Julesssss** [comment]
Just to clarify, we don't need to wait for this to reach prod as all changes are on the front-end.

**Comment by Maftalion** [comment]
@Julesssss Sound good, the pr is ready for review

**Comment by Julesssss** [comment]
Ideal, thanks for letting me know.

**Comment by mallenexpensify** [comment]
Scheduled to pay on 4/29 if there are no regressions

**Comment by mallenexpensify** [comment]
Paid, sorry for the slight delay @Maftalion
