### ISSUE TITLE
Chat - Unable to create a new account with gmail, stuck in "Resend link" loop

### ISSUE THREAD

**Issue by isagoico** [Expensify/Expensify.cash#2248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
When the user clicks on the validation link in the email, they are redirected to /setpassword page and are able to successfully create a new account.

## Actual Result:
The validation link in the email redirects the user to /signin page with "Resend link" button. If the user clicks it, the link in the next email redirects them to the same page. User is stuck in this loop and unable to create a new account with gmail.

## Action Performed:
1. Open https://staging.expensify.cash/
2. Enter a new gmail address without an Expensify account.
3. Click "Continue".
4. Click on the validation link from the email (convert it to staging if needed)
5. Click "Resend".
6. Repeat Step 4.

## Workaround:
Create the account and validate via expensify.com and log in in Expensify.cash 

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS ✔️
 Android ✔️
 Desktop App ✔️
 Mobile Web  ✔️

**Version Number:** 1.0.13-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

Issue is reproducible in production and staging. 

![image](https://user-images.githubusercontent.com/44479856/113781849-501f7d80-96ff-11eb-851f-7f358a070aae.png)

https://user-images.githubusercontent.com/44479856/113781832-49910600-96ff-11eb-93a6-606d32044201.mp4

**Expensify/Expensify Issue URL:**

**Comment by marcaaron** [comment]
This will happen until we merge @jasperhuangg's PR https://github.com/Expensify/Expensify.cash/pull/1857

**Comment by jasperhuangg** [comment]
Yup! Sorry for missing this; it should be fixed by now.

**Comment by isagoico** [comment]
Yep! Confirmed this is working as expected now. Thanks 🎉
