### ISSUE TITLE
Improve Onyx.merge performance by informing listeners that a key has changed before persisting it in local storage

### ISSUE THREAD

**Issue by iwiznia** [Expensify/Expensify.cash#2397]
Context https://expensify.slack.com/archives/C01GTK53T8Q/p1618405920178400

# Problem

When we set a key in onyx, the time it takes to inform listeners that they key was set is quite long. This is because we are waiting for the value to be saved to AsyncStorage, but there's really no need for that wait.

# Solution

We can inform listeners that the value has changed at the same time we tell AsyncStorage to save it.

Coming from https://github.com/Expensify/react-native-onyx/issues/63 the Onyx merge path is:
```
Onyx.merge -> get -> set -> AsyncStorage.setItem -> then(() => keyChanged(key, val))
```

The idea is to trigger `keyChanged` at the same time `setItem` or `set` is called.

**Comment by quinthar** [comment]
Is there any risk that we will call `keyChanged()` before it's saved to disk, which might create race conditions with whatever is in that callback -- which might do something that reads from disk, and expects that value to be set?

**Comment by iwiznia** [comment]
Great question, I really don't know, but thinking of it, it's totally possible someone uses it in the callback... so maybe we can't really change this.

**Comment by kidroca** [comment]
Can you set up an example of how someone might read from the same storage key inside the callback ?

Also why would someone ever use it like that

Is this the potential problem?
```js
Onyx.connect({
    myAlias: {
        key: 'SOME.ITEM',
        // keyChanged would trigger this callback
        callback: (data) => {
            // Yes calling Onyx.get('SOME.ITEM') is uncertain
            // But why would make such a call when I've just received the latest value in data

            // Retrieving other keys won't be a problem e.g. Onyx.get('OTHER.ITEM')
        }
    }
})
```

You can introduce this enhancement as a configuration for `connect` so whoever is using that method can opt in to that behavior 
 
```js
Onyx.connect({
    myAlias: {
        key: 'SOME.ITEM',
        callback: (data) => {/* ... */},
        // I hereby declare I just need the data ASAP and won't read from storage for the same key in my callback
        optimistic: true,
    }
})
```

**Comment by marcaaron** [comment]
On the surface, this idea sounds reasonable, but there is one piece I think we are missing

**Scenario:**
1. Data is prepared and we are ready to call `set()` after batching together merges
2. We call `keyChanged()` before `set()` (and assume the write will be fine)
3. The data fails to be set for some reason (storage exceeded most likely)
4. We now have a bad picture of state when calling `get()` then next time we `merge()` so that merge will possibly return incomplete data (since we are initial referencing what's in storage to make the merge in the first place)

So, I think is a problem, but I also think we are also maybe underestimating (or at least not considering) the time it takes to `get()` data before setting it. The most obvious solution to both would be to use a JS object memory cache this way we are never referencing what is in storage to apply a merge (besides from whatever data we dump into the cache when Onyx initializes).

I am optimistic that this will improve things, but besides the potential data loss stuff that I've brought up... would it be helpful to maybe just quickly benchmark a change where we put `keyChanged` before `set()` to see what improvements there are?

**Comment by iwiznia** [comment]
> The data fails to be set for some reason (storage exceeded most likely)

But it will get stored _eventually_ since we evict things from the storage when it's full, no?

> would it be helpful to maybe just quickly benchmark a change where we put keyChanged before set() to see what improvements there are?

Yep! As well as measure where the time is spent (get, set, other?)

**Comment by marcaaron** [comment]
>But it will get stored eventually since we evict things from the storage when it's full, no?

That's true, I was thinking of a hypothetical irrecoverable error where the write never happens at all and in this case the expectation would be that the app should still be able to sync the JS object store. But perhaps that's not a real problem yet.

**Comment by marcaaron** [comment]
Ok so this is just one test I ran but perhaps there are some better ideas...

# Test

From completely empty storage measure the time it takes for `Onyx.merge()` to set post downloaded `reportActions` data to storage and then update the subscriber of the active report. This does not take into account network request time only the time between when data is returned from the `fetch()` and when the component props are updated with this data.

## Web
**Before:**
`Timing:expensify.cash.fetchActionsAndDataAvailableToOnyx 58`

**After:**
`Timing:expensify.cash.fetchActionsAndDataAvailableToOnyx 52`

## iOS

**Before:**
`Timing:expensify.cash.fetchActionsAndDataAvailableToOnyx 63`

**After:**
`Timing:expensify.cash.fetchActionsAndDataAvailableToOnyx 59`

## Android

**Before:**
`Timing:expensify.cash.fetchActionsAndDataAvailableToOnyx 558`

**After:**
`Timing:expensify.cash.fetchActionsAndDataAvailableToOnyx 482`

There is some measurable performance impact, but I'd be curious to see a more global test. In general, moving the call to `keyChanged()` before `set()` improved timing a bit. 

**Note:** Android looks much slower compared to others in this test, but we are comparing Apples to Androids and not all hardware emulation is equal.

**Comment by iwiznia** [comment]
hmmm from those numbers, it does not look like the change is worth it, agree?

**Comment by marcaaron** [comment]
Possibly, but to be fair, the test was pretty myopic. There was a 76ms savings in Android which could be significant. And `keyChanged()` also got called 168 times after `set()` on a cold boot so it could add up to some more significant delay.

**Comment by marcaaron** [comment]
I think we are already doing this as a side effect of the `Onyx.get()` proposed changes so I'm going to close this one.
