### ISSUE TITLE
Cursor isn't properly returning to compose box during chat and or after switching chats

### ISSUE THREAD

**Issue by isagoico** [Expensify/Expensify.cash#2403]
From Matt's [issue in E/E rep](https://github.com/Expensify/Expensify/issues/160525)

<hr>

## Expected Result:
While chatting or after selecting someone from search, the cursor to return to the compose box so that a user can instantly type messages

## Actual Result:
Cursor shows in compose box but no characters show when typing

## Action Performed:
Chat
1. Ensure you're on Desktop v1.0.21-0
2. Type a message to a test account and send by clicking the return key 
3. Observe that the cursor shows in compose box but you can't type characters into the box

Search
1. Go to search on right side, type test account name and then click enter key
2. 3. Observe that the cursor shows in compose box but you can't type characters into the box
 
- **Platform, Version Number:** Desktop v1.0.21-0. 
- **Notes/Photos/Videos:** Any additional supporting documentation
From [this Slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1618431963227000)
> ISSUE: Compose box is acting wonky - When switching or sending chats I can see the cursor in the compose box but when I try to type, nothing happens.  I have to use my pointer to click on the box to be able to type (or... occasionally it magically allows me to start typing).  Desktop v1.0.21-0.  This is a regression, I def would have noticed before

**Comment by marcaaron** [comment]
I'm pretty sure we have fixed this issue. But let us know if it still occurs?
