### ISSUE TITLE
Search feature is not working

### ISSUE THREAD

**Issue by iwiznia** [Expensify/Expensify.cash#2538]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Jump to the chat

## Actual Result:
Blank screen and JS error

## Action Performed:
- CMD+k
- Select a person to chat
- See blank screen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
Where is this issue occurring?

I only tested in web and in staging

**Version Number:**
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/521248/115774958-853ff700-a3b2-11eb-8e6b-6ac963e1690c.png)

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by isagoico** [comment]
We're also able to reproduce this. 

Another bit of info, this same error is displayed when trying to create a new chat or group 

![image](https://user-images.githubusercontent.com/44479856/115786171-747d8a00-a38e-11eb-9311-91120cef9332.png)

**Comment by marcaaron** [comment]
This was me thanks I broke it.

**Comment by marcaaron** [comment]
This doesn't happen on `main` and the PR that will fix it is here -> https://github.com/Expensify/Expensify.cash/pull/2525

So, I also fixed it already, but the timing is just bad.

**Comment by iwiznia** [comment]
So, should we CP that to staging?

**Comment by marcaaron** [comment]
Sorry, no looking into it some more and it's broken. I should probably quit while I'm ahead.
