### ISSUE TITLE
Blank Screen and TypeError from BootSplash on Non-Native Platforms

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/Expensify.cash#2618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
The sign in page should render without any issues.

## Actual Result:
A blank screen appears, and a TypeError appears in the JS console:
<img width="1792" alt="Screen Shot 2021-04-29 at 8 35 48 AM" src="https://user-images.githubusercontent.com/31285285/116490270-85b42280-a8c9-11eb-9717-13b1a4e0179b.png">

## Action Performed:
Run Expensify.cash locally, navigate to whatever localhost URL it's served from.

## Workaround:
Use mobile

## Platform:
 Web
Mobile Web
Desktop

**Comment by jasperhuangg** [comment]
Looks like it was caused by this PR: https://github.com/Expensify/Expensify.cash/pull/2594. We need to update our definition of `hide` in `src/libs/BootStrap/index.js` to return an object with `then` defined.

**Comment by parasharrajat** [comment]
oh yeah just sending a fix in few minutes.

**Comment by parasharrajat** [comment]
@jasperhuangg I don't think its a regression from that PR.

**Comment by parasharrajat** [comment]
Thanks for taking care of this @jasperhuangg. Let me know if you need anything from me.

**Comment by jasperhuangg** [comment]
My bad for not seeing your comment sooner! I opened up the issue after I already wrote up a fix.
