### ISSUE TITLE
Signing out yields strange SignIn Screen URL Format

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/Expensify.cash#2620]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Signing out should navigate back to `[baseURL]/`

## Actual Result:
Signing out navigates to `[baseURL]/?params=%5Bobject%20Object%5D&screen=Report`

## Action Performed:
1. Sign in to your account on Web or Mobile Web.
2. Take a few actions (open different chats, etc.)
3. Sign out.
4. Observe the URL format.

## Workaround:
Yep, it just looks pretty ugly.

## Platform:
All platforms, but the URL is only visible on Web and Mobile Web.

 Web
 Mobile Web

**Version Number:** v1.0.33-0

cc @marcaaron

**Comment by roryabraham** [comment]
@isagoico since there are no known side-effects of these strange URLs, I'm removing the deploy blocker label from this, and making it a weekly.

**Comment by marcaaron** [comment]
@jasperhuangg What's the status on this?

**Comment by jasperhuangg** [comment]
Oop, sorry I forgot I created this issue; it should have been fixed by https://github.com/Expensify/Expensify.cash/pull/2616. When I tested that PR the issue didn't resurface. Closing this!
