### ISSUE TITLE
Blank white screen and console error after signing in and loading reports screen

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/Expensify.cash#2785]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
We should be able to sign in without any issues and load all the reports.

## Actual Result:
There's a blank, white screen and this console error when we login:
<img width="483" alt="Screen Shot 2021-05-11 at 2 34 44 PM" src="https://user-images.githubusercontent.com/31285285/117769246-0a0d8a80-b266-11eb-989f-f1decdeacebf.png">

## Action Performed:
1. Sign in at staging.expensify.cash.
2. Notice how the screen goes blank shortly after the loading spinner disappears.. Open the console and check for the error.

## Workaround:
Refreshing the page fixes things.

## Platform:
Where is this issue occurring?

 Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by yuwenmemon** [comment]
Hmmm... I can't seem to reproduce - @jasperhuangg were you able to re-trigger by deleting something?
