### ISSUE TITLE
Have the draft icon always be visible in the LHN when there is a draft

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/Expensify.cash#2807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Show the draft 'pencil' for all chats, even the one you are currently looking at

## Actual Result:
In e.cash, when a report has a draft comment, the LHN only shows the draft icon (pencil) visible for non-selected chats.

## Action Performed:

1. Select a chat
2. Begin writing a comment
3. Look at the LHN and there won't be a pencil icon
4. Switch to another chat
5. Look at the LHN and you'll see the pencil icon for the previous chat you were in

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes, though this will improve the experience. 

## Platform:
Where is this issue occurring?

All platforms

**Version Number:** All versions
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/163084

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by parasharrajat** [comment]
We have to remove the Active Reportcheck on line 88 from here
https://github.com/Expensify/Expensify.cash/blob/1f541bb4353a512ffcbec81731533e3ae3543b8b/src/libs/OptionsListUtils.js#L87-L91
and now icon would be visible for all chats in LHN.

**Comment by Julesssss** [comment]
Looks good to me. @bfitzexpensify can we hire @parasharrajat please

**Comment by bfitzexpensify** [comment]
Hired you @parasharrajat. Feel free to get cranking on a PR!
