### ISSUE TITLE
New group - App crashes when initiating chat with newly created group

### ISSUE THREAD

**Issue by isagoico** [Expensify/Expensify.cash#2809]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
User able to type and initiate group chat

## Actual Result:
App crashes 

## Action Performed:
1. Launch the app and login
2. Create a group with 4 users
3. Focus on the input field to type

## Workaround:
N/A 

## Platform:
Where is this issue occurring?

 Web
 iOS ✔️ 
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.42-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/44479856/117888149-b6a83600-b27f-11eb-9250-f748096b302a.mp4
[Expensify.cash-2021-05-11-173651.txt](https://github.com/Expensify/Expensify.cash/files/6462184/Expensify.cash-2021-05-11-173651.txt)

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by Christinadobrzyn** [comment]
Hum, here's a video of the testing I've tried, is this the same issue you see on th e.cash mobile app?

• Open the e.cash mobile app
• Tap the '+'  > tap New Group
• Add 4 members to the group
• Tap Create Group
• The screen goes blank - group doesn't load

@isagoico Is this the same issue you see? Here's a video. 


https://user-images.githubusercontent.com/51066321/117907771-edc32980-b309-11eb-84c7-92500c80f9fd.MP4

**Comment by trjExpensify** [comment]
Just tested on `1.0.42-1` and can confirm the app crashes upon focusing on the input field to type.

**Comment by Jag96** [comment]
It looks like the issue here is `TypeError: undefined is not an object (evaluating 'this.props.report.participants.includes')`, which references [this line](https://github.com/Expensify/Expensify.cash/pull/2740/files#diff-7fa482b2895f4e36a2a3ad8233496489c6de1256a8c992524e2fc072aaba43f8R292) from https://github.com/Expensify/Expensify.cash/pull/2740.

@tugbadogan can you please look into this?
