### ISSUE TITLE
 🤯   Expensify.cash crashing on web.

### ISSUE THREAD

**Issue by parasharrajat** [Expensify/Expensify.cash#2902]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
When we resize the page, the page hangs forever. This is happening while implementing changes for https://github.com/Expensify/Expensify.cash/pull/2822/ I have minimized all the state changes for this PR. It does not seem to cause infinite rendering to block the thread. After Observations, I found few things that are putting unnecessary load on the js thread.
1. WithWindowDimensions `change` listners.
2. Tooltips' componentDidUpdate https://github.com/Expensify/Expensify.cash/blob/4d5f11883f23370a2c13a71bbd5c2ae968e27b7b/src/components/Tooltip/index.js#L51.
 
After debugging it through with Dev-tools Performance. I saw that `onDimensionsChange` creates n number of microtask which further causes the tree to be reconciled on React. Same for Tooltips' `this.setStateIfMounted` which seems to be the cause of it. (Visible on Dev-tools Snapshot) I tried a simple implementation(for testing purposes only I don't recommend it either) where we use Onyx to provide the dimensions change (Once discussed https://github.com/Expensify/Expensify.cash/issues/2517), there was no further crash and Also I see improvement in page layout's delay. You can compare it in the Videos below.

<details>
<summary>Before</summary>

https://user-images.githubusercontent.com/24370807/118194333-d51c5600-b466-11eb-9128-aa89677c313f.mp4

</details>

 
<details>
<summary>After</summary>

https://user-images.githubusercontent.com/24370807/118196758-32b2a180-b46b-11eb-8301-9b8971102362.mp4

</details>

### DEV-Tools

|Before(Only one resize or Drag) | After (Includes multiple resize or drags. One big task is basically a single resize event) |
|----------|----------|
|![crash](https://user-images.githubusercontent.com/24370807/118195632-347b6580-b469-11eb-83a4-d0657a2a7592.png)|![crash-optimized](https://user-images.githubusercontent.com/24370807/118195781-7e644b80-b469-11eb-8e99-fd69b4b6ad10.png)|

Check the Layout Shit which should happen but in the first image we have a lot of tasks to be done after layout shift but in the next image task finishes after layout shift. It proves there are unnecessary calculations in the first case.

#### Tooltip Issue

1. Every resizes basic cause re-render for all tooltips on the page(It can be seen as `setStateIfMounted` calls on the Dev-tool report)  to recalculate dimensions but we don't really need it as there is no tooltip visible on the page. But there could be 100 tooltips on the page that can trigger update down the tree. We are already calculating the dimensions on the `showtooltip` method https://github.com/Expensify/Expensify.cash/blob/4d5f11883f23370a2c13a71bbd5c2ae968e27b7b/src/components/Tooltip/index.js#L129.

## Dev-Tool Report Data
1. Crash https://drive.google.com/file/d/1wNjIbW-M0WT5TyHZYUpIxkdaK3SQQ_EX/view?usp=sharing
2. After changes https://drive.google.com/file/d/1nlfehFs_WAr1Kp8l1tbxVgELz9dJ7Bhx/view?usp=sharing

## Expected Result:
 The page should resize without issues and it should not crash.

## Actual Result:
  Page is crashed.

## Action Performed:
1. Open E.cash on web.
2. Apply the following PR https://github.com/Expensify/Expensify.cash/pull/2822.
3. Now open the Context menu on any message.
4. Start resizing the browser and see the context menu scale/reposition accordingly but after some time page is hanged.

## Workaround:
Kill the tab and open the app on a new tab.

## Platform:
Where is this issue occurring?

 Web :white_check_mark: 
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** Latest
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by mallenexpensify** [comment]
@parasharrajat apologies for the delay, just noticed this now.  Can you confirm this is still happening? If so I'll move this issue along for review

**Comment by parasharrajat** [comment]
I will test it again. @mallenexpensify

**Comment by mallenexpensify** [comment]
Any luck with testing @parasharrajat ?

**Comment by parasharrajat** [comment]
Sorry, Checking it now @mallenexpensify

**Comment by parasharrajat** [comment]
@mallenexpensify Closing it looks like it's not happening anymore.

**Comment by mallenexpensify** [comment]
Thanks for reporting and checking up on it @parasharrajat
