### ISSUE TITLE
Android Production Deploys are failing

### ISSUE THREAD

**Issue by Jag96** [Expensify/Expensify.cash#2918]
Keeping this issue internal since this requires Google Play access to confirm the builds show up in the internal track
cc @Expensify/mobile-deployers 

## Expected Result:
Android deploys such as [this one](https://github.com/Expensify/Expensify.cash/commit/66421d9a5c3bd916c9d454638b45c4c25f0eea00/checks) should succeed

## Actual Result:
Android deploys are failing with the following error message:
`Track 'internal' doesn't have any releases`

## Action Performed:
This happens during the `Run Fastlane` step of the [Build and Deploy Android 
 action](https://github.com/Expensify/Expensify.cash/commit/66421d9a5c3bd916c9d454638b45c4c25f0eea00/checks)

## Platform:
Where is this issue occurring?
- Android

For the run mentioned above, we see `[22:53:31]: Found '1001004400' version codes in track 'internal'` in the logs, and in the google play console we see that the 1.0.44-0 release is in the Internal Testing track, but for some reason fastlane still doesn't see the release.

Potentiall related: https://github.com/fastlane/fastlane/issues/18497

**Comment by AndrewGable** [comment]
@roryabraham did you have any ideas or additional context on this one? Thanks!

**Comment by roryabraham** [comment]
Any @Expensify/mobile-deployers have any extra bandwidth to look into this?

**Comment by Jag96** [comment]
Had a quick look at this today since the build failed again, going to create a PR to see if I can get it working. Notes:

- Since version 2.135.0, it seems that Google Play automatically removes releases that are superseded ([see check_superseded_tracks](https://docs.fastlane.tools/actions/upload_to_play_store/#migration-from-androidpublisherv2-to-androidpublisherv3-in-fastlane-21350))
- The code that throws this error is [here](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L187)
- When we create the production build, we're re-using the previously used version, but we don't specify `version_codes_to_retain` in the `upload_to_play_store` config, which could be causing the issue
- Looking at [this failed build](https://github.com/Expensify/Expensify.cash/runs/2769334418?check_suite_focus=true), the build fails at `00:42:00` whereas the [next closest build](https://github.com/Expensify/Expensify.cash/runs/2769343580?check_suite_focus=true) uploads at `00:55:00`, so it doesn't look like this is caused by a new build overwriting the old one

**Comment by Jag96** [comment]
Or it could be b/c the version_code is just set to 0 🤦 
![image](https://user-images.githubusercontent.com/3981102/121120907-661aee80-c7d3-11eb-9abe-7007aa4837f6.png)

**Comment by Jag96** [comment]
Ok, not sure what the issue is here. Running [the echo command](https://github.com/Expensify/Expensify.cash/blob/f38f41ef96ec94c77d9ac423263271257a99b0b6/.github/workflows/platformDeploy.yml#L51) that sets the output seems to be working find locally, and the path seems correct since we run [similar commands](https://github.com/Expensify/Expensify.cash/blob/f38f41ef96ec94c77d9ac423263271257a99b0b6/.github/workflows/platformDeploy.yml#L139) that make it seem we're in the root. cc @AndrewGable in case you have any ideas since you wrote the regex

**Comment by AndrewGable** [comment]
Yeah I think I see the bug, looks [like this should be `VERSION_CODE`](https://github.com/Expensify/Expensify.cash/blob/f38f41ef96ec94c77d9ac423263271257a99b0b6/.github/workflows/platformDeploy.yml#L61) because in Ruby we expect it to be that name instead of [`VERSION`](https://github.com/Expensify/Expensify.cash/blob/f38f41ef96ec94c77d9ac423263271257a99b0b6/fastlane/Fastfile#L58)

**Comment by Jag96** [comment]
Looks like this is still happening here: https://github.com/Expensify/Expensify.cash/runs/2778864820?check_suite_focus=true

**Comment by AndrewGable** [comment]
I believe we've narrowed it down to the regex doesn't work on Ubuntu and used to work on MacOS

**Comment by roryabraham** [comment]
After confirming that the current regex doesn't work in our ubuntu VMs, I found a variation that _does_ seem to work in both ubuntu and macOS:

```bash
echo "VERSION_CODE=$(grep -e 'versionCode\s\+[0-9]\+' android/app/build.gradle | awk '{ print $2 }')"
```
