### ISSUE TITLE
Change "Settled Up With Expensify" report comment to "Settled up!" when using "Pay with Expensify"

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/Expensify.cash#3876]
### **Problem**
Following up on [this post](https://expensify.slack.com/archives/C03U7DCU4/p1625163144431200), our current report comment when settling up in-app is "Settled up with Expensify". Since we expect the vast majority of users to use our in-app payment method, the "Expensify" is a bit overkill.

![image](https://user-images.githubusercontent.com/22508290/124335627-e3cee180-db68-11eb-99cc-2286cb9932e4.png)

### **Solution**
Let's change the report comment for in-app payments to simply be "Settled up!".

**Comment by Luke9389** [comment]
Thx @kevinksullivan for making this issue!

**Comment by Beamanator** [comment]
Randomly stumbled upon this - shouldn't it be closed? :D

**Comment by Luke9389** [comment]
It is closed–I don't know what you're talking about 😄

**Comment by Luke9389** [comment]
I wasn't seeing it on my K2 bc it wasn't labeled.

**Comment by Beamanator** [comment]
Aah there must be a TZ issue here - I see you closed it just ~after~ before I commented 🤣
