### ISSUE TITLE
App is crashing after entered an email of an account to add to the workspace

### ISSUE THREAD

**Issue by Jag96** [Expensify/Expensify.cash#3944]
Coming from https://github.com/Expensify/Expensify.cash/pull/3681#issuecomment-876879397

## Expected Result: 
Able to add the number of accounts to the workspace
## Actual Result:
App is crashing after entered an email of account
## Actions Performed:
1. Lunch the app
2. Log in with expensifail account
3. Click on Plus button and Select Workspace
4. Tap the workspace
5. Tap the "People" option on the next screen
6. use the green Invite button which will bring in a modal from a side.
7. Enter an email of an account you want to add to the workspace
## Platform:
iOS 
mWeb 
Android ✔️
## Build:
1.0.76-0
## Notes/Images/Video:
![Bug5144843_Screenshot_20210708-220331_One_UI_Home](https://user-images.githubusercontent.com/43996225/125017598-7aa40e00-e041-11eb-8635-77a6b5e7f374.jpg)

https://user-images.githubusercontent.com/43996225/125017601-7b3ca480-e041-11eb-8c0a-3e9fd50ef4f9.mp4

[log file.txt](https://github.com/Expensify/Expensify.cash/files/6788419/log.file.txt)

**Comment by rdjuric** [comment]
@Jag96 Looks like it's the same root cause as #3923?

**Comment by Jag96** [comment]
Ah perfect! Yup that should fix it, closing this, good 👀
