### ISSUE TITLE
'Send' button incorrect color when no text is entered into the message field

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/Expensify.cash#983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

View the job on Upwork [here](https://www.upwork.com/jobs/~01bed4c451e8bdd92e)

**Platform - version:**  

All platforms + versions

**Action Performed (reproducible steps):**

Open app, enter text and clear text, observing the 'send' button.

**Expected Result:**

Button should be grey when no text is entered.

**Actual Result:**

Button is green when no text has been entered.

**Notes/Photos/Videos:** 

Expected:

![image](https://user-images.githubusercontent.com/38236554/102396550-fa3d9300-3fb2-11eb-989d-679fb30abacd.png)

Actual:

![image](https://user-images.githubusercontent.com/38236554/102396487-e3973c00-3fb2-11eb-8982-ce4dd0204258.png)

 
**Logs - JS/Android/iOS (if applicable)**:

**Comment by laurenreidexpensify** [comment]
Have approached [Bharat](https://www.upwork.com/fl/bharatvasoya3) and [Aashish](https://www.upwork.com/fl/aashishsharma44) - Bharat has already accepted

**Comment by BharatVasoya** [comment]
I am working on this issue.

**Comment by shanky97** [comment]
I am working on this and completed it here is the PR link - https://github.com/Expensify/Expensify.cash/issues/983
