### ISSUE TITLE
The cursor looks too close to the left edge

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/Expensify.cash#987]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

View the job on Upwork [here](https://www.upwork.com/jobs/~012aa302a196a4cc88)

**Platform - version:**  
Build version : Android 8.0
Device and OS: SG S8

**Action Performed (reproducible steps):**
1.  Launch the app and login
2. On the search box, search any user you have access to.

Tester login credentials - Password	: Feya86Katya
Tester login credentials - Email/Phone	: abeccivutest+1028@gmail.com

**Expected Result:**
The cursor should be placed a bit off typing field.

**Actual Result:**
The cursor looks too close to the edge.

**Notes/Photos/Videos:** 

![image](https://user-images.githubusercontent.com/38236554/102400860-daa96900-3fb8-11eb-9a08-3f8f408790c2.png)

**Comment by bfitzexpensify** [comment]
Have sent offers to [Rakesh](https://www.upwork.com/ab/c/8577561/offer/14759785) and [Chris](https://www.upwork.com/ab/c/8577561/offer/14759780)

**Comment by UpworkBartkoski** [comment]
I'm working on this.

**Comment by rakesh1504** [comment]
I am working on this.
