### ISSUE TITLE
Email addresses aren't showing properly linked in Chat

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#990]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

View the job on Upwork [here](https://www.upwork.com/jobs/~0138bdf88bcff83060).

**Platform - version:**  
Build 263, all platforms

**Action Performed (reproducible steps):**
1. Send an email address in a message via the chat box

**Expected Result:**
It should render as a mailto link.

**Actual Result:**
It renders only the domain part of the email and it renders it as a normal hyperlink

**Notes/Photos/Videos:** 
![100033378-ebe2c980-2dae-11eb-9d1c-d2c3ced1ffb9](https://user-images.githubusercontent.com/24399930/102404251-6ae5af00-3fb5-11eb-85f2-dee5d2d90fb6.png)

**Comment by nicodev-git** [comment]
I am working on this issue.

**Comment by roryabraham** [comment]
This was fixed and merged a last week
