### ISSUE TITLE
Code block markdown inserts improper line breaks

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#993]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Upwork job: https://www.upwork.com/jobs/~01921d7b980ffc182b

**Platform - version:** ALL

**Action Performed (reproducible steps):**

- Log into expensify.cash
- Send a message containing a code block (framed by ```) longer than 1 line, and with a double dash " -- " to observe the formatting.

The example text is:

_Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra feugiat ipsum sit amet dapibus. Donec eu euismod metus, viverra tempor lacus. In semper, magna vel eleifend ultrices, nisi turpis facilisis metus, ac tristique nisi sem non est. Quisque tempus turpis vitae lectus maximus tincidunt. Fusce tempor nisl et condimentum lacinia. Sed tellus arcu, commodo vitae lorem et, tincidunt porttitor -- magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum sem tellus, tempus in vulputate a, tempor eleifend massa. Morbi a dolor ut est tincidunt consectetur non at justo. Nullam sem erat, gravida in ipsum ac, facilisis faucibus ex. Morbi venenatis turpis justo, vitae interdum sapien venenatis quis. Duis dictum ornare -- massa, ac mollis quam sagittis non. Vivamus metus tellus, ultricies eu metus vel, pharetra vulputate nunc. Nulla nec ex ac orci dignissim imperdiet._

**Expected Result:**

The code block should wrap full words onto the next line, and the double dash " -- " should not cause a line break.

**Actual Result:**

Words are broken in the middle, and each time a double dash appears there is a line break in the middle of the two dashes.

**Notes/Photos/Videos:** 
 
![image](https://user-images.githubusercontent.com/59587260/102417219-24995a00-4060-11eb-8170-0fda04d31fba.png)

**Comment by ronlaniado** [comment]
I've been workng on this issue

**Comment by parasharrajat** [comment]
Hey, I have started on this issue. But I am not able to signup on expensify.cash. I used my email but I didn't get any email and now it's asking for a password.

**Comment by parasharrajat** [comment]
@kadiealexander add a pull request to the Expensify/common repo which will potentially solve this problem. Let me if there are any queries.

Thanks

**Comment by stephanieelliott** [comment]
@parasharrajat this PR should be submitted on the **Expensify/Expensify.Cash** repository. You can find the instructions for submitting your PR here: https://github.com/Expensify/Expensify.cash/blob/master/CONTRIBUTING.md

**Comment by parasharrajat** [comment]
@stephanieelliott  Will do that waiting for the original PR to be merged.

**Comment by parasharrajat** [comment]
@stephanieelliott @kadiealexander  @laurenreidexpensify Due to my other PR on **Expensify/Expensify-common** this issue got closed here. Please look at the above PR which patches the fix on **Expensify/Expensify.Cash**  and thus resolves it.

Thanks.

**Comment by marcaaron** [comment]
Any context for why this was reopened?

**Comment by kadiealexander** [comment]
Just a mistake, sorry Marc!
